#define API_VERSION       "1.19"

#define PLUGIN_VERSION_MAJOR 0
#define PLUGIN_VERSION_MINOR 5
#define PLUGIN_VERSION_PATCH 0
#define PLUGIN_VERSION_TWEAK 0

#define PKG_PRERELEASE ""
#define PKG_BUILD_INFO "2606301034.db2f43e"

#define PLUGIN

