/*********************************************************************
 * Name:      	main.h
 * Purpose:   	Declares simple wxWidgets application with GUI
 * 				created using wxFormBuilder.
 * Author:
 * Created:
 * Copyright:
 * License:   	wxWidgets license (www.wxwidgets.org)
 *
 * Notes:		Note that all GUI creation code is declared in
 * 				gui.h source file which is generated by wxFormBuilder.
 *********************************************************************/

#ifndef __main__
#define __main__

// main wxWidgets header file
#include <wx/wx.h>

#include "ocpn_plugin.h"

#include "gui.h"
#include "ncdf_reader.h"
#include "wx/wfstream.h"
#include <wx/datetime.h>
#include <vector>
#include <wx/dirdlg.h>

#include <stdio.h>
#include <stdlib.h>
#include <netcdf.h>
#include <list>

#define NDIMS 3

#define LAT_NAME "latitude"
#define LON_NAME "longitude"
#define TIME_NAME "time"
#define V_NAME "v"
#define U_NAME "u"

#define ERR(e) { return 2; }

////////////////////////////////////////////////////////////////////////////////
// main application frame declaration
////////////////////////////////////////////////////////////////////////////////
#ifndef PI
#define PI        3.1415926535897931160E0      /* pi */
#endif

using namespace std;


struct Selection
{
    wxDouble topLat;
    wxDouble topLon;
    wxDouble bottomLat;
    wxDouble bottomLon;
};

class ncdf_pi;
class ncdfDataMessage;
class Arrow;

struct CurrentData {
	double dir;
	double force;
};

class MainDialog : public ncdfDialog {
public:
	MainDialog( wxWindow *parent );
	virtual ~MainDialog();

	ncdfReader 	*my_ncdfReader;

	void SetCursorLatLon(double lat, double lon);
	void setPlugIn(ncdf_pi *p);

	ncdf_pi	*pPlugIn;
	wxWindow	*m_parent;
	Selection	selectionRectangle;
	double		m_cursor_lon, m_cursor_lat;
	double *my_ucurr = 0;
	double *my_vcurr = 0;
	int treeMinutes[96];

	// Lightweight file metadata (for tree building, no data allocation)
	struct FileMetadata {
		bool valid;
		bool hasCurrent, hasSeaTemp, hasSalinity;
		size_t timelength, latlength, lonlength;
		wxDouble firstGridPointLat, firstGridPointLong;
		wxDouble lastGridPointLat, lastGridPointLong;
		wxDouble iDirectionIncr, jDirectionIncr;
		int cached_u_varid, cached_v_varid, cached_sst_varid, cached_sal_varid;
		std::vector<wxDateTime> dates;
		std::vector<bool> timeValid;
		std::vector<double> timeValues;
		std::shared_ptr<SharedCoords> sharedCoords;
		FileMetadata() : valid(false), hasCurrent(false), hasSeaTemp(false), hasSalinity(false),
			timelength(0), latlength(0), lonlength(0),
			firstGridPointLat(0), firstGridPointLong(0),
			lastGridPointLat(0), lastGridPointLong(0),
			iDirectionIncr(0), jDirectionIncr(0),
			cached_u_varid(-1), cached_v_varid(-1),
			cached_sst_varid(-1), cached_sal_varid(-1) {}
	};
	FileMetadata nc_read_metadata(const wxString &fileName);

	bool m_fileHasCurrent = false;   // File contains u/v ocean current data
	bool m_fileHasSeaTemp = false;   // File contains SST data
	bool m_fileHasSalinity = false;  // File contains salinity data
	int m_cached_u_varid = -1;       // Cached NetCDF variable ID for u-current
	int m_cached_v_varid = -1;       // Cached NetCDF variable ID for v-current
	int m_cached_sst_varid = -1;     // Cached NetCDF variable ID for SST
	int m_cached_sal_varid = -1;     // Cached NetCDF variable ID for salinity

	// Persistent NetCDF file handle (reused across same-file time step switches)
	int m_openedNcid = -1;
	wxString m_openedFileName;

	// Pre-allocated data buffers (file-level, reused across time steps to avoid 32-bit heap fragmentation)
	std::vector<double> m_fileUBuffer;
	std::vector<double> m_fileVBuffer;
	std::vector<double> m_fileSSTBuffer;
	std::vector<double> m_fileSalBuffer;
	bool m_fileBufferReady;

	ncdfDataMessage myncdfData, myData, myMessage;
	vector<ncdfDataMessage> myDataVector;
	int m_lastSelectedTimeIndex;
	int ncdf_get_data(wxString filestr);
	int ncdf_get_keys(wxString filestr);
	int nc_get(wxString filestr);

	int ncdf_get_ncdf1();
	double** makeGridDataCURRENT(ncdfDataMessage message, wxString current);
	int np;
	void OnContextMenu(double m_lat, double m_lon);
	void BuildHelpPage();
	CurrentData getCurrentData(double lat, double lon);
	std::list<Arrow*> m_ArrowList;
	
	bool readTimeStepData(ncdfDataMessage& dataMessage);
	bool m_isTreeUpdating;
	bool m_isLoading{false};  // Guard against re-entrant time step loads
	bool m_dataLoaded{false};  // True when myMessage has data for current time step
	bool m_gridsReady{false};  // True when float grids are prepared (Phase 2 complete)
	wxString m_currentFilePath;  // Track which file is currently loaded


private:
	void UpdateTrackingControls();
	void printCurrentData();
	bool switchToFile(const wxString &fileName, const wxString &fn, int &idx);



	wxString toBeaufort(wxFloat32 w);
	wxLogWindow *log_window_m;



protected:
	// protected event handlers
	virtual void OnCloseFrame( wxCloseEvent& event );
	virtual void onCloseDialog( wxCloseEvent& event );
	virtual void OnExitClick( wxCommandEvent& event );
	virtual void onFileButtonClick(wxCommandEvent& event);



	wxDateTime GetDateFromHours(int hours_in);

	virtual void onDirChanged(wxCommandEvent& event);
	virtual void onTreeSelectionChanged(wxTreeEvent& event);
	virtual void onTreeItemRightClick(wxTreeEvent& event);
	virtual void onDCurrentClick( wxCommandEvent& event );
	virtual void onBmpCurrentForceClick( wxCommandEvent& event );
	virtual void onParticlesClick( wxCommandEvent& event );
	virtual void onSeaTempClick( wxCommandEvent& event );
	virtual void onSalinityClick( wxCommandEvent& event );
	virtual void onAnimateClick( wxCommandEvent& event );
	virtual void onAnimateSSTClick( wxCommandEvent& event );
	virtual void onAnimateSalClick( wxCommandEvent& event );
	virtual void onIsoSSTClick( wxCommandEvent& event );
	virtual void onIsoSalClick( wxCommandEvent& event );
	void fillDirTree(wxString dir, bool start, wxTreeItemId id);
	void addChildren(wxTreeItemId id, wxString s);
	void readData(wxTreeItemId itemId);

};

class MyTreeItemData : public wxTreeItemData
{
public:
	MyTreeItemData(int index) : m_index(index) {}
	int m_index;
};


class Arrow
{
public:
	double m_dir;
	double m_force;
	double m_lat;
	double m_lon;

};

#endif //__main__
