/*********************************************************************
 * Name:      	main.cpp
 * Purpose:   	Implements simple wxWidgets application with GUI
 * 				created using wxFormBuilder.
 * Author:      Mike Rossiter

 * Created:
 * Copyright:
 * License:
 *
 * Notes:		Note that all GUI creation code is implemented in
 * 				gui.cpp source file which is generated by wxFormBuilder.
 *********************************************************************/

#include "stdio.h"
#include <chrono>
#include "wx/wx.h"
#include "wx/dir.h"
#include <wx/wfstream.h>
#include <wx/sstream.h>
#include <wx/protocol/http.h>
#include <wx/treectrl.h>
#include <wx/treebase.h>
#include <wx/hash.h>
#include <wx/utils.h>
#include <wx/log.h>
#include <wx/stdpaths.h>

#include "folder.xpm"

#include "ncdf.h"
#include "ncdf_reader.h"
#include "ncdfdata.h"
#include "ncdf_pi.h"
#include "ncdfoverlayfactory.h"
#include "ncdf_animate.h"
#include <vector>
#include <algorithm>

using namespace std;

void ncdfLog(const char* format, ...) {
    FILE *logFile = fopen("C:\\ProgramData\\opencpn\\ncdf_debug.log", "a");
    if (logFile) {
        va_list args;
        va_start(args, format);
        vfprintf(logFile, format, args);
        va_end(args);
        fflush(logFile);
        fclose(logFile);
    }
}

// Memory tracker: log estimated memory usage from vector/overlay sizes
static void ncdfLogMem(MainDialog *dlg, const char* tag) {
    if (!dlg) return;
    ncdf_pi *p = dlg->pPlugIn;
    ncdfOverlayFactory *f = p ? p->GetncdfOverlayFactory() : NULL;
    size_t msgMem = dlg->myMessage.ucurr.capacity() * sizeof(double)
                  + dlg->myMessage.vcurr.capacity() * sizeof(double)
                  + dlg->myMessage.sst.capacity() * sizeof(double)
                  + dlg->myMessage.salinity.capacity() * sizeof(double);
    size_t gridMem = 0;
    if (f) {
        auto gridBytes = [](float** g, int nj) -> size_t {
            if (!g) return 0;
            size_t bytes = nj * sizeof(float*);
            for (int j = 0; j < nj; j++) if (g[j]) bytes += sizeof(float) * 4320; // approximate
            return bytes;
        };
        gridMem += gridBytes(f->m_currentOverlay.cachedU, f->m_currentOverlay.cachedUNj);
        gridMem += gridBytes(f->m_currentOverlay.cachedV, f->m_currentOverlay.cachedUNj);
        gridMem += gridBytes((float**)f->m_seaTempOverlay.cachedBaseGrid.get(), f->m_seaTempOverlay.cachedNj);
        gridMem += gridBytes((float**)f->m_salinityOverlay.cachedBaseGrid.get(), f->m_salinityOverlay.cachedNj);
    }
    ncdfLog("[mem:%s] myMessage=%.1fMB grids=%.1fMB total=%.1fMB\n",
        tag, msgMem / (1024.0*1024.0), gridMem / (1024.0*1024.0), (msgMem + gridMem) / (1024.0*1024.0));
}

static void ncdfLogW(const wchar_t* format, ...) {
    FILE *logFile = fopen("C:\\ProgramData\\opencpn\\ncdf_debug.log", "a");
    if (logFile) {
        va_list args;
        va_start(args, format);
        vfwprintf(logFile, format, args);
        va_end(args);
        fflush(logFile);
        fclose(logFile);
    }
}

MainDialog::MainDialog(wxWindow *parent) : ncdfDialog( parent ), m_isTreeUpdating(false)
{
	ncdfLog("[ncdf] MainDialog constructor: started\n");
	
	this->my_ncdfReader = new ncdfReader(this);
	
	ncdfLog("[ncdf] MainDialog constructor: ncdfReader created\n");
	
	this->m_parent = parent;
	selectionRectangle.bottomLat = selectionRectangle.bottomLon
	= selectionRectangle.topLat = selectionRectangle.topLon = ncdf_NOTDEF;

	log_window_m = NULL;
	m_lastSelectedTimeIndex = -1;

	// Hide all data checkboxes by default (shown when data is loaded)
	m_checkBoxBmpCurrentForce->Hide();
	m_staticText40->Hide();
	m_textCtrlCurrentForce->Hide();
	m_staticText41->Hide();
	m_checkBoxSeaTemp->Hide();
	m_staticTextSeaTemp->Hide();
	m_textCtrlSeaTemp->Hide();
	m_staticTextSeaTempUnit->Hide();
	m_checkBoxSalinity->Hide();
	m_staticTextSalinity->Hide();
	m_textCtrlSalinity->Hide();

	BuildHelpPage();

	/* Ensure dialog and its contents can be resized */
	this->SetWindowStyleFlag(this->GetWindowStyleFlag() | wxRESIZE_BORDER);
	this->SetSizeHints(280, 460, -1, -1);
	this->Layout();
}

MainDialog::~MainDialog()
{
	ncdfLog("[ncdf] ~MainDialog: started\n");

	// Close persistent NetCDF file handle
	if (m_openedNcid >= 0) {
		nc_close(m_openedNcid);
		m_openedNcid = -1;
	}

	// Disconnect prev/next buttons


	if(log_window_m)
		delete log_window_m;
	
	ncdfLog("[ncdf] ~MainDialog: log_window_m deleted\n");

	delete my_ncdfReader;
	
	ncdfLog("[ncdf] ~MainDialog: my_ncdfReader deleted\n");
	

	pPlugIn->m_bShowCurrentDir = m_checkBoxDCurrent->GetValue();
	pPlugIn->m_bShowCurrentDir = m_checkBoxDCurrent->GetValue();
	pPlugIn->m_bShowCurrentForce = m_checkBoxBmpCurrentForce->GetValue();
	pPlugIn->m_bShowParticles = m_checkBoxParticles->GetValue();
	pPlugIn->m_bShowSeaTemp = m_checkBoxSeaTemp->GetValue();
	pPlugIn->m_bShowSalinity = m_checkBoxSalinity->GetValue();

	ncdfLog("[ncdf] ~MainDialog: settings saved\n");
	
	myDataVector.clear();
	
	ncdfLog("[ncdf] ~MainDialog: myDataVector cleared\n");
	
	ncdfLog("[ncdf] ~MainDialog: completed\n");
}

void MainDialog::setPlugIn(ncdf_pi *p)
{
  this->pPlugIn = p;
  this->m_textCtrlDir->SetValue(pPlugIn->m_ncdf_dir);
  fillDirTree(pPlugIn->m_ncdf_dir, true, 0);
  m_checkBoxDCurrent->SetValue(pPlugIn->m_bShowCurrentDir);
  m_checkBoxBmpCurrentForce->SetValue(pPlugIn->m_bShowCurrentForce);
  m_checkBoxParticles->SetValue(pPlugIn->m_bShowParticles);
  m_checkBoxSeaTemp->SetValue(pPlugIn->m_bShowSeaTemp);
  m_checkBoxSalinity->SetValue(pPlugIn->m_bShowSalinity);
  m_checkBoxIsoSST->SetValue(pPlugIn->m_settingsSeaTemp.showIsoLines);
  m_checkBoxIsoSal->SetValue(pPlugIn->m_settingsSalinity.showIsoLines);
}

void MainDialog::SetCursorLatLon(double lat, double lon)
{
      m_cursor_lon = lon;
      m_cursor_lat = lat;

      UpdateTrackingControls();
}

void MainDialog::UpdateTrackingControls()
{
   ncdfOverlayFactory *pof = pPlugIn ? pPlugIn->GetncdfOverlayFactory() : NULL;

   // Current speed at cursor position — from float grid
   this->m_textCtrlCurrentForce->Clear();
   if (pof && pof->m_currentOverlay.cachedU && pof->m_currentOverlay.cachedV) {
       printCurrentData();
   }

   // SST temperature at cursor position — from float grid
   m_textCtrlSeaTemp->Clear();
   if (pof && pof->m_seaTempOverlay.cachedBaseGrid) {
       double temp = myMessage.getInterpolatedValueFloat(
           pof->m_seaTempOverlay.cachedBaseGrid.get(),
           (int)myMessage.lonLength, (int)myMessage.latLength,
           myMessage.firstGridPointLat, myMessage.lastGridPointLat,
           myMessage.firstGridPointLong, myMessage.lastGridPointLong,
           myMessage.iDirectionIncr, myMessage.jDirectionIncr,
           m_cursor_lon, m_cursor_lat);
       if (temp != ncdf_NOTDEF && !isnan(temp) && isfinite(temp)) {
           wxString t = wxString::Format(_T("%.1f"), temp) + wxString::FromUTF8("\xc2\xb0") + _T("C");
           m_textCtrlSeaTemp->SetValue(t);
       } else {
           m_textCtrlSeaTemp->SetValue(_T("--"));
       }
   }

   // Salinity at cursor position — from float grid
   m_textCtrlSalinity->Clear();
   if (pof && pof->m_salinityOverlay.cachedBaseGrid) {
       double sal = myMessage.getInterpolatedValueFloat(
           pof->m_salinityOverlay.cachedBaseGrid.get(),
           (int)myMessage.lonLength, (int)myMessage.latLength,
           myMessage.firstGridPointLat, myMessage.lastGridPointLat,
           myMessage.firstGridPointLong, myMessage.lastGridPointLong,
           myMessage.iDirectionIncr, myMessage.jDirectionIncr,
           m_cursor_lon, m_cursor_lat);
       if (sal != ncdf_NOTDEF && !isnan(sal) && isfinite(sal)) {
           wxString t = wxString::Format(_T("%.1f"), sal) + wxString::FromUTF8("\xe2\x80\xb0");
           m_textCtrlSalinity->SetValue(t);
       } else {
           m_textCtrlSalinity->SetValue(_T("--"));
       }
   }
}

void MainDialog::printCurrentData()
{
	  m_textCtrlCurrentForce->Clear();
	  ncdfOverlayFactory *pof = pPlugIn ? pPlugIn->GetncdfOverlayFactory() : NULL;
	  if (!pof || !pof->m_currentOverlay.cachedU || !pof->m_currentOverlay.cachedV) {
		m_textCtrlCurrentForce->SetValue(_T("--"));
		return;
	  }
	  wxString t;
	  double uOut, vOut;
	  bool ok = myMessage.getInterpolatedUVFloat(
		  pof->m_currentOverlay.cachedU, pof->m_currentOverlay.cachedV,
		  (int)myMessage.lonLength, (int)myMessage.latLength,
		  myMessage.firstGridPointLat, myMessage.lastGridPointLat,
		  myMessage.firstGridPointLong, myMessage.lastGridPointLong,
		  myMessage.iDirectionIncr, myMessage.jDirectionIncr,
		  m_cursor_lon, m_cursor_lat, uOut, vOut);

	  if (ok && isfinite(uOut) && isfinite(vOut)) {
		  double speed = sqrt(uOut*uOut + vOut*vOut);
		  t.Printf(_T("%.2f m/s"), speed);
		  m_textCtrlCurrentForce->SetValue(t);
	  } else {
		  m_textCtrlCurrentForce->SetValue(_T("--"));
	  }
}

CurrentData MainDialog::getCurrentData(double lat, double lon)
{
	CurrentData result = {0, 0};
	ncdfOverlayFactory *pof = pPlugIn ? pPlugIn->GetncdfOverlayFactory() : NULL;
	if (!pof || !pof->m_currentOverlay.cachedU || !pof->m_currentOverlay.cachedV) return result;

	double uOut, vOut;
	bool ok = myMessage.getInterpolatedUVFloat(
		pof->m_currentOverlay.cachedU, pof->m_currentOverlay.cachedV,
		(int)myMessage.lonLength, (int)myMessage.latLength,
		myMessage.firstGridPointLat, myMessage.lastGridPointLat,
		myMessage.firstGridPointLong, myMessage.lastGridPointLong,
		myMessage.iDirectionIncr, myMessage.jDirectionIncr,
		lon, lat, uOut, vOut);

	if (ok && isfinite(uOut) && isfinite(vOut)) {
		result.force = sqrt(uOut*uOut + vOut*vOut);  // m/s
		result.dir = 90. + (atan2(vOut, -uOut) * 180. / PI) - 180;
		if (result.dir < 0) result.dir = 360 + result.dir;
	}

	return result;
}


double** MainDialog::makeGridDataCURRENT(ncdfDataMessage message, wxString current){

	int y = message.noPointsMeridian, x = message.noPointsParallel;
	double** grid = new double*[y];
	grid[0] = new double[y*x];
	for (int i = 1; i < y; ++i)
		grid[i] = grid[i - 1] + x;

	unsigned int count = 0;
	int bit = 7;
	unsigned int index;
	index = 0;

	for (unsigned int lat = 0; lat < message.noPointsMeridian; lat++)
	{
		for (unsigned int lon = 0; lon < message.noPointsParallel; lon++)
		{
			if (current == _T("currentu")){
				grid[lat][lon] = message.ucurr[count++];
			}
			else if (current == _T("currentv")){
				grid[lat][lon] = message.vcurr[count++];
			}

		}
	}
	return grid;
}


void MainDialog::readData(wxTreeItemId itemId) {
    FILE *logFile = fopen("C:\\ProgramData\\opencpn\\ncdf_debug.log", "a");
    if (logFile) {
        fwprintf(logFile, L"[ncdf] readData: started, itemId=%p\n", itemId.m_pItem);
        fflush(logFile);
    }
    
	MyTreeItemData *data = (MyTreeItemData *) this->m_treeCtrl->GetItemData(itemId);
	
	if (logFile) {
        fwprintf(logFile, L"[ncdf] readData: data=%p\n", data);
        fflush(logFile);
    }
	
	if (data == NULL) {
		if (logFile) {
			fwprintf(logFile, L"[ncdf] readData: data is NULL, returning\n");
			fflush(logFile);
			fclose(logFile);
		}
		return;
	}

	int idx = data->m_index;
	if (logFile) {
        fwprintf(logFile, L"[ncdf] readData: index=%d, m_lastSelectedTimeIndex=%d, vectorSize=%d\n", 
            idx, m_lastSelectedTimeIndex, (int)myDataVector.size());
        fflush(logFile);
    }
	
	if (idx < 0 || idx >= (int)myDataVector.size()) {
		if (logFile) {
            fwprintf(logFile, L"[ncdf] readData: index out of range\n");
            fflush(logFile);
            fclose(logFile);
        }
		return;
	}
	
	if (m_lastSelectedTimeIndex >= 0 && m_lastSelectedTimeIndex < (int)myDataVector.size()) {
		if (logFile) {
            fwprintf(logFile, L"[ncdf] readData: clearing myDataVector[%d]\n", m_lastSelectedTimeIndex);
            fflush(logFile);
        }
		myDataVector[m_lastSelectedTimeIndex].clearData();
	}
	
	ncdfLog("[ncdf] readData: HELLO_SST_TEST idx=%d, vectorSize=%d\n", idx, (int)myDataVector.size());

	if (logFile) {
        fwprintf(logFile, L"[ncdf] readData: calling readTimeStepData for index=%d\n", idx);
        fflush(logFile);
    }
	if (!readTimeStepData(myDataVector[idx])) {
		ncdfLog("[ncdf] readData: readTimeStepData returned FALSE\n");
		if (logFile) {
            fwprintf(logFile, L"[ncdf] readData: readTimeStepData failed\n");
            fflush(logFile);
            fclose(logFile);
        }
		return;
	}

	ncdfLog("[ncdf] readData: readTimeStepData returned TRUE, calling readncdfFile\n");
	
	if (logFile) {
        fwprintf(logFile, L"[ncdf] readData: readTimeStepData succeeded\n");
        fflush(logFile);
    }
	
	m_lastSelectedTimeIndex = idx;

	if (logFile) {
        fwprintf(logFile, L"[ncdf] readData: updated m_lastSelectedTimeIndex=%d\n", m_lastSelectedTimeIndex);
        fflush(logFile);
    }
	
	if (logFile) {
        fwprintf(logFile, L"[ncdf] readData: calling readncdfFile\n");
        fflush(logFile);
    }
	this->my_ncdfReader->readncdfFile(myDataVector[idx]);
	
	if (logFile) {
        fwprintf(logFile, L"[ncdf] readData: readncdfFile returned\n");
        fflush(logFile);
    }
	
	pPlugIn->GetncdfOverlayFactory()->renderSelectionRectangle = false;
	RequestRefresh(m_parent);
	
	if (logFile) {
        fwprintf(logFile, L"[ncdf] readData: completed\n");
        fflush(logFile);
        fclose(logFile);
    }
}

void MainDialog::OnCloseFrame(wxCloseEvent& event) {

}

void MainDialog::onCloseDialog(wxCloseEvent& event)
{
    pPlugIn->OnncdfDialogClose();
}

void MainDialog::OnExitClick(wxCommandEvent& event) {
//	Destroy();
}

void MainDialog::onFileButtonClick(wxCommandEvent& event)
{
    ncdfLog("[ncdf] onFileButtonClick: started\n");
    
    wxDirDialog fd(this,_("Select a directory"),pPlugIn->m_ncdf_dir);
    ncdfLog("[ncdf] onFileButtonClick: dialog created\n");

    if(fd.ShowModal() != wxID_OK) {
        ncdfLog("[ncdf] onFileButtonClick: user canceled\n");
        return; 
    }
    
    ncdfLog("[ncdf] onFileButtonClick: directory selected\n");
    
    ncdfLog("[ncdf] onFileButtonClick: pPlugIn=%p\n", pPlugIn);
    
    pPlugIn->m_ncdf_dir = fd.GetPath();
    
    ncdfLog("[ncdf] onFileButtonClick: pPlugIn->m_ncdf_dir set\n");
    
    ncdfLog("[ncdf] onFileButtonClick: m_textCtrlDir=%p\n", m_textCtrlDir);
    
    this->m_textCtrlDir->SetValue(pPlugIn->m_ncdf_dir);
    
    ncdfLog("[ncdf] onFileButtonClick: m_textCtrlDir->SetValue done\n");
    
    ncdfLog("[ncdf] onFileButtonClick: completed\n");
}

/* Helper: read a text attribute from a variable. Caller must delete[] the result. */
static char* read_var_att_text(int ncid, int varid, const char* attname) {
    size_t attlen;
    if (nc_inq_attlen(ncid, varid, attname, &attlen) != NC_NOERR) return NULL;
    char* text = new char[attlen + 1];
    if (nc_get_att_text(ncid, varid, attname, text) != NC_NOERR) {
        delete[] text;
        return NULL;
    }
    text[attlen] = '\0';
    return text;
}

/* CF-compliant variable finder with three-tier priority:
   P1 (gold standard): exact standard_name match
   P2 (disambiguation): if multiple matches, return first with warning
   P3 (fallback): try long_name, then variable name, with WARNING log */
static int find_var_by_cf(int ncid,
                           const char* target_std_name,
                           const char** alt_std_names,
                           const char** long_name_hints,
                           const char** var_name_hints) {
    int nvars;
    if (nc_inq(ncid, NULL, &nvars, NULL, NULL) != NC_NOERR) return -1;
    
    /* ===== Priority 1: standard_name exact match ===== */
    int best_varid = -1;
    int match_count = 0;
    
    for (int i = 0; i < nvars; i++) {
        char* std_name = read_var_att_text(ncid, i, "standard_name");
        if (!std_name) continue;
        
        if (strcmp(std_name, target_std_name) == 0) {
            if (best_varid == -1) best_varid = i;
            match_count++;
        }
        delete[] std_name;
    }
    
    if (match_count == 1) return best_varid;
    
    /* ===== Priority 2: multiple matches ===== */
    if (match_count > 1) {
        ncdfLog("[ncdf] find_var_by_cf: WARNING - %d vars with standard_name='%s', using first (varid=%d)\n",
                match_count, target_std_name, best_varid);
        return best_varid;
    }
    
    /* ===== Try alternative standard_names ===== */
    if (alt_std_names) {
        for (const char** alt = alt_std_names; *alt; alt++) {
            for (int i = 0; i < nvars; i++) {
                char* std_name = read_var_att_text(ncid, i, "standard_name");
                if (!std_name) continue;
                if (strcmp(std_name, *alt) == 0) {
                    delete[] std_name;
                    ncdfLog("[ncdf] find_var_by_cf: matched alt standard_name='%s' (target was '%s')\n",
                            *alt, target_std_name);
                    return i;
                }
                delete[] std_name;
            }
        }
    }
    
    /* ===== Priority 3a: fallback to long_name ===== */
    if (long_name_hints) {
        for (const char** hint = long_name_hints; *hint; hint++) {
            for (int i = 0; i < nvars; i++) {
                char* long_name = read_var_att_text(ncid, i, "long_name");
                if (long_name && strcmp(long_name, *hint) == 0) {
                    ncdfLog("[ncdf] find_var_by_cf: WARNING - no standard_name, matched long_name='%s' for target='%s'\n",
                            *hint, target_std_name);
                    delete[] long_name;
                    return i;
                }
                if (long_name) delete[] long_name;
            }
        }
    }
    
    /* ===== Priority 3b: fallback to variable name ===== */
    if (var_name_hints) {
        for (const char** hint = var_name_hints; *hint; hint++) {
            int varid;
            if (nc_inq_varid(ncid, *hint, &varid) == NC_NOERR) {
                ncdfLog("[ncdf] find_var_by_cf: WARNING - no standard_name, matched variable name='%s' for target='%s'\n",
                        *hint, target_std_name);
                return varid;
            }
        }
    }
    
    return -1;
}

static int find_dim_by_var(int ncid, int varid, int dim_idx) {
    int ndims;
    nc_inq_varndims(ncid, varid, &ndims);
    if (dim_idx >= ndims) return -1;

    int* dimids = new int[ndims];
    nc_inq_var(ncid, varid, NULL, NULL, NULL, dimids, NULL);
    int dimid = dimids[dim_idx];
    delete[] dimids;
    return dimid;
}

/* Shared dimension discovery for any NetCDF variable.
   Matches variable dimensions to time/lat/lon/depth by comparing dimension IDs.
   Returns indices within the variable's dimension array. */
struct VarDimInfo {
    int time_idx, lat_idx, lon_idx, depth_idx;
    bool lat_before_lon;
    bool valid;
};

static VarDimInfo discover_var_dims(int ncid, int varid) {
    VarDimInfo info = {-1, -1, -1, -1, false, false};

    int ndims;
    if (nc_inq_varndims(ncid, varid, &ndims) != NC_NOERR) return info;

    int* dimids = (int*)calloc(ndims, sizeof(int));
    if (!dimids) return info;
    if (nc_inq_var(ncid, varid, NULL, NULL, NULL, dimids, NULL) != NC_NOERR) {
        free(dimids);
        return info;
    }

    int time_dimid = -1, lat_dimid = -1, lon_dimid = -1, depth_dimid = -1;

    nc_inq_dimid(ncid, "time", &time_dimid);

    if (nc_inq_dimid(ncid, "latitude", &lat_dimid) != NC_NOERR)
        if (nc_inq_dimid(ncid, "lat", &lat_dimid) != NC_NOERR)
            if (nc_inq_dimid(ncid, "y", &lat_dimid) != NC_NOERR)
                nc_inq_dimid(ncid, "nav_lat", &lat_dimid);

    if (nc_inq_dimid(ncid, "longitude", &lon_dimid) != NC_NOERR)
        if (nc_inq_dimid(ncid, "lon", &lon_dimid) != NC_NOERR)
            if (nc_inq_dimid(ncid, "x", &lon_dimid) != NC_NOERR)
                nc_inq_dimid(ncid, "nav_lon", &lon_dimid);

    if (nc_inq_dimid(ncid, "depth", &depth_dimid) != NC_NOERR)
        if (nc_inq_dimid(ncid, "z", &depth_dimid) != NC_NOERR)
            if (nc_inq_dimid(ncid, "deptht", &depth_dimid) != NC_NOERR)
                nc_inq_dimid(ncid, "depthu", &depth_dimid);

    for (int i = 0; i < ndims; i++) {
        if (dimids[i] == time_dimid) info.time_idx = i;
        else if (dimids[i] == lat_dimid) info.lat_idx = i;
        else if (dimids[i] == lon_dimid) info.lon_idx = i;
        else if (dimids[i] == depth_dimid) info.depth_idx = i;
    }

    free(dimids);

    if (info.time_idx == -1 || info.lat_idx == -1 || info.lon_idx == -1) {
        ncdfLog("[ncdf] discover_var_dims: FAILED for varid=%d (time=%d lat=%d lon=%d)\n",
            varid, info.time_idx, info.lat_idx, info.lon_idx);
        return info;
    }

    info.lat_before_lon = (info.lat_idx < info.lon_idx);
    info.valid = true;

    ncdfLog("[ncdf] discover_var_dims: varid=%d time=%d lat=%d lon=%d depth=%d lat_before_lon=%d\n",
        varid, info.time_idx, info.lat_idx, info.lon_idx, info.depth_idx, (int)info.lat_before_lon);

    return info;
}

/* CF-compliant time unit parser.
   Parses strings like "hours since 1950-01-01 00:00:00" or "days since 1950-01-01".
   Returns seconds_per_unit and the epoch datetime. */
struct CFTimeInfo {
    wxDateTime baseDateTime;
    double secondsPerUnit;
    bool valid;
    CFTimeInfo() : secondsPerUnit(0.0), valid(false) {}
};

static CFTimeInfo ParseCFTimeUnits(const char* unitsStr) {
    CFTimeInfo info;
    wxString units(unitsStr);
    
    int sincePos = units.Find(" since ");
    if (sincePos == wxNOT_FOUND) return info;
    
    wxString unitPart = units.Left(sincePos).Trim().Lower();
    wxString datePart = units.Mid(sincePos + 7).Trim();
    
    if (unitPart.Contains("second") || unitPart == "secs" || unitPart == "sec" || unitPart == "s")
        info.secondsPerUnit = 1.0;
    else if (unitPart.Contains("minute") || unitPart == "mins" || unitPart == "min")
        info.secondsPerUnit = 60.0;
    else if (unitPart.Contains("hour") || unitPart == "hrs" || unitPart == "hr" || unitPart == "h")
        info.secondsPerUnit = 3600.0;
    else if (unitPart.Contains("day") || unitPart == "d")
        info.secondsPerUnit = 86400.0;
    else
        return info;
    
    /* Strip trailing timezone (e.g. " UTC", " +00:00", "Z") and fractional seconds */
    wxString cleanDate;
    for (size_t j = 0; j < datePart.Len(); j++) {
        wxChar c = datePart[j];
        if (c == 'Z' || c == 'z') continue;  // skip Z
        if (c == '+' || c == '-') {
            /* Check if this is a timezone offset like "+00:00" or "-05:00" */
            if (j > 0 && datePart[j-1] == ' ') {
                break;  // timezone after space
            }
            if (j > 0 && datePart[j-1] == 'T') {
                /* This could be a negative timezone like T-05:00 */
                cleanDate += c;
                continue;
            }
        }
        cleanDate += c;
    }
    /* Remove trailing whitespace */
    cleanDate = cleanDate.Trim();
    
    if (info.baseDateTime.ParseFormat(cleanDate, "%Y-%m-%d %H:%M:%S") ||
        info.baseDateTime.ParseFormat(cleanDate, "%Y-%m-%dT%H:%M:%S") ||
        info.baseDateTime.ParseFormat(cleanDate, "%Y-%m-%d") ||
        info.baseDateTime.ParseFormat(cleanDate, "%Y-%m-%dT%H:%M:%SZ") ||
        info.baseDateTime.ParseFormat(cleanDate, "%Y-%m-%dT%H:%M:%S%z") ||
        info.baseDateTime.ParseFormat(cleanDate, "%Y-%m-%d %H:%M:%S %z")) {
        info.valid = true;
    }
    
    return info;
}

// Lightweight metadata reader for tree building — no data allocation, no myDataVector modification.
// Returns date labels and data type availability for each timestep.
MainDialog::FileMetadata MainDialog::nc_read_metadata(const wxString &fileName) {
	FileMetadata meta;
	const wxCharBuffer mbBuf = fileName.mb_str();
	const char* filename = mbBuf.data();

	int ncid;
	int retval = nc_open(filename, NC_NOWRITE, &ncid);
	if (retval != NC_NOERR)
		retval = nc_open(filename, NC_NOWRITE | NC_NETCDF4, &ncid);
	if (retval != NC_NOERR) return meta;

	// Discover time variable
	int time_varid;
	{
		const char* alt_std[] = {NULL};
		const char* long_hints[] = {"Time", "time coordinate", NULL};
		const char* var_hints[] = {"time", "t", "Time", NULL};
		time_varid = find_var_by_cf(ncid, "time", alt_std, long_hints, var_hints);
	}
	if (time_varid == -1) { nc_close(ncid); return meta; }

	int timeid = find_dim_by_var(ncid, time_varid, 0);
	if (timeid == -1) { nc_close(ncid); return meta; }

	size_t timelength = 0;
	if (nc_inq_dimlen(ncid, timeid, &timelength) != NC_NOERR || timelength == 0) {
		nc_close(ncid);
		return meta;
	}

	// Read time values
	double* time_out = (double*)calloc(timelength, sizeof(double));
	if (!time_out) { nc_close(ncid); return meta; }

	if (nc_get_var_double(ncid, time_varid, time_out) != NC_NOERR) {
		float* tf = (float*)calloc(timelength, sizeof(float));
		if (tf) {
			if (nc_get_var_float(ncid, time_varid, tf) == NC_NOERR)
				for (size_t i = 0; i < timelength; i++) time_out[i] = tf[i];
			free(tf);
		}
	}

	// Parse CF time units
	CFTimeInfo timeInfo;
	char* timeUnits = read_var_att_text(ncid, time_varid, "units");
	if (timeUnits) {
		timeInfo = ParseCFTimeUnits(timeUnits);
		delete[] timeUnits;
	}

	// Check data availability and cache variable IDs
	{
		const char* alt_std[] = {"surface_eastward_sea_water_velocity", NULL};
		const char* long_hints[] = {"Eastward Current Velocity", NULL};
		const char* var_hints[] = {"u", "uo", "current_u", NULL};
		meta.cached_u_varid = find_var_by_cf(ncid, "eastward_sea_water_velocity", alt_std, long_hints, var_hints);
		meta.hasCurrent = (meta.cached_u_varid != -1);
	}
	{
		const char* alt_std[] = {"surface_northward_sea_water_velocity", NULL};
		const char* long_hints[] = {"Northward Current Velocity", NULL};
		const char* var_hints[] = {"v", "vo", "current_v", NULL};
		meta.cached_v_varid = find_var_by_cf(ncid, "northward_sea_water_velocity", alt_std, long_hints, var_hints);
	}
	{
		const char* alt_std[] = {"sea_surface_temperature", NULL};
		const char* long_hints[] = {"Sea surface temperature", NULL};
		const char* var_hints[] = {"thetao", "sst", "temperature", NULL};
		meta.cached_sst_varid = find_var_by_cf(ncid, "sea_water_temperature", alt_std, long_hints, var_hints);
		meta.hasSeaTemp = (meta.cached_sst_varid != -1);
	}
	{
		const char* alt_std[] = {"sea_surface_salinity", NULL};
		const char* long_hints[] = {"Sea surface salinity", NULL};
		const char* var_hints[] = {"so", "salinity", "salt", NULL};
		meta.cached_sal_varid = find_var_by_cf(ncid, "sea_water_salinity", alt_std, long_hints, var_hints);
		meta.hasSalinity = (meta.cached_sal_varid != -1);
	}

	// Read lat/lon coordinates and dimension sizes
	{
		int lat_varid, lon_varid;
		{
			const char* alt_std[] = {"projection_y_coordinate", NULL};
			const char* long_hints[] = {"Latitude", NULL};
			const char* var_hints[] = {"lat", "latitude", NULL};
			lat_varid = find_var_by_cf(ncid, "latitude", alt_std, long_hints, var_hints);
		}
		{
			const char* alt_std[] = {"projection_x_coordinate", NULL};
			const char* long_hints[] = {"Longitude", NULL};
			const char* var_hints[] = {"lon", "longitude", NULL};
			lon_varid = find_var_by_cf(ncid, "longitude", alt_std, long_hints, var_hints);
		}

		if (lat_varid != -1 && lon_varid != -1) {
			int latid = find_dim_by_var(ncid, lat_varid, 0);
			int lonid = find_dim_by_var(ncid, lon_varid, 0);
			if (latid != -1) nc_inq_dimlen(ncid, latid, &meta.latlength);
			if (lonid != -1) nc_inq_dimlen(ncid, lonid, &meta.lonlength);

			if (meta.latlength > 0) {
				double* lats = (double*)calloc(meta.latlength, sizeof(double));
				if (lats) {
					if (nc_get_var_double(ncid, lat_varid, lats) != NC_NOERR) {
						float* lf = (float*)calloc(meta.latlength, sizeof(float));
						if (lf) { nc_get_var_float(ncid, lat_varid, lf); for (size_t i = 0; i < meta.latlength; i++) lats[i] = lf[i]; free(lf); }
					}
					meta.firstGridPointLat = lats[0];
					meta.lastGridPointLat = lats[meta.latlength - 1];
					// Store in SharedCoords for later use
					meta.sharedCoords = std::make_shared<SharedCoords>();
					meta.sharedCoords->latValues = lats;
					meta.sharedCoords->latLength = meta.latlength;
				}
			}
			if (meta.lonlength > 0) {
				double* lons = (double*)calloc(meta.lonlength, sizeof(double));
				if (lons) {
					if (nc_get_var_double(ncid, lon_varid, lons) != NC_NOERR) {
						float* lf = (float*)calloc(meta.lonlength, sizeof(float));
						if (lf) { nc_get_var_float(ncid, lon_varid, lf); for (size_t i = 0; i < meta.lonlength; i++) lons[i] = lf[i]; free(lf); }
					}
					meta.firstGridPointLong = lons[0];
					meta.lastGridPointLong = lons[meta.lonlength - 1];
					if (meta.sharedCoords) {
						meta.sharedCoords->lonValues = lons;
						meta.sharedCoords->lonLength = meta.lonlength;
					}
				}
			}
			meta.iDirectionIncr = (meta.lonlength > 1) ?
				(meta.lastGridPointLong - meta.firstGridPointLong) / (meta.lonlength - 1) : 0;
			meta.jDirectionIncr = (meta.latlength > 1) ?
				(meta.lastGridPointLat - meta.firstGridPointLat) / (meta.latlength - 1) : 0;
		}
	}

	// Store time values for later use
	meta.timeValues.resize(timelength);
	for (size_t i = 0; i < timelength; i++) meta.timeValues[i] = time_out[i];

	// Build date list
	meta.timelength = timelength;
	meta.dates.resize(timelength);
	meta.timeValid.resize(timelength);
	for (size_t i = 0; i < timelength; i++) {
		if (timeInfo.valid) {
			wxTimeSpan span = wxTimeSpan::Seconds((long long)(time_out[i] * timeInfo.secondsPerUnit));
			meta.dates[i] = timeInfo.baseDateTime;
			meta.dates[i].Add(span);
			meta.timeValid[i] = true;
		} else {
			// Fallback: try to guess time format (same logic as nc_get)
			bool guessed = false;
			if (time_out[i] >= 1e9 && time_out[i] <= 2e9) {
				// Looks like Unix timestamp
				CFTimeInfo unixInfo = ParseCFTimeUnits("seconds since 1970-01-01");
				if (unixInfo.valid) {
					wxTimeSpan span = wxTimeSpan::Seconds((long long)(time_out[i] * unixInfo.secondsPerUnit));
					meta.dates[i] = unixInfo.baseDateTime;
					meta.dates[i].Add(span);
					guessed = true;
				}
			}
			if (!guessed && time_out[i] >= 0 && time_out[i] <= 700000) {
				// Looks like CMEMS hours since 1950-01-01
				CFTimeInfo cmemsInfo = ParseCFTimeUnits("hours since 1950-01-01");
				if (cmemsInfo.valid) {
					wxTimeSpan span = wxTimeSpan::Seconds((long long)(time_out[i] * cmemsInfo.secondsPerUnit));
					meta.dates[i] = cmemsInfo.baseDateTime;
					meta.dates[i].Add(span);
					guessed = true;
				}
			}
			meta.timeValid[i] = guessed;
			if (!guessed) meta.dates[i] = wxDateTime();
		}
	}

	meta.valid = true;
	free(time_out);
	nc_close(ncid);
	return meta;
}

int MainDialog::nc_get(wxString filestr){

	FILE *dbg = fopen("C:\\ProgramData\\opencpn\\ncdf_crash_trace.log", "a");
	if (dbg) { fprintf(dbg, "nc_get: ENTER\n"); fflush(dbg); fclose(dbg); }

	ncdfLog("[ncdf] nc_get: started\n");

	ncdfLog("[ncdf] nc_get: clearing myDataVector...\n");
	myDataVector.clear();
	ncdfLog("[ncdf] nc_get: myDataVector cleared\n");

	m_lastSelectedTimeIndex = -1;

	// Reset cached variable IDs (previous file may have had different variables)
	m_cached_u_varid = -1;
	m_cached_v_varid = -1;
	m_cached_sst_varid = -1;
	m_cached_sal_varid = -1;
	m_fileHasCurrent = false;
	m_fileHasSeaTemp = false;
	m_fileHasSalinity = false;

	ncdfLog("[ncdf] nc_get: declaring variables...\n");
	int ncid;
	int time_varid, lat_varid, lon_varid;
	int u_varid, v_varid;
	int retval;

	int ndims_in, nvars_in, ngatts_in, unlimdimid_in;

	ncdfLog("[ncdf] nc_get: processing filename...\n");
	wxString filenameStr = filestr;
	ncdfLog("[ncdf] nc_get: filenameStr wxChar length=%d\n", (int)filenameStr.length());
	
	const wxCharBuffer mbBuf = filenameStr.mb_str();
	size_t mbLen = strlen(mbBuf);
	char* filename = new char[mbLen + 1];
	ncdfLog("[ncdf] nc_get: filename allocated, mbLen=%d\n", (int)mbLen);
	
	strcpy(filename, mbBuf);
	ncdfLog("[ncdf] nc_get: filename copied: %s\n", filename);

	/* Try opening without NC_NETCDF4 first (compatible with NetCDF3 classic format).
	   If that fails, retry with NC_NETCDF4 for HDF5-based NetCDF4 files. */
	retval = nc_open(filename, NC_NOWRITE, &ncid);
	if (retval != NC_NOERR) {
		retval = nc_open(filename, NC_NOWRITE | NC_NETCDF4, &ncid);
	}
	if (retval != NC_NOERR) {
		ncdfLog("[ncdf] nc_get: nc_open failed, retval=%d\n", retval);
		delete[] filename;
		return retval;
	}

	if ((retval = nc_inq(ncid, &ndims_in, &nvars_in, &ngatts_in, &unlimdimid_in))) {
		nc_close(ncid);
		delete[] filename;
		return retval;
	}

	if (ndims_in < 3 || ndims_in > 4) {
		ncdfLog("[ncdf] nc_get: unsupported ndims=%d (need 3-4)\n", ndims_in);
		nc_close(ncid);
		delete[] filename;
		return 2;
	}

	ncdfLog("[ncdf] nc_get: searching for variables using CF conventions...\n");

	/* u: eastward_sea_water_velocity */
	{
		const char* alt_std[] = {"surface_eastward_sea_water_velocity", NULL};
		const char* long_hints[] = {"Eastward Current Velocity", "u-velocity component of current", NULL};
		const char* var_hints[] = {"u", "uo", "current_u", "curr_u", "u10", "u100", NULL};
		u_varid = find_var_by_cf(ncid, "eastward_sea_water_velocity", alt_std, long_hints, var_hints);
	}
	
	/* v: northward_sea_water_velocity */
	{
		const char* alt_std[] = {"surface_northward_sea_water_velocity", NULL};
		const char* long_hints[] = {"Northward Current Velocity", "v-velocity component of current", NULL};
		const char* var_hints[] = {"v", "vo", "current_v", "curr_v", "v10", "v100", NULL};
		v_varid = find_var_by_cf(ncid, "northward_sea_water_velocity", alt_std, long_hints, var_hints);
	}
	
	/* lat: latitude */
	{
		const char* alt_std[] = {"projection_y_coordinate", NULL};
		const char* long_hints[] = {"Latitude", "latitude coordinate", NULL};
		const char* var_hints[] = {"lat", "latitude", "nav_lat", NULL};
		lat_varid = find_var_by_cf(ncid, "latitude", alt_std, long_hints, var_hints);
	}
	
	/* lon: longitude */
	{
		const char* alt_std[] = {"projection_x_coordinate", NULL};
		const char* long_hints[] = {"Longitude", "longitude coordinate", NULL};
		const char* var_hints[] = {"lon", "longitude", "nav_lon", NULL};
		lon_varid = find_var_by_cf(ncid, "longitude", alt_std, long_hints, var_hints);
	}
	
	/* time */
	{
		const char* alt_std[] = {NULL};
		const char* long_hints[] = {"Time", "time coordinate", NULL};
		const char* var_hints[] = {"time", "t", "Time", NULL};
		time_varid = find_var_by_cf(ncid, "time", alt_std, long_hints, var_hints);
	}

	/* sea surface temperature (optional, just discover the variable) */
	int sst_varid = -1;
	{
		const char* alt_std[] = {"sea_surface_temperature", "surface_temperature", NULL};
		const char* long_hints[] = {"Sea surface temperature", "sea_water_temperature", "SST", "Temperature", "temperature", NULL};
		const char* var_hints[] = {"thetao", "sst", "temperature", "temp", "SST", "votemper", "to", NULL};
		sst_varid = find_var_by_cf(ncid, "sea_water_temperature", alt_std, long_hints, var_hints);
	}
	ncdfLog("[ncdf] nc_get: sst_varid=%d\n", sst_varid);

	/* sea surface salinity (optional) */
	int sal_varid = -1;
	{
		const char* alt_std[] = {"sea_surface_salinity", "surface_salinity", NULL};
		const char* long_hints[] = {"Sea surface salinity", "sea_water_salinity", "Salinity", "salinity", NULL};
		const char* var_hints[] = {"so", "salinity", "salt", "vosaline", "sos", "SSS", NULL};
		sal_varid = find_var_by_cf(ncid, "sea_water_salinity", alt_std, long_hints, var_hints);
	}
	ncdfLog("[ncdf] nc_get: sal_varid=%d\n", sal_varid);

	/* depth - commented out */
	/*int depth_varid = -1;
	{
		const char* alt_std[] = {"depth", "z", "depth_below_sea_level", NULL};
		const char* long_hints[] = {"Depth", "depth coordinate", "vertical level", NULL};
		const char* var_hints[] = {"depth", "z", "Depth", "level", NULL};
		depth_varid = find_var_by_cf(ncid, "depth", alt_std, long_hints, var_hints);
	}*/

	ncdfLog("[ncdf] nc_get: result - u_varid=%d, v_varid=%d, lat_varid=%d, lon_varid=%d, time_varid=%d, sst_varid=%d\n",
		u_varid, v_varid, lat_varid, lon_varid, time_varid, sst_varid);

	bool hasCurrent = (u_varid != -1 && v_varid != -1);
	bool hasSST = (sst_varid != -1);
	bool hasSalinity = (sal_varid != -1);

	// Store file-level data availability and cached variable IDs
	m_fileHasCurrent = hasCurrent;
	m_fileHasSeaTemp = hasSST;
	m_fileHasSalinity = hasSalinity;
	m_cached_u_varid = u_varid;
	m_cached_v_varid = v_varid;
	m_cached_sst_varid = sst_varid;
	m_cached_sal_varid = sal_varid;
	ncdfLog("[ncdf] nc_get: m_fileHasCurrent=%d, m_fileHasSeaTemp=%d, cached varids: u=%d v=%d sst=%d\n",
		(int)m_fileHasCurrent, (int)m_fileHasSeaTemp, m_cached_u_varid, m_cached_v_varid, m_cached_sst_varid);

	if (!hasCurrent && !hasSST) {
		ncdfLog("[ncdf] nc_get: no u/v and no SST, but loading file anyway for coordinate display\n");
		// Don't return error - allow the file to load for coordinate/time display
	}

	if (lat_varid == -1) {
		ncdfLog("[ncdf] nc_get: lat variable not found\n");
		nc_close(ncid);
		delete[] filename;
		return 2;
	}

	if (lon_varid == -1) {
		ncdfLog("[ncdf] nc_get: lon variable not found\n");
		nc_close(ncid);
		delete[] filename;
		return 2;
	}

	if (time_varid == -1) {
		ncdfLog("[ncdf] nc_get: time variable not found\n");
		nc_close(ncid);
		delete[] filename;
		return 2;
	}

	int timeid = find_dim_by_var(ncid, time_varid, 0);
	int latid = find_dim_by_var(ncid, lat_varid, 0);
	int lonid = find_dim_by_var(ncid, lon_varid, 0);
	/* depth - commented out */
	/*int depthid = -1;
	if (depth_varid != -1) {
		depthid = find_dim_by_var(ncid, depth_varid, 0);
	}*/

	if (timeid == -1 || latid == -1 || lonid == -1) {
		ncdfLog("[ncdf] nc_get: invalid dimension id (timeid=%d, latid=%d, lonid=%d)\n", timeid, latid, lonid);
		nc_close(ncid);
		delete[] filename;
		return 2;
	}

	size_t timelength = 0, latlength = 0, lonlength = 0/*, depthlength = 0*/;
	int status;

	if ((status = nc_inq_dimlen(ncid, timeid, &timelength)) != NC_NOERR) {
		ncdfLog("[ncdf] nc_get: failed to get time dimension length\n");
		nc_close(ncid);
		delete[] filename;
		return 2;
	}
	if ((status = nc_inq_dimlen(ncid, latid, &latlength)) != NC_NOERR) {
		ncdfLog("[ncdf] nc_get: failed to get lat dimension length\n");
		nc_close(ncid);
		delete[] filename;
		return 2;
	}
	if ((status = nc_inq_dimlen(ncid, lonid, &lonlength)) != NC_NOERR) {
		ncdfLog("[ncdf] nc_get: failed to get lon dimension length\n");
		nc_close(ncid);
		delete[] filename;
		return 2;
	}

	ncdfLog("[ncdf] nc_get: timelength=%d, latlength=%d, lonlength=%d\n", 
		(int)timelength, (int)latlength, (int)lonlength);

	wxDouble* lats = (wxDouble*)calloc(latlength, sizeof(wxDouble));
	wxDouble* lons = (wxDouble*)calloc(lonlength, sizeof(wxDouble));
	double* time_out = (double*)calloc(timelength, sizeof(double));

	if (!lats || !lons || !time_out) {
		if (lats) free(lats);
		if (lons) free(lons);
		if (time_out) free(time_out);
		nc_close(ncid);
		delete[] filename;
		return 1;
	}

	if (nc_get_var_double(ncid, lat_varid, (double*)lats) != NC_NOERR) {
		float* lat_float = (float*)calloc(latlength, sizeof(float));
		if (!lat_float) { free(lats); free(lons); free(time_out); nc_close(ncid); delete[] filename; return 1; }
		if (nc_get_var_float(ncid, lat_varid, lat_float) == NC_NOERR) {
			for (size_t i = 0; i < latlength; i++) {
				lats[i] = lat_float[i];
			}
		}
		free(lat_float);
	}
	
	if (nc_get_var_double(ncid, lon_varid, (double*)lons) != NC_NOERR) {
		float* lon_float = (float*)calloc(lonlength, sizeof(float));
		if (!lon_float) { free(lons); free(lats); free(time_out); nc_close(ncid); delete[] filename; return 1; }
		if (nc_get_var_float(ncid, lon_varid, lon_float) == NC_NOERR) {
			for (size_t i = 0; i < lonlength; i++) {
				lons[i] = lon_float[i];
			}
		}
		free(lon_float);
	}
	
	if (nc_get_var_double(ncid, time_varid, time_out) != NC_NOERR) {
		float* time_float = (float*)calloc(timelength, sizeof(float));
		if (!time_float) { free(time_out); free(lats); free(lons); nc_close(ncid); delete[] filename; return 1; }
		if (nc_get_var_float(ncid, time_varid, time_float) == NC_NOERR) {
			for (size_t i = 0; i < timelength; i++) {
				time_out[i] = time_float[i];
			}
		}
		free(time_float);
	}
	
	ncdfLog("[ncdf] nc_get: first time value = %f\n", timelength > 0 ? time_out[0] : 0.0);
	
	/* depth - commented out */
	/*wxDouble* depths = NULL;
	if (depth_varid != -1 && depthid != -1) {
		if ((status = nc_inq_dimlen(ncid, depthid, &depthlength)) != NC_NOERR) {
			ncdfLog("[ncdf] nc_get: failed to get depth dimension length, assuming surface data\n");
			depthlength = 0;
		} else {
			if (depthlength > 0) {
				depths = (wxDouble*)calloc(depthlength, sizeof(wxDouble));
				if (depths) {
					if (nc_get_var_double(ncid, depth_varid, (double*)depths) != NC_NOERR) {
						float* depth_float = (float*)calloc(depthlength, sizeof(float));
						if (depth_float) {
							if (nc_get_var_float(ncid, depth_varid, depth_float) == NC_NOERR) {
								for (size_t i = 0; i < depthlength; i++) {
									depths[i] = depth_float[i];
								}
							}
							free(depth_float);
						}
					}
					ncdfLog("[ncdf] nc_get: depth length=%d, first depth value=%f\n", 
						(int)depthlength, depths[0]);
				}
			} else {
				ncdfLog("[ncdf] nc_get: depth dimension length is 0, assuming surface data\n");
				depthlength = 0;
			}
		}
	} else {
		depthlength = 0;
	}*/

	float firstGridPointLat;
	float firstGridPointLon;
	float lastGridPointLat;
	float lastGridPointLon;
	float scale_factor = 1.0f;

	// Always use actual coordinate arrays for bounds (GRIB pattern)
	// Global attributes (latitude_min etc.) may not match the data grid exactly
	firstGridPointLat = lats[0];
	firstGridPointLon = lons[0];
	lastGridPointLat = lats[latlength - 1];
	lastGridPointLon = lons[lonlength - 1];
	
	if (nc_get_att_float(ncid, u_varid, "scale_factor", &scale_factor) != NC_NOERR) {
		scale_factor = 1.0f;
	}
	
	/* Read CF time units and parse epoch + unit */
	CFTimeInfo timeInfo;
	{
		char* timeUnits = read_var_att_text(ncid, time_varid, "units");
		if (!timeUnits) {
			timeUnits = read_var_att_text(ncid, NC_GLOBAL, "units");
			if (timeUnits) ncdfLog("[ncdf] nc_get: found time units from NC_GLOBAL: '%s'\n", timeUnits);
		}
		
		if (!timeUnits && timelength > 0) {
			double firstTimeValue = time_out[0];
			double timeStep = timelength > 1 ? time_out[1] - time_out[0] : 1.0;
			
			bool canDetermine = false;
			const int MAX_YEAR = 2050;
			
			if (firstTimeValue >= 0 && firstTimeValue <= 2000000000.0) {
				if (timeStep >= 3600.0 || timeStep >= 86400.0) {
					CFTimeInfo unixInfo = ParseCFTimeUnits("seconds since 1970-01-01");
					if (unixInfo.valid) {
						wxDateTime testDate = unixInfo.baseDateTime;
						testDate.Add(wxTimeSpan::Seconds((long long)(firstTimeValue * unixInfo.secondsPerUnit)));
						if (testDate.GetYear() <= MAX_YEAR) {
							ncdfLog("[ncdf] nc_get: WARNING - no units, guessed Unix timestamp, first date=%s (valid, <=%d)\n", 
								(const char*)testDate.Format("%Y-%m-%d").mb_str(), MAX_YEAR);
							timeInfo = unixInfo;
							canDetermine = true;
						} else {
							ncdfLog("[ncdf] nc_get: WARNING - no units, guessed Unix timestamp but first date=%s (>%d), rejecting\n", 
								(const char*)testDate.Format("%Y-%m-%d").mb_str(), MAX_YEAR);
						}
					}
				}
			}
			
			if (!canDetermine && firstTimeValue >= 0 && firstTimeValue <= 700000.0) {
				if (timeStep >= 1.0 && timeStep <= 24.0) {
					CFTimeInfo cmemsInfo = ParseCFTimeUnits("hours since 1950-01-01");
					if (cmemsInfo.valid) {
						wxDateTime testDate = cmemsInfo.baseDateTime;
						testDate.Add(wxTimeSpan::Seconds((long long)(firstTimeValue * cmemsInfo.secondsPerUnit)));
						if (testDate.GetYear() <= MAX_YEAR) {
							ncdfLog("[ncdf] nc_get: WARNING - no units, guessed CMEMS hours, first date=%s (valid, <=%d)\n", 
								(const char*)testDate.Format("%Y-%m-%d").mb_str(), MAX_YEAR);
							timeInfo = cmemsInfo;
							canDetermine = true;
						} else {
							ncdfLog("[ncdf] nc_get: WARNING - no units, guessed CMEMS hours but first date=%s (>%d), rejecting\n", 
								(const char*)testDate.Format("%Y-%m-%d").mb_str(), MAX_YEAR);
						}
					}
				}
			}
			
			if (!canDetermine) {
				ncdfLog("[ncdf] nc_get: WARNING - no units, time value=%.0f, step=%.0f, cannot reliably determine time unit, using sequential labels\n", firstTimeValue, timeStep);
				timeInfo.valid = false;
			}
		} else if (!timeUnits) {
			ncdfLog("[ncdf] nc_get: WARNING - no units and no time data, using sequential labels\n");
			timeInfo.valid = false;
		} else {
			ncdfLog("[ncdf] nc_get: time units = '%s'\n", timeUnits);
			timeInfo = ParseCFTimeUnits(timeUnits);
			delete[] timeUnits;
		}
		if (timeInfo.valid) {
			wxString fmt = timeInfo.baseDateTime.Format("%Y-%m-%d %H:%M:%S");
			ncdfLog("[ncdf] nc_get: time epoch = %s, secondsPerUnit=%f\n",
				(const char*)fmt.mb_str(), timeInfo.secondsPerUnit);
		} else {
			ncdfLog("[ncdf] nc_get: WARNING - failed to parse time units, using fallback\n");
		}
	}
	
	//
	wxDouble iDirectionIncr = (lastGridPointLon - firstGridPointLon) / (lonlength > 1 ? lonlength - 1 : 1);
	wxDouble jDirectionIncr = (lastGridPointLat - firstGridPointLat) / (latlength > 1 ? latlength - 1 : 1);

	// Item 1: Allocate shared coordinate arrays once (all time steps share the same data)
	std::shared_ptr<SharedCoords> sharedCoords = std::make_shared<SharedCoords>();
	sharedCoords->latValues = (wxDouble*)calloc(latlength, sizeof(wxDouble));
	sharedCoords->lonValues = (wxDouble*)calloc(lonlength, sizeof(wxDouble));
	sharedCoords->timeValues = (double*)calloc(timelength, sizeof(double));
	sharedCoords->latLength = latlength;

	// Pre-allocate file-level data buffers (reused across time steps, avoids 32-bit heap fragmentation)
	size_t nbr_uv = latlength * lonlength;
	m_fileUBuffer.reserve(nbr_uv);
	m_fileVBuffer.reserve(nbr_uv);
	m_fileSSTBuffer.reserve(nbr_uv);
	m_fileSalBuffer.reserve(nbr_uv);
	m_fileBufferReady = true;
	ncdfLog("[ncdf] nc_get: file buffers reserved, nbr_uv=%zu\n", nbr_uv);
	sharedCoords->lonLength = lonlength;
	sharedCoords->timeLength = timelength;
	memcpy(sharedCoords->latValues, lats, latlength * sizeof(wxDouble));
	memcpy(sharedCoords->lonValues, lons, lonlength * sizeof(wxDouble));
	memcpy(sharedCoords->timeValues, time_out, timelength * sizeof(double));

	// Create message for each timestep (metadata only, shared coords)
	for (size_t i = 0; i < timelength; i++) {

		myncdfData.clear();
		myncdfData.timeValid = timeInfo.valid;

		if (timeInfo.valid) {
			wxTimeSpan span = wxTimeSpan::Seconds((long long)(time_out[i] * timeInfo.secondsPerUnit));
			myncdfData.dataDateTime = timeInfo.baseDateTime;
			myncdfData.dataDateTime.Add(span);
			myncdfData.minutesAfterStart = (int)(time_out[i] * timeInfo.secondsPerUnit / 60.0);

			wxString dateStr = myncdfData.dataDateTime.Format("%Y-%m-%d %H:%M:%S");
			ncdfLog("[ncdf] nc_get: timestep=%d, raw_time=%f, calculated_date=%s\n",
				(int)i, time_out[i], (const char*)dateStr.mb_str());
		} else {
			myncdfData.dataDateTime = wxDateTime();
			myncdfData.minutesAfterStart = (int)(i * 60);
			ncdfLog("[ncdf] nc_get: timestep=%d, raw_time=%f, timeValid=false, using sequential label, minutesAfterStart=%d\n",
				(int)i, time_out[i], myncdfData.minutesAfterStart);
		}
		myncdfData.numberOfPoints = (int)(latlength * lonlength);
		myncdfData.noPointsParallel = (wxUint32)lonlength;
		myncdfData.noPointsMeridian = (wxUint32)latlength;
		myncdfData.firstGridPointLat = firstGridPointLat;
		myncdfData.firstGridPointLong = firstGridPointLon;
		myncdfData.lastGridPointLat = lastGridPointLat;
		myncdfData.lastGridPointLong = lastGridPointLon;
		if (i == 0) {
			ncdfLog("[ncdf] nc_get: bounds from file: lat[%.2f,%.2f] lon[%.2f,%.2f] file=%s\n",
				firstGridPointLat, lastGridPointLat, firstGridPointLon, lastGridPointLon, filename);
		}
		myncdfData.iDirectionIncr = iDirectionIncr;
		myncdfData.jDirectionIncr = jDirectionIncr;
		myncdfData.fileName = filename;
		myncdfData.timeIndex = (int)i;
		myncdfData.timeLength = timelength;
		myncdfData.latLength = latlength;
		myncdfData.lonLength = lonlength;
		myncdfData.hasSeaTemp = hasSST;
		myncdfData.hasSalinity = hasSalinity;
		/*myncdfData.depthLength = depthlength;*/

		// Share coordinate arrays across all time steps (one allocation)
		myncdfData.sharedCoords = sharedCoords;
		myncdfData.latValues = sharedCoords->latValues;
		myncdfData.lonValues = sharedCoords->lonValues;
		myncdfData.timeValues = sharedCoords->timeValues;

		myDataVector.push_back(myncdfData);
	}
	
	nc_close(ncid);
	
	free(time_out);
	free(lats);
	free(lons);
	/*if (depths) {
		free(depths);
	}*/
	
	delete[] filename;


	return 0;
}

static bool readUVFromNC(int ncid, int u_varid, int v_varid, ncdfDataMessage& dataMessage) {
	ncdfLog("[ncdf] readUVFromNC: u_varid=%d, v_varid=%d\n", u_varid, v_varid);

	float fill_value_u = -32767.0f;
	float fill_value_v = -32767.0f;

	if (nc_get_att_float(ncid, u_varid, "_FillValue", &fill_value_u) != NC_NOERR) {
		double fill_val_double;
		if (nc_get_att_double(ncid, u_varid, "_FillValue", &fill_val_double) == NC_NOERR) {
			fill_value_u = (float)fill_val_double;
		} else {
			fill_value_u = -32767.0f;
		}
	}

	if (nc_get_att_float(ncid, v_varid, "_FillValue", &fill_value_v) != NC_NOERR) {
		double fill_val_double;
		if (nc_get_att_double(ncid, v_varid, "_FillValue", &fill_val_double) == NC_NOERR) {
			fill_value_v = (float)fill_val_double;
		} else {
			fill_value_v = -32767.0f;
		}
	}

	VarDimInfo dims = discover_var_dims(ncid, u_varid);
	if (!dims.valid) return false;

	int ndims;
	nc_inq_varndims(ncid, u_varid, &ndims);

	size_t start[4] = {0, 0, 0, 0};
	size_t count[4] = {1, 1, 1, 1};

	start[dims.time_idx] = dataMessage.timeIndex;
	count[dims.time_idx] = 1;
	start[dims.lat_idx] = 0;
	count[dims.lat_idx] = dataMessage.latLength;
	start[dims.lon_idx] = 0;
	count[dims.lon_idx] = dataMessage.lonLength;
	if (dims.depth_idx != -1) {
		start[dims.depth_idx] = 0;
		count[dims.depth_idx] = 1;
	}

	size_t nbr_uv = dataMessage.latLength * dataMessage.lonLength;

	float* u_vals = (float*)calloc(nbr_uv, sizeof(float));
	if (!u_vals) return false;

	float* v_vals = (float*)calloc(nbr_uv, sizeof(float));
	if (!v_vals) { free(u_vals); return false; }

	nc_type u_type, v_type;
	nc_inq_vartype(ncid, u_varid, &u_type);
	nc_inq_vartype(ncid, v_varid, &v_type);

	ncdfLog("[ncdf] readUVFromNC: reading data, u_type=%d, v_type=%d, nbr_uv=%zu\n",
		(int)u_type, (int)v_type, nbr_uv);

	int retval;
	if (u_type == NC_DOUBLE) {
		double* u_vals_double = (double*)calloc(nbr_uv, sizeof(double));
		if (!u_vals_double) { free(u_vals); free(v_vals); return false; }
		if ((retval = nc_get_vara_double(ncid, u_varid, start, count, u_vals_double))) {
			free(u_vals_double); free(u_vals); free(v_vals); return false;
		}
		for (size_t i = 0; i < nbr_uv; i++) {
			u_vals[i] = (float)u_vals_double[i];
		}
		free(u_vals_double);
	} else {
		if ((retval = nc_get_vara_float(ncid, u_varid, start, count, u_vals))) {
			free(u_vals); free(v_vals); return false;
		}
	}

	if (v_type == NC_DOUBLE) {
		double* v_vals_double = (double*)calloc(nbr_uv, sizeof(double));
		if (!v_vals_double) { free(u_vals); free(v_vals); return false; }
		if ((retval = nc_get_vara_double(ncid, v_varid, start, count, v_vals_double))) {
			free(v_vals_double); free(u_vals); free(v_vals); return false;
		}
		for (size_t i = 0; i < nbr_uv; i++) {
			v_vals[i] = (float)v_vals_double[i];
		}
		free(v_vals_double);
	} else {
		if ((retval = nc_get_vara_float(ncid, v_varid, start, count, v_vals))) {
			free(u_vals); free(v_vals); return false;
		}
	}

	ncdfLog("[ncdf] readUVFromNC: data read successfully, allocating output arrays\n");

	dataMessage.ucurr.resize(nbr_uv, ncdf_NOTDEF);
	dataMessage.vcurr.resize(nbr_uv, ncdf_NOTDEF);

	size_t count_records = 0;
	if (dims.lat_before_lon) {
		for (size_t j = 0; j < dataMessage.latLength; j++) {
			for (size_t k = 0; k < dataMessage.lonLength; k++) {
				if (u_vals[count_records] != fill_value_u && v_vals[count_records] != fill_value_v) {
					dataMessage.ucurr[count_records] = (double)u_vals[count_records];
					dataMessage.vcurr[count_records] = (double)v_vals[count_records];
				}
				count_records++;
			}
		}
	} else {
		for (size_t k = 0; k < dataMessage.lonLength; k++) {
			for (size_t j = 0; j < dataMessage.latLength; j++) {
				if (u_vals[count_records] != fill_value_u && v_vals[count_records] != fill_value_v) {
					dataMessage.ucurr[count_records] = (double)u_vals[count_records];
					dataMessage.vcurr[count_records] = (double)v_vals[count_records];
				}
				count_records++;
			}
		}
	}

	free(u_vals);
	free(v_vals);
	return true;
}

static bool readSSTFromNC(int ncid, int sst_varid, ncdfDataMessage& dataMessage) {
	ncdfLog("[ncdf] readSSTFromNC: sst_varid=%d\n", sst_varid);

	if (sst_varid < 0) {
		// Fallback: discover SST variable if cache miss
		const char* alt_std[] = {"sea_surface_temperature", "surface_temperature", NULL};
		const char* long_hints[] = {"Sea surface temperature", "sea_water_temperature", "SST", "Temperature", "temperature", NULL};
		const char* var_hints[] = {"thetao", "sst", "temperature", "temp", "SST", "votemper", "to", NULL};
		sst_varid = find_var_by_cf(ncid, "sea_water_temperature", alt_std, long_hints, var_hints);
	}
	if (sst_varid == -1) return false;

	VarDimInfo dims = discover_var_dims(ncid, sst_varid);
	if (!dims.valid) return false;

	int ndims;
	nc_inq_varndims(ncid, sst_varid, &ndims);

	size_t start[NC_MAX_DIMS] = {0};
	size_t count[NC_MAX_DIMS] = {0};

	start[dims.time_idx] = dataMessage.timeIndex;
	count[dims.time_idx] = 1;
	start[dims.lat_idx] = 0;
	count[dims.lat_idx] = dataMessage.latLength;
	start[dims.lon_idx] = 0;
	count[dims.lon_idx] = dataMessage.lonLength;
	if (dims.depth_idx != -1) {
		start[dims.depth_idx] = 0;
		count[dims.depth_idx] = 1;
	}

	size_t nbr_uv = dataMessage.latLength * dataMessage.lonLength;

	nc_type var_type;
	nc_inq_vartype(ncid, sst_varid, &var_type);

	float* sst_vals = (float*)calloc(nbr_uv, sizeof(float));
	if (!sst_vals) return false;

	if (var_type == NC_DOUBLE) {
		double* sst_double = (double*)calloc(nbr_uv, sizeof(double));
		if (!sst_double) { free(sst_vals); return false; }
		if (nc_get_vara_double(ncid, sst_varid, start, count, sst_double) != NC_NOERR) {
			free(sst_double); free(sst_vals); return false;
		}
		for (size_t i = 0; i < nbr_uv; i++) sst_vals[i] = (float)sst_double[i];
		free(sst_double);
	} else {
		if (nc_get_vara_float(ncid, sst_varid, start, count, sst_vals) != NC_NOERR) {
			free(sst_vals); return false;
		}
	}

	bool isKelvin = false;
	char units_str[64] = {0};
	if (nc_get_att_text(ncid, sst_varid, "units", units_str) == NC_NOERR) {
		if (strstr(units_str, "K") || strstr(units_str, "kelvin")) isKelvin = true;
	}

	float sst_fill = -32767.0f;
	nc_get_att_float(ncid, sst_varid, "_FillValue", &sst_fill);

	dataMessage.sst.resize(nbr_uv, ncdf_NOTDEF);

	// Rearrange data to [lat, lon] order regardless of file dimension order
	size_t latLen = dataMessage.latLength;
	size_t lonLen = dataMessage.lonLength;
	size_t count_records = 0;
	double minValid = isKelvin ? 100.0 : -10.0;
	double maxValid = isKelvin ? 370.0 : 50.0;

	if (dims.lat_before_lon) {
		for (size_t j = 0; j < latLen; j++) {
			for (size_t k = 0; k < lonLen; k++) {
				double val = (double)sst_vals[count_records];
				if (!isnan(val) && isfinite(val) && val != sst_fill && val > minValid && val < maxValid)
					dataMessage.sst[count_records] = isKelvin ? (val - 273.15) : val;
				else
					dataMessage.sst[count_records] = ncdf_NOTDEF;
				count_records++;
			}
		}
	} else {
		// File order is [lon, lat] — reorder to [lat, lon]
		float* reordered = (float*)calloc(nbr_uv, sizeof(float));
		if (reordered) {
			for (size_t k = 0; k < lonLen; k++)
				for (size_t j = 0; j < latLen; j++)
					reordered[j * lonLen + k] = sst_vals[k * latLen + j];
			for (size_t i = 0; i < nbr_uv; i++) {
				double val = (double)reordered[i];
				if (!isnan(val) && isfinite(val) && val != sst_fill && val > minValid && val < maxValid)
					dataMessage.sst[i] = isKelvin ? (val - 273.15) : val;
				else
					dataMessage.sst[i] = ncdf_NOTDEF;
			}
			free(reordered);
		}
	}

	free(sst_vals);
	ncdfLog("[ncdf] readSSTFromNC: SST read, isKelvin=%d, lat_before_lon=%d\n",
		(int)isKelvin, (int)dims.lat_before_lon);
	dataMessage.hasSeaTemp = true;
	return true;
}

static bool readSalinityFromNC(int ncid, int sal_varid, ncdfDataMessage& dataMessage) {
	ncdfLog("[ncdf] readSalinityFromNC: sal_varid=%d\n", sal_varid);

	if (sal_varid < 0) {
		const char* alt_std[] = {"sea_surface_salinity", "surface_salinity", NULL};
		const char* long_hints[] = {"Sea surface salinity", "sea_water_salinity", "Salinity", "salinity", NULL};
		const char* var_hints[] = {"so", "salinity", "salt", "vosaline", "sos", "SSS", NULL};
		sal_varid = find_var_by_cf(ncid, "sea_water_salinity", alt_std, long_hints, var_hints);
	}
	if (sal_varid == -1) return false;

	VarDimInfo dims = discover_var_dims(ncid, sal_varid);
	if (!dims.valid) return false;

	int ndims;
	nc_inq_varndims(ncid, sal_varid, &ndims);

	size_t start[NC_MAX_DIMS] = {0};
	size_t count[NC_MAX_DIMS] = {0};

	start[dims.time_idx] = dataMessage.timeIndex;
	count[dims.time_idx] = 1;
	start[dims.lat_idx] = 0;
	count[dims.lat_idx] = dataMessage.latLength;
	start[dims.lon_idx] = 0;
	count[dims.lon_idx] = dataMessage.lonLength;
	if (dims.depth_idx != -1) {
		start[dims.depth_idx] = 0;
		count[dims.depth_idx] = 1;
	}

	size_t nbr_uv = dataMessage.latLength * dataMessage.lonLength;

	nc_type var_type;
	nc_inq_vartype(ncid, sal_varid, &var_type);

	float* sal_vals = (float*)calloc(nbr_uv, sizeof(float));
	if (!sal_vals) return false;

	if (var_type == NC_DOUBLE) {
		double* sal_double = (double*)calloc(nbr_uv, sizeof(double));
		if (!sal_double) { free(sal_vals); return false; }
		if (nc_get_vara_double(ncid, sal_varid, start, count, sal_double) != NC_NOERR) {
			free(sal_double); free(sal_vals); return false;
		}
		for (size_t i = 0; i < nbr_uv; i++) sal_vals[i] = (float)sal_double[i];
		free(sal_double);
	} else {
		if (nc_get_vara_float(ncid, sal_varid, start, count, sal_vals) != NC_NOERR) {
			free(sal_vals); return false;
		}
	}

	float sal_fill = -32767.0f;
	nc_get_att_float(ncid, sal_varid, "_FillValue", &sal_fill);

	dataMessage.salinity.resize(nbr_uv, ncdf_NOTDEF);

	// Rearrange data to [lat, lon] order regardless of file dimension order
	size_t latLen = dataMessage.latLength;
	size_t lonLen = dataMessage.lonLength;
	size_t count_records = 0;

	if (dims.lat_before_lon) {
		for (size_t j = 0; j < latLen; j++) {
			for (size_t k = 0; k < lonLen; k++) {
				double val = (double)sal_vals[count_records];
				if (!isnan(val) && isfinite(val) && val != sal_fill && val > 0.0 && val < 100.0)
					dataMessage.salinity[count_records] = val;
				else
					dataMessage.salinity[count_records] = ncdf_NOTDEF;
				count_records++;
			}
		}
	} else {
		// File order is [lon, lat] — reorder to [lat, lon]
		float* reordered = (float*)calloc(nbr_uv, sizeof(float));
		if (reordered) {
			for (size_t k = 0; k < lonLen; k++)
				for (size_t j = 0; j < latLen; j++)
					reordered[j * lonLen + k] = sal_vals[k * latLen + j];
			for (size_t i = 0; i < nbr_uv; i++) {
				double val = (double)reordered[i];
				if (!isnan(val) && isfinite(val) && val != sal_fill && val > 0.0 && val < 100.0)
					dataMessage.salinity[i] = val;
				else
					dataMessage.salinity[i] = ncdf_NOTDEF;
			}
			free(reordered);
		}
	}

	free(sal_vals);
	ncdfLog("[ncdf] readSalinityFromNC: Salinity read, lat_before_lon=%d\n", (int)dims.lat_before_lon);
	dataMessage.hasSalinity = true;
	return true;
}

bool MainDialog::readTimeStepData(ncdfDataMessage& dataMessage) {
	ncdfLog("[ncdf] readTimeStepData: timeIndex=%d, latLength=%d, lonLength=%d, ucurr.size=%zu\n",
		dataMessage.timeIndex, (int)dataMessage.latLength, (int)dataMessage.lonLength, dataMessage.ucurr.size());

	if (!dataMessage.latValues || !dataMessage.lonValues) {
		ncdfLog("[ncdf] readTimeStepData: latValues or lonValues is NULL\n");
		return false;
	}

	// Reuse vector capacity: assign() overwrites values in-place when capacity is sufficient.
	// If new file is larger, proactively free old buffers to avoid 32-bit heap fragmentation.
	size_t nbr_uv = dataMessage.latLength * dataMessage.lonLength;
	ncdfLog("[ncdf] readTimeStepData: nbr_uv=%zu, ucurr.cap=%zu\n", nbr_uv, dataMessage.ucurr.capacity());
	if (nbr_uv > dataMessage.ucurr.capacity()) {
		ncdfLog("[ncdf] readTimeStepData: capacity insufficient (%zu < %zu), freeing old buffers\n",
			dataMessage.ucurr.capacity(), nbr_uv);
		dataMessage.ucurr.clear(); dataMessage.ucurr.shrink_to_fit();
		dataMessage.vcurr.clear(); dataMessage.vcurr.shrink_to_fit();
		dataMessage.sst.clear(); dataMessage.sst.shrink_to_fit();
		dataMessage.salinity.clear(); dataMessage.salinity.shrink_to_fit();
	}
	try {
		dataMessage.ucurr.assign(nbr_uv, ncdf_NOTDEF);
		dataMessage.vcurr.assign(nbr_uv, ncdf_NOTDEF);
	} catch (const std::bad_alloc&) {
		ncdfLog("[ncdf] readTimeStepData: OOM assigning ucurr/vcurr (%zu elements)\n", nbr_uv);
		return false;
	}
	dataMessage.sst.clear();
	dataMessage.salinity.clear();

	int ncid;
	int retval;

	// Reuse persistent ncid for same-file time step switches (avoids repeated nc_open/nc_close)
	wxString filenameStr = dataMessage.fileName;
	if (m_openedNcid >= 0 && m_openedFileName == filenameStr) {
		ncid = m_openedNcid;
		ncdfLog("[ncdf] readTimeStepData: reusing cached ncid=%d\n", ncid);
	} else {
		// Close old file if open
		if (m_openedNcid >= 0) {
			nc_close(m_openedNcid);
			m_openedNcid = -1;
		}
		const wxCharBuffer mbBuf = filenameStr.mb_str();
		size_t mbLen = strlen(mbBuf);
		char* filename = new char[mbLen + 1];
		strcpy(filename, mbBuf);

		retval = nc_open(filename, NC_NOWRITE, &ncid);
		if (retval != NC_NOERR) {
			retval = nc_open(filename, NC_NOWRITE | NC_NETCDF4, &ncid);
		}
		delete[] filename;
		if (retval != NC_NOERR) {
			ncdfLog("[ncdf] readTimeStepData: nc_open failed, retval=%d\n", retval);
			return false;
		}
		m_openedNcid = ncid;
		m_openedFileName = filenameStr;
		ncdfLog("[ncdf] readTimeStepData: opened file, ncid=%d\n", ncid);
	}

	// Discover variable IDs (with cached fallback)
	int u_varid = m_cached_u_varid;
	int v_varid = m_cached_v_varid;
	if (u_varid < 0 || v_varid < 0) {
		ncdfLog("[ncdf] readTimeStepData: cache miss, falling back to CF discovery\n");
		{
			const char* alt_std[] = {"surface_eastward_sea_water_velocity", NULL};
			const char* long_hints[] = {"Eastward Current Velocity", "u-velocity component of current", NULL};
			const char* var_hints[] = {"u", "uo", "current_u", "curr_u", "u10", "u100", NULL};
			u_varid = find_var_by_cf(ncid, "eastward_sea_water_velocity", alt_std, long_hints, var_hints);
		}
		{
			const char* alt_std[] = {"surface_northward_sea_water_velocity", NULL};
			const char* long_hints[] = {"Northward Current Velocity", "v-velocity component of current", NULL};
			const char* var_hints[] = {"v", "vo", "current_v", "curr_v", "v10", "v100", NULL};
			v_varid = find_var_by_cf(ncid, "northward_sea_water_velocity", alt_std, long_hints, var_hints);
		}
	}

	bool hasUV = (u_varid != -1 && v_varid != -1);
	ncdfLog("[ncdf] readTimeStepData: hasUV=%d, u_varid=%d, v_varid=%d\n", (int)hasUV, u_varid, v_varid);

	// P2: Only read data types that are currently checked (visible).
	// Unchecked types will be read on-demand when the user clicks the checkbox.
	// Animation also needs U/V data for displacement computation.
	bool anyAnimate = pPlugIn && (pPlugIn->m_settingsCurrent.animate ||
	                              pPlugIn->m_settingsSeaTemp.animate ||
	                              pPlugIn->m_settingsSalinity.animate);
	bool needCurrent = pPlugIn && (pPlugIn->m_bShowCurrentForce || anyAnimate);
	bool needSST = pPlugIn && pPlugIn->m_bShowSeaTemp;
	bool needSal = pPlugIn && pPlugIn->m_bShowSalinity;
	ncdfLog("[ncdf] readTimeStepData: needCurrent=%d needSST=%d needSal=%d anyAnimate=%d "
	        "showCurr=%d showSST=%d showSal=%d animateCur=%d animateSST=%d animateSal=%d\n",
	        (int)needCurrent, (int)needSST, (int)needSal, (int)anyAnimate,
	        (int)(pPlugIn && pPlugIn->m_bShowCurrentForce),
	        (int)(pPlugIn && pPlugIn->m_bShowSeaTemp),
	        (int)(pPlugIn && pPlugIn->m_bShowSalinity),
	        (int)(pPlugIn && pPlugIn->m_settingsCurrent.animate),
	        (int)(pPlugIn && pPlugIn->m_settingsSeaTemp.animate),
	        (int)(pPlugIn && pPlugIn->m_settingsSalinity.animate));

	if (hasUV && needCurrent) {
		if (!readUVFromNC(ncid, u_varid, v_varid, dataMessage)) {
			ncdfLog("[ncdf] readTimeStepData: readUVFromNC failed\n");
			dataMessage.ucurr.clear();
			dataMessage.vcurr.clear();
		}
	} else {
		dataMessage.ucurr.clear();
		dataMessage.vcurr.clear();
	}

	if (ncid >= 0 && m_fileHasSeaTemp && needSST) {
		if (!readSSTFromNC(ncid, m_cached_sst_varid, dataMessage)) {
			ncdfLog("[ncdf] readTimeStepData: readSSTFromNC failed\n");
		}
	}

	if (ncid >= 0 && m_fileHasSalinity && needSal) {
		if (!readSalinityFromNC(ncid, m_cached_sal_varid, dataMessage)) {
			ncdfLog("[ncdf] readTimeStepData: readSalinityFromNC failed\n");
		}
	}

	ncdfLog("[ncdf] readTimeStepData: completed successfully\n");

	// Don't close ncid — it stays open for same-file time step switches
	return true;
}

wxDateTime MainDialog::GetDateFromHours(int hours_in){

	wxString baseDateTime = _T("2011-12-31 00:00:00");

	wxDateTime m_dt;
	m_dt.ParseDateTime(baseDateTime);

	wxTimeSpan m_ts = wxTimeSpan::Hours(hours_in);
	m_dt.Add(m_ts);

	return m_dt;
}


void MainDialog::onDirChanged(wxCommandEvent& event)
{
    ncdfLogW(L"[ncdf] onDirChanged: started, value=%ls\n", (const wchar_t*)this->m_textCtrlDir->GetValue().c_str());
	
	wxStandardPathsBase &std_path = wxStandardPathsBase::Get();
	wxString std = std_path.GetDocumentsDir();

	if(this->m_textCtrlDir->GetValue().length() != 0 && pPlugIn->m_ncdf_dir != std_path.GetDocumentsDir()){
	    ncdfLog("[ncdf] onDirChanged: calling fillDirTree\n");
		fillDirTree(this->m_textCtrlDir->GetValue(), true, 0);
	    ncdfLog("[ncdf] onDirChanged: fillDirTree returned\n");
	}
	else{
	    ncdfLog("[ncdf] onDirChanged: deleting all tree items\n");
		this->m_treeCtrl->DeleteAllItems();
	}
}

bool MainDialog::switchToFile(const wxString &fileName, const wxString &fn, int &idx)
{
	// Use a separate log file for crash debugging
	FILE *dbg = fopen("C:\\ProgramData\\opencpn\\ncdf_crash_trace.log", "a");
	if (dbg) { fprintf(dbg, "switchToFile: ENTER\n"); fflush(dbg); fclose(dbg); }

	ncdfLogW(L"[ncdf] switchToFile: switching to file %ls\n", (const wchar_t*)fn.c_str());

	// Close persistent ncid from previous file
	if (m_openedNcid >= 0) {
		nc_close(m_openedNcid);
		m_openedNcid = -1;
		m_openedFileName.Clear();
	}

	myDataVector.clear();
	m_lastSelectedTimeIndex = -1;
	myMessage.clear();

	if (pPlugIn) {
		ncdfOverlayFactory *pof = pPlugIn->GetncdfOverlayFactory();
		if (pof) {
			pof->m_currentOverlay.Cleanup();
			pof->m_seaTempOverlay.Cleanup();
			pof->m_salinityOverlay.Cleanup();
			pof->m_bReadyToRender = false;
		}
	}

	auto t0 = std::chrono::high_resolution_clock::now();

	// Use lightweight metadata reader instead of heavy nc_get
	FileMetadata meta = nc_read_metadata(fileName);
	if (!meta.valid) {
		ncdfLog("[ncdf] switchToFile: nc_read_metadata failed for %s\n", (const char*)fn.mb_str());
		return false;
	}
	m_currentFilePath = fileName;

	// Cache variable IDs for readTimeStepData
	m_fileHasCurrent = meta.hasCurrent;
	m_fileHasSeaTemp = meta.hasSeaTemp;
	m_fileHasSalinity = meta.hasSalinity;
	m_cached_u_varid = meta.cached_u_varid;
	m_cached_v_varid = meta.cached_v_varid;
	m_cached_sst_varid = meta.cached_sst_varid;
	m_cached_sal_varid = meta.cached_sal_varid;

	// Pre-allocate float grid structures (one-time per file, reused across all time steps)
	if (pPlugIn) {
		ncdfOverlayFactory *pof = pPlugIn->GetncdfOverlayFactory();
		if (pof) {
			int ni = (int)meta.lonlength;
			int nj = (int)meta.latlength;
			if (meta.hasCurrent) {
				pof->m_currentOverlay.ensureGridAllocated(ni, nj);
			}
			if (meta.hasSeaTemp) {
				pof->m_seaTempOverlay.ensureGridAllocated(ni, nj);
			}
			if (meta.hasSalinity) {
				pof->m_salinityOverlay.ensureGridAllocated(ni, nj);
			}
			ncdfLog("[switchToFile] pre-allocated grids: ni=%d nj=%d current=%d sst=%d sal=%d\n",
				ni, nj, (int)meta.hasCurrent, (int)meta.hasSeaTemp, (int)meta.hasSalinity);
		}
	}

	// Build lightweight myDataVector entries (metadata only, no heavy data)
	double* timeValuesArr = (double*)calloc(meta.timelength, sizeof(double));
	if (meta.sharedCoords && meta.sharedCoords->timeValues) {
		memcpy(timeValuesArr, meta.sharedCoords->timeValues, meta.timelength * sizeof(double));
	} else if (!meta.timeValues.empty()) {
		memcpy(timeValuesArr, meta.timeValues.data(), meta.timelength * sizeof(double));
	}

	myDataVector.clear();
	for (size_t i = 0; i < meta.timelength; i++) {
		ncdfDataMessage entry;
		entry.timeIndex = (int)i;
		entry.timeLength = meta.timelength;
		entry.latLength = meta.latlength;
		entry.lonLength = meta.lonlength;
		entry.numberOfPoints = (int)(meta.latlength * meta.lonlength);
		entry.noPointsParallel = (wxUint32)meta.lonlength;
		entry.noPointsMeridian = (wxUint32)meta.latlength;
		entry.firstGridPointLat = meta.firstGridPointLat;
		entry.firstGridPointLong = meta.firstGridPointLong;
		entry.lastGridPointLat = meta.lastGridPointLat;
		entry.lastGridPointLong = meta.lastGridPointLong;
		entry.iDirectionIncr = meta.iDirectionIncr;
		entry.jDirectionIncr = meta.jDirectionIncr;
		entry.fileName = fileName;
		entry.timeValid = meta.timeValid[i];
		entry.dataDateTime = meta.dates[i];
		entry.hasSeaTemp = meta.hasSeaTemp;
		entry.hasSalinity = meta.hasSalinity;
		// Share coordinates (one allocation, all entries share)
		entry.sharedCoords = meta.sharedCoords;
		entry.latValues = meta.sharedCoords ? meta.sharedCoords->latValues : NULL;
		entry.lonValues = meta.sharedCoords ? meta.sharedCoords->lonValues : NULL;
		// Time values: allocate per-entry (needed for CF time parsing)
		entry.timeValues = (double*)calloc(meta.timelength, sizeof(double));
		if (entry.timeValues && timeValuesArr) {
			memcpy(entry.timeValues, timeValuesArr, meta.timelength * sizeof(double));
		}
		entry.minutesAfterStart = meta.timeValid[i] ? (int)(meta.timeValues[i] * 3600.0 / 60.0) : (int)(i * 60);
		myDataVector.push_back(entry);
	}
	if (timeValuesArr) free(timeValuesArr);

	ncdfLog("[ncdf] switchToFile: metadata loaded, %zu entries, lat=%zu lon=%zu\n",
		meta.timelength, meta.latlength, meta.lonlength);

	auto t1 = std::chrono::high_resolution_clock::now();
	ncdfLog("[perf] switchToFile: nc_read_metadata=%lldms\n",
		(long long)std::chrono::duration_cast<std::chrono::milliseconds>(t1 - t0).count());

	// Auto-enable rendering for available data types (GRIB pattern)
	bool showCur = m_fileHasCurrent;
	bool showSST = m_fileHasSeaTemp;
	m_checkBoxBmpCurrentForce->Show(showCur);
	m_staticText40->Show(showCur);
	m_textCtrlCurrentForce->Show(showCur);
	m_checkBoxSeaTemp->Show(showSST);
	m_staticTextSeaTemp->Show(showSST);
	m_textCtrlSeaTemp->Show(showSST);
	bool showSal = m_fileHasSalinity;
	m_checkBoxSalinity->Show(showSal);
	m_staticTextSalinity->Show(showSal);
	m_textCtrlSalinity->Show(showSal);
	Layout();
	// Disable unavailable types. Don't auto-enable — use persisted settings.
	if (!showCur) {
		pPlugIn->m_bShowCurrentDir = false;
		pPlugIn->m_bShowCurrentForce = false;
		pPlugIn->m_bShowParticles = false;
		m_checkBoxBmpCurrentForce->SetValue(false);
	}
	if (!showSST) {
		pPlugIn->m_bShowSeaTemp = false;
		pPlugIn->m_bShowSeaTempIso = false;
		m_checkBoxSeaTemp->SetValue(false);
	}
	if (!showSal) {
		pPlugIn->m_bShowSalinity = false;
		m_checkBoxSalinity->SetValue(false);
	}

	return true;
}

void MainDialog::onTreeSelectionChanged(wxTreeEvent& event)
{
    ncdfLog("[ncdf] onTreeSelectionChanged: started\n");
	
	if (m_isTreeUpdating) {
		ncdfLog("[ncdf] onTreeSelectionChanged: m_isTreeUpdating=true, returning\n");
		return;
	}
	
	if(this->my_ncdfReader->isReading == true){
	    ncdfLog("[ncdf] onTreeSelectionChanged: isReading=true, returning\n");
		ncdfDialog::onTreeSelectionChanged(event); 
		return; 
	}

 	if(this->m_treeCtrl->GetRootItem() == event.GetItem()){
	    ncdfLog("[ncdf] onTreeSelectionChanged: root item selected, returning\n");
		return;
	}
	
	if (this->m_treeCtrl->HasChildren(event.GetItem())){
	    // File node clicked: just expand/collapse (same as clicking the expand button)
	    if (m_treeCtrl->IsExpanded(event.GetItem()))
	        m_treeCtrl->Collapse(event.GetItem());
	    else
	        m_treeCtrl->Expand(event.GetItem());
	    return;
	}

	ncdfDialog::onTreeSelectionChanged(event);

	// Re-entrancy guard: if a load is already in progress, skip this event
	if (m_isLoading) {
		ncdfLog("[ncdf] onTreeSelectionChanged: SKIP (load in progress)\n");
		return;
	}
	m_isLoading = true;

	MyTreeItemData* data = (MyTreeItemData*)this->m_treeCtrl->GetItemData(event.GetItem());
	if (data) {
		int idx = data->m_index;

		// Check if we need to load a different file first
		bool fileSwitched = false;
		wxTreeItemId parentItem = m_treeCtrl->GetItemParent(event.GetItem());
		if (parentItem.IsOk()) {
			wxString fn = m_treeCtrl->GetItemText(parentItem);
			wxString fileName = m_textCtrlDir->GetValue() + _T("\\") + fn;
			if (fileName != m_currentFilePath) {
				if (!switchToFile(fileName, fn, idx)) {
					m_isLoading = false;
					return;
				}
				fileSwitched = true;
			}
		}

		if (idx < 0 || idx >= (int)myDataVector.size()) {
			ncdfLog("[ncdf] onTreeSelectionChanged: index out of range\n");
			m_isLoading = false;
			return;
		}

		ncdfDataMessage& dataRef = myDataVector[idx];
		ncdfLog("[ncdf] onTreeSelectionChanged: idx=%d fileSwitched=%d\n", idx, (int)fileSwitched);
		m_lastSelectedTimeIndex = idx;
		m_dataLoaded = false;
		m_gridsReady = false;

		// === Phase 1: Immediate (< 5ms) — update UI, show checkboxes ===
		wxString timeText;
		if (dataRef.timeValid) {
			timeText = dataRef.dataDateTime.Format(_T("%Y-%m-%d %H:00"));
		} else {
			timeText = wxString::Format(_("time%d"), idx + 1);
		}
		m_staticTextDateTime->SetLabel(timeText);
		ncdfLog("[phase1] idx=%d fileSwitched=%d timeText='%s' m_fileHasCurrent=%d m_fileHasSST=%d m_fileHasSal=%d\n",
			idx, (int)fileSwitched, (const char*)timeText.mb_str(),
			(int)m_fileHasCurrent, (int)m_fileHasSeaTemp, (int)m_fileHasSalinity);

		ncdfLog("[phase1] checkbox state: showCurr=%d showSST=%d showSal=%d\n",
			(int)pPlugIn->m_bShowCurrentForce, (int)pPlugIn->m_bShowSeaTemp, (int)pPlugIn->m_bShowSalinity);

		// Cross-file: sync checkbox visibility + flags from persisted settings
		if (fileSwitched) {
			this->myMessage.clearData();
			if (!m_fileHasCurrent) {
				m_checkBoxBmpCurrentForce->SetValue(false);
				pPlugIn->m_bShowCurrentForce = false;
				pPlugIn->m_bShowCurrentDir = false;
				pPlugIn->m_bShowParticles = false;
			} else {
				m_checkBoxBmpCurrentForce->SetValue(pPlugIn->m_bShowCurrentForce);
			}
			if (!m_fileHasSeaTemp) {
				m_checkBoxSeaTemp->SetValue(false);
				pPlugIn->m_bShowSeaTemp = false;
				pPlugIn->m_bShowSeaTempIso = false;
			} else {
				m_checkBoxSeaTemp->SetValue(pPlugIn->m_bShowSeaTemp);
			}
			if (!m_fileHasSalinity) {
				m_checkBoxSalinity->SetValue(false);
				pPlugIn->m_bShowSalinity = false;
			} else {
				m_checkBoxSalinity->SetValue(pPlugIn->m_bShowSalinity);
			}
		}

		// Show/hide checkboxes based on file-level data availability
		m_checkBoxBmpCurrentForce->Show(m_fileHasCurrent);
		m_staticText40->Show(m_fileHasCurrent);
		m_textCtrlCurrentForce->Show(m_fileHasCurrent);
		m_checkBoxSeaTemp->Show(m_fileHasSeaTemp);
		m_staticTextSeaTemp->Show(m_fileHasSeaTemp);
		m_textCtrlSeaTemp->Show(m_fileHasSeaTemp);
		m_checkBoxSalinity->Show(m_fileHasSalinity);
		m_staticTextSalinity->Show(m_fileHasSalinity);
		m_textCtrlSalinity->Show(m_fileHasSalinity);
		Layout();
		// Disable unavailable types
		if (!m_fileHasCurrent) {
			pPlugIn->m_bShowCurrentDir = false;
			pPlugIn->m_bShowCurrentForce = false;
			pPlugIn->m_bShowParticles = false;
			m_checkBoxBmpCurrentForce->SetValue(false);
		}
		if (!m_fileHasSeaTemp) {
			pPlugIn->m_bShowSeaTemp = false;
			pPlugIn->m_bShowSeaTempIso = false;
			m_checkBoxSeaTemp->SetValue(false);
		}
		if (!m_fileHasSalinity) {
			pPlugIn->m_bShowSalinity = false;
			m_checkBoxSalinity->SetValue(false);
		}

		// Copy metadata to myMessage (no data yet)
		this->myMessage.noPointsParallel = dataRef.noPointsParallel;
		this->myMessage.noPointsMeridian = dataRef.noPointsMeridian;
		this->myMessage.firstGridPointLat = dataRef.firstGridPointLat;
		this->myMessage.firstGridPointLong = dataRef.firstGridPointLong;
		this->myMessage.lastGridPointLat = dataRef.lastGridPointLat;
		this->myMessage.lastGridPointLong = dataRef.lastGridPointLong;
		this->myMessage.iDirectionIncr = dataRef.iDirectionIncr;
		this->myMessage.jDirectionIncr = dataRef.jDirectionIncr;
		this->myMessage.latLength = dataRef.latLength;
		this->myMessage.lonLength = dataRef.lonLength;
		this->myMessage.timeLength = dataRef.timeLength;
		this->myMessage.hasSeaTemp = dataRef.hasSeaTemp;
		this->myMessage.hasSalinity = dataRef.hasSalinity;
		this->myMessage.sharedCoords = dataRef.sharedCoords;
		this->myMessage.latValues = dataRef.latValues;
		this->myMessage.lonValues = dataRef.lonValues;
		this->myMessage.timeValues = dataRef.timeValues;
		this->myMessage.timeIndex = dataRef.timeIndex;
		this->myMessage.timeValid = dataRef.timeValid;
		this->myMessage.dataDateTime = dataRef.dataDateTime;
		this->myMessage.fileName = dataRef.fileName;

		ncdfLog("[ncdf] onTreeSelectionChanged: Phase 1 complete, checkboxes shown\n");

		// Prevent checkbox events from firing during Phase 2
		m_isLoading = true;

		// === Phase 2: Deferred — read data + prepare grids ===
		// Use CallAfter to let the UI refresh first (show checkboxes)
		CallAfter([this, idx, fileSwitched]() {
			ncdfLog("[ncdf] Phase 2: starting deferred data load for idx=%d\n", idx);

			ncdfOverlayFactory *pof = pPlugIn->GetncdfOverlayFactory();
			if (pof) pof->m_bReadyToRender = false;

			// Read raw data into myMessage (all available types)
			ncdfLog("[phase2] reading time step data...\n");
			auto pt0 = std::chrono::high_resolution_clock::now();
			if (!readTimeStepData(this->myMessage)) {
				ncdfLog("[phase2] readTimeStepData FAILED\n");
				if (pof) pof->m_bReadyToRender = true;
				m_isLoading = false;
				return;
			}
			m_dataLoaded = true;
			auto pt1 = std::chrono::high_resolution_clock::now();
			ncdfLog("[phase2] data loaded: ucurr.size=%zu sst.size=%zu (%lldms)\n",
				this->myMessage.ucurr.size(), this->myMessage.sst.size(),
				(long long)std::chrono::duration_cast<std::chrono::milliseconds>(pt1 - pt0).count());
			ncdfLogMem(this, "phase2-data-loaded");

			// Set up overlay factory (bounds, gui, plugin pointers)
			ncdfLog("[phase2] calling setData\n");
			if (pof) {
				pof->setData(this, pPlugIn, this->myMessage,
					this->myMessage.numberOfPoints,
					this->myMessage.firstGridPointLat, this->myMessage.firstGridPointLong,
					this->myMessage.lastGridPointLat, this->myMessage.lastGridPointLong);
			}

			// Convert raw data to float grids for ALL available types
			ncdfLog("[phase2] calling prepareAllGrids\n");
			if (pof) pof->prepareAllGrids();
			m_gridsReady = true;
			ncdfLog("[phase2] grids prepared, m_gridsReady=true\n");
			ncdfLogMem(this, "phase2-grids-ready");

			// Release raw double data (grids are float, cursor tracking uses grids)
			ncdfLog("[phase2] releasing raw double data\n");
			this->myMessage.ucurr.clear();
			this->myMessage.vcurr.clear();
			this->myMessage.sst.clear();
			this->myMessage.salinity.clear();
			ncdfLogMem(this, "phase2-raw-released");

			// If a checkbox is already checked, compute coefficients for it (Phase 3)
			if (pof) {
				bool anyChecked = false;
				if (pPlugIn->m_bShowCurrentForce && pof->m_currentOverlay.cachedU) {
					ncdfLog("[phase2→3] auto-computing current coefficients\n");
					pof->m_currentOverlay.prepareCoeff(pof);
					anyChecked = true;
				}
				if (pPlugIn->m_bShowSeaTemp && pof->m_seaTempOverlay.cachedBaseGrid) {
					ncdfLog("[ncdf] Phase 2→3: auto-computing SST coefficients\n");
					pof->m_seaTempOverlay.prepareCoeff(pof);
					anyChecked = true;
				}
				if (pPlugIn->m_bShowSalinity && pof->m_salinityOverlay.cachedBaseGrid) {
					ncdfLog("[ncdf] Phase 2→3: auto-computing salinity coefficients\n");
					pof->m_salinityOverlay.prepareCoeff(pof);
					anyChecked = true;
				}
				if (anyChecked) {
					pof->m_bReadyToRender = true;
					RequestRefresh(m_parent);
				}
			}

			m_isLoading = false;
			ncdfLog("[ncdf] Phase 2: complete\n");
		});

	} else {
		ncdfLog("[ncdf] onTreeSelectionChanged: GetItemData returned NULL\n");
		m_isLoading = false;
	}
}

void MainDialog::onTreeItemRightClick(wxTreeEvent& event)
{
    if(this->m_treeCtrl->GetRootItem() == event.GetItem())
		return;

    wxTreeItemId id =  this->m_treeCtrl->GetSelection();
    MyTreeItemData *data = (MyTreeItemData *) this->m_treeCtrl->GetItemData(id);
}

void MainDialog::onDCurrentClick( wxCommandEvent& event )
{
	pPlugIn->m_bShowCurrentDir = m_checkBoxDCurrent->GetValue();
	RequestRefresh(m_parent);
}
void MainDialog::onBmpCurrentForceClick(wxCommandEvent& event)
{
	static bool s_guard = false;
	if (s_guard || m_isLoading) return;
	s_guard = true;
	bool checked = m_checkBoxBmpCurrentForce->GetValue();
	pPlugIn->m_bShowCurrentForce = checked;
	// Mutual exclusion: uncheck SST and Salinity color maps
	if (checked) {
		m_checkBoxSeaTemp->SetValue(false);
		pPlugIn->m_bShowSeaTemp = false;
		m_checkBoxSalinity->SetValue(false);
		pPlugIn->m_bShowSalinity = false;
	}
	s_guard = false;
	// Phase 3: Compute B-spline coefficients for the checked type
	ncdfLog("[phase3:cur] checked=%d m_gridsReady=%d cachedU=%p m_lastSelectedTimeIndex=%d\n",
		(int)checked, (int)m_gridsReady, (void*)(pPlugIn->GetncdfOverlayFactory() ? pPlugIn->GetncdfOverlayFactory()->m_currentOverlay.cachedU : NULL), m_lastSelectedTimeIndex);
	if (checked && m_lastSelectedTimeIndex >= 0) {
		ncdfOverlayFactory *pof = pPlugIn->GetncdfOverlayFactory();
		if (pof) {
			if (pof->m_currentOverlay.hasTexture) {
				// Texture on GPU — just display it (shader reads from GPU, not CPU coefficients)
				ncdfLog("[phase3:cur] texture exists, reusing\n");
				pof->m_currentOverlay.dataReady = true;
				pof->m_currentOverlay.needsRebuild = false;
			} else {
				// Read data first, then setData (so myMessage has data for setData)
				ncdfLog("[phase3:cur] loading data + computing coefficients\n");
				pof->m_bReadyToRender = false;
				if (readTimeStepData(this->myMessage)) {
					pof->setData(this, pPlugIn, this->myMessage,
						this->myMessage.numberOfPoints,
						this->myMessage.firstGridPointLat, this->myMessage.firstGridPointLong,
						this->myMessage.lastGridPointLat, this->myMessage.lastGridPointLong);
					if (!pof->m_currentOverlay.gridReady) pof->m_currentOverlay.prepareGrid(this);
					pof->m_currentOverlay.prepareCoeff(pof);
				}
				pof->m_bReadyToRender = true;
			}
		}
	}
	RequestRefresh(m_parent);
}

void MainDialog::onParticlesClick(wxCommandEvent& event)
{
	pPlugIn->m_bShowParticles = !pPlugIn->m_bShowParticles;
	RequestRefresh(m_parent);
}

void MainDialog::onSeaTempClick(wxCommandEvent& event)
{
	static bool s_guard = false;
	if (s_guard || m_isLoading) return;
	s_guard = true;
	bool checked = m_checkBoxSeaTemp->GetValue();
	pPlugIn->m_bShowSeaTemp = checked;
	// Mutual exclusion: uncheck Current and Salinity color maps
	if (checked) {
		m_checkBoxBmpCurrentForce->SetValue(false);
		pPlugIn->m_bShowCurrentForce = false;
		m_checkBoxSalinity->SetValue(false);
		pPlugIn->m_bShowSalinity = false;
	}
	s_guard = false;
	// Phase 3: Compute B-spline coefficients for SST
	if (checked && m_lastSelectedTimeIndex >= 0) {
		ncdfOverlayFactory *pof = pPlugIn->GetncdfOverlayFactory();
		if (pof) {
			if (pof->m_seaTempOverlay.hasTexture) {
				ncdfLog("[phase3:sst] texture exists, reusing\n");
				pof->m_seaTempOverlay.dataReady = true;
				pof->m_seaTempOverlay.needsRebuild = false;
			} else {
				ncdfLog("[phase3:sst] loading data + computing coefficients\n");
				pof->m_bReadyToRender = false;
				if (readTimeStepData(this->myMessage)) {
					pof->setData(this, pPlugIn, this->myMessage,
						this->myMessage.numberOfPoints,
						this->myMessage.firstGridPointLat, this->myMessage.firstGridPointLong,
						this->myMessage.lastGridPointLat, this->myMessage.lastGridPointLong);
					if (!pof->m_seaTempOverlay.gridReady) pof->m_seaTempOverlay.prepareGrid(this);
					pof->m_seaTempOverlay.prepareCoeff(pof);
				}
				pof->m_bReadyToRender = true;
			}
		}
	}
	RequestRefresh(m_parent);
}

void MainDialog::onIsoSSTClick(wxCommandEvent& event)
{
	pPlugIn->m_settingsSeaTemp.showIsoLines = m_checkBoxIsoSST->GetValue();
	pPlugIn->m_bShowSeaTempIso = pPlugIn->m_settingsSeaTemp.showIsoLines;  // sync legacy flag
	ncdfOverlayFactory *pof = pPlugIn->GetncdfOverlayFactory();
	if (pof) pof->SetBicubicMode(true);
	RequestRefresh(m_parent);
}
void MainDialog::onIsoSalClick(wxCommandEvent& event)
{
	pPlugIn->m_settingsSalinity.showIsoLines = m_checkBoxIsoSal->GetValue();
	ncdfOverlayFactory *pof = pPlugIn->GetncdfOverlayFactory();
	if (pof) pof->SetBicubicMode(true);
	RequestRefresh(m_parent);
}

void MainDialog::onSalinityClick(wxCommandEvent& event)
{
	static bool s_guard = false;
	if (s_guard || m_isLoading) return;
	s_guard = true;
	bool checked = m_checkBoxSalinity->GetValue();
	pPlugIn->m_bShowSalinity = checked;
	// Mutual exclusion: uncheck Current and SST color maps
	if (checked) {
		m_checkBoxBmpCurrentForce->SetValue(false);
		pPlugIn->m_bShowCurrentForce = false;
		m_checkBoxSeaTemp->SetValue(false);
		pPlugIn->m_bShowSeaTemp = false;
	}
	s_guard = false;
	// Phase 3: Compute B-spline coefficients for Salinity
	if (checked && m_lastSelectedTimeIndex >= 0) {
		ncdfOverlayFactory *pof = pPlugIn->GetncdfOverlayFactory();
		if (pof) {
			if (pof->m_salinityOverlay.hasTexture) {
				ncdfLog("[phase3:sal] texture exists, reusing\n");
				pof->m_salinityOverlay.dataReady = true;
				pof->m_salinityOverlay.needsRebuild = false;
			} else {
				ncdfLog("[phase3:sal] loading data + computing coefficients\n");
				pof->m_bReadyToRender = false;
				if (readTimeStepData(this->myMessage)) {
					pof->setData(this, pPlugIn, this->myMessage,
						this->myMessage.numberOfPoints,
						this->myMessage.firstGridPointLat, this->myMessage.firstGridPointLong,
						this->myMessage.lastGridPointLat, this->myMessage.lastGridPointLong);
					if (!pof->m_salinityOverlay.gridReady) pof->m_salinityOverlay.prepareGrid(this);
					pof->m_salinityOverlay.prepareCoeff(pof);
				}
				pof->m_bReadyToRender = true;
			}
		}
	}
	RequestRefresh(m_parent);
}

void MainDialog::fillDirTree(wxString path, bool start, wxTreeItemId id)
{
    ncdfLogW(L"[ncdf] fillDirTree: started, path=%ls, start=%d\n", (const wchar_t*)path.c_str(), (int)start);

	if(start == true)
	{
		ncdfLog("[ncdf] fillDirTree: deleting all tree items\n");

		m_isTreeUpdating = true;
		m_treeCtrl->Freeze();
		this->m_treeCtrl->DeleteAllItems();

		id = this->m_treeCtrl->AddRoot(_T(""));
		this->m_treeCtrl->SetItemText(id,_("ncdf-Files"));
		this->m_treeCtrl->SelectItem(id);
		// Keep m_isTreeUpdating=true and Freeze() active through addChildren loop
		ncdfLog("[ncdf] fillDirTree: root item created\n");
	}

	wxDir dir(path);
	if(dir.IsOpened() && dir.HasFiles())
	{
		ncdfLog("[ncdf] fillDirTree: directory opened successfully\n");

		wxString s;
		if (dir.GetFirst(&s, wxEmptyString, wxDIR_FILES)) {
			do {
				wxString ext = s.Mid(s.find_last_of('.') + 1).Lower();
				if (ext == "nc" || ext == "nc4") {
					ncdfLogW(L"[ncdf] fillDirTree: adding file: %ls\n", (const wchar_t*)s.c_str());

					wxTreeItemId iid = this->m_treeCtrl->AppendItem(id, s);

					ncdfLogW(L"[ncdf] fillDirTree: calling addChildren for %ls\n", (const wchar_t*)s.c_str());
					addChildren(iid, s);

					ncdfLog("[ncdf] fillDirTree: addChildren returned\n");
				}
			} while (dir.GetNext(&s));
		}
	}

	// Release tree update guard and thaw display
	m_isTreeUpdating = false;
	if (start) m_treeCtrl->Thaw();

	ncdfLog("[ncdf] fillDirTree: completed\n");
}

void MainDialog::addChildren(wxTreeItemId id, wxString fn)
{
    ncdfLogW(L"[ncdf] addChildren: started, fn=%ls\n", (const wchar_t*)fn.c_str());

	wxString fileName = this->m_textCtrlDir->GetValue()+_("\\")+fn;
	ncdfLogW(L"[ncdf] addChildren: fileName=%ls\n", (const wchar_t*)fileName.c_str());

	// Lightweight metadata read — no myDataVector allocation, no nc_get overhead
	FileMetadata meta = nc_read_metadata(fileName);
	if (!meta.valid) {
		ncdfLog("[ncdf] addChildren: nc_read_metadata failed for %s\n", (const char*)fileName.mb_str());
		return;
	}
	ncdfLog("[ncdf] addChildren: metadata OK, timelength=%zu hasCurrent=%d hasSST=%d hasSal=%d\n",
		meta.timelength, (int)meta.hasCurrent, (int)meta.hasSeaTemp, (int)meta.hasSalinity);

	for (size_t i = 0; i < meta.timelength; i++) {
		wxTreeItemId itemId = this->m_treeCtrl->AppendItem(id, _T(""));
		wxString timeText;
		if (meta.timeValid[i]) {
			timeText = meta.dates[i].Format(_T("%Y-%m-%d %H:00"));
		} else {
			timeText = wxString::Format(_("time%d"), (int)i + 1);
		}
		this->m_treeCtrl->SetItemText(itemId, timeText);
		MyTreeItemData* treeItemData = new MyTreeItemData((int)i);
		this->m_treeCtrl->SetItemData(itemId, treeItemData);
	}

	ncdfLog("[ncdf] addChildren: completed, %zu tree items created\n", meta.timelength);
}

void MainDialog::OnContextMenu(double m_lat, double m_lon){

	// show some info about this item
	wxTreeItemId itemId = m_treeCtrl->GetFocusedItem();
	MyTreeItemData *item = (MyTreeItemData *)this->m_treeCtrl->GetItemData(itemId);

	if (item == NULL)
	{
		return;
	}

	int response;
	wxMessageDialog *dial = new wxMessageDialog(NULL, _T("Show tidal current at the cursor position?"), wxT("Proceed?"), wxOK | wxCANCEL);

	response = dial->ShowModal();

	if (response == wxID_OK) {
		pPlugIn->b_showODAS = true;
		Arrow *m_Arrow = new Arrow;
		m_Arrow->m_lat = m_lat;
		m_Arrow->m_lon = m_lon;
		m_ArrowList.push_back(m_Arrow);
	}
	else{
		pPlugIn->b_showODAS = false;
		m_ArrowList.clear();

		return;
	}
}

void MainDialog::BuildHelpPage(){
	// Download page replaced by Settings page - no-op
}


void MainDialog::onAnimateClick(wxCommandEvent& event)
{
	bool checked = m_checkBoxAnimate->GetValue();
	pPlugIn->m_settingsCurrent.animate = checked;
	if (checked) {
		m_checkBoxAnimateSST->SetValue(false);
		pPlugIn->m_settingsSeaTemp.animate = false;
		m_checkBoxAnimateSal->SetValue(false);
		pPlugIn->m_settingsSalinity.animate = false;
	}
	ncdfOverlayFactory *pof = pPlugIn->GetncdfOverlayFactory();
	if (pof) {
		if (checked) {
			pof->m_animate.Init(pPlugIn, this);
			// Ensure coefficient texture and grids exist for animation
			if (!pof->m_currentOverlay.hasTexture && m_gridsReady) {
				if (readTimeStepData(this->myMessage)) {
					pof->setData(this, pPlugIn, this->myMessage,
						this->myMessage.numberOfPoints,
						this->myMessage.firstGridPointLat, this->myMessage.firstGridPointLong,
						this->myMessage.lastGridPointLat, this->myMessage.lastGridPointLong);
					pof->m_currentOverlay.prepareGrid(this);
					pof->m_currentOverlay.prepareCoeff(pof);
				}
			}
			// Compute displacement map and initialize coordinate fields from float grids
			if (pof->m_currentOverlay.cachedU && pof->m_currentOverlay.cachedV) {
				int ni = pof->m_currentOverlay.cachedVNi;
				int nj = pof->m_currentOverlay.cachedUNj;
				if (pof->m_animate.ComputeDisplacementMap(
						pof->m_currentOverlay.cachedU,
						pof->m_currentOverlay.cachedV, ni, nj)) {
					pof->m_animate.InitCoordFields(ni, nj);
				}
			}
			pof->m_animateTimer.Start(250);
		} else if (!pPlugIn->m_settingsSeaTemp.animate && !pPlugIn->m_settingsSalinity.animate) {
			pof->m_animateTimer.Stop();
			pof->m_animate.Cleanup();
		}
		pof->SetBicubicMode(true);
	}
	RequestRefresh(m_parent);
}
void MainDialog::onAnimateSSTClick(wxCommandEvent& event)
{
	bool checked = m_checkBoxAnimateSST->GetValue();
	pPlugIn->m_settingsSeaTemp.animate = checked;
	if (checked) {
		m_checkBoxAnimate->SetValue(false);
		pPlugIn->m_settingsCurrent.animate = false;
		m_checkBoxAnimateSal->SetValue(false);
		pPlugIn->m_settingsSalinity.animate = false;
	}
	ncdfOverlayFactory *pof = pPlugIn->GetncdfOverlayFactory();
	if (pof) {
		if (checked) {
			pof->m_animate.Init(pPlugIn, this);
			// Load U/V data first (needed for displacement computation)
			if (readTimeStepData(this->myMessage)) {
				pof->setData(this, pPlugIn, this->myMessage,
					this->myMessage.numberOfPoints,
					this->myMessage.firstGridPointLat, this->myMessage.firstGridPointLong,
					this->myMessage.lastGridPointLat, this->myMessage.lastGridPointLong);
				pof->prepareAllGrids();
				pof->m_seaTempOverlay.prepareCoeff(pof);
			}
			// Compute displacement from prepared U/V grids
			if (pof->m_currentOverlay.cachedU && pof->m_currentOverlay.cachedV) {
				int ni = pof->m_currentOverlay.cachedVNi;
				int nj = pof->m_currentOverlay.cachedUNj;
				if (pof->m_animate.ComputeDisplacementMap(
						pof->m_currentOverlay.cachedU,
						pof->m_currentOverlay.cachedV, ni, nj)) {
					pof->m_animate.InitCoordFields(ni, nj);
					pof->m_animate.SetExternalSourceGrids(
						pof->m_currentOverlay.cachedU,
						pof->m_currentOverlay.cachedV, ni, nj);
				}
			}
			pof->m_animateTimer.Start(250);
		} else if (!pPlugIn->m_settingsCurrent.animate && !pPlugIn->m_settingsSalinity.animate) {
			pof->m_animateTimer.Stop();
			pof->m_animate.Cleanup();
		}
		pof->SetBicubicMode(true);
	}
	RequestRefresh(m_parent);
}
void MainDialog::onAnimateSalClick(wxCommandEvent& event)
{
	bool checked = m_checkBoxAnimateSal->GetValue();
	pPlugIn->m_settingsSalinity.animate = checked;
	if (checked) {
		m_checkBoxAnimate->SetValue(false);
		pPlugIn->m_settingsCurrent.animate = false;
		m_checkBoxAnimateSST->SetValue(false);
		pPlugIn->m_settingsSeaTemp.animate = false;
	}
	ncdfOverlayFactory *pof = pPlugIn->GetncdfOverlayFactory();
	if (pof) {
		if (checked) {
			pof->m_animate.Init(pPlugIn, this);
			// Load U/V data first (needed for displacement computation)
			if (readTimeStepData(this->myMessage)) {
				pof->setData(this, pPlugIn, this->myMessage,
					this->myMessage.numberOfPoints,
					this->myMessage.firstGridPointLat, this->myMessage.firstGridPointLong,
					this->myMessage.lastGridPointLat, this->myMessage.lastGridPointLong);
				// Prepare ALL grids (including current overlay's U/V for displacement)
				pof->prepareAllGrids();
				pof->m_salinityOverlay.prepareCoeff(pof);
			}
			// Compute displacement from prepared U/V grids
			if (pof->m_currentOverlay.cachedU && pof->m_currentOverlay.cachedV) {
				int ni = pof->m_currentOverlay.cachedVNi;
				int nj = pof->m_currentOverlay.cachedUNj;
				if (pof->m_animate.ComputeDisplacementMap(
						pof->m_currentOverlay.cachedU,
						pof->m_currentOverlay.cachedV, ni, nj)) {
					pof->m_animate.InitCoordFields(ni, nj);
					pof->m_animate.UploadCoordFields();  // sync CPU → GPU
					pof->m_animate.SetExternalSourceGrids(
						pof->m_currentOverlay.cachedU,
						pof->m_currentOverlay.cachedV, ni, nj);
				}
			}
			pof->m_animateTimer.Start(250);
		} else if (!pPlugIn->m_settingsCurrent.animate && !pPlugIn->m_settingsSeaTemp.animate) {
			pof->m_animateTimer.Stop();
			pof->m_animate.Cleanup();
		}
		pof->SetBicubicMode(true);
	}
	RequestRefresh(m_parent);
}
