/*********************************************************************
 * Name:      	main.cpp
 * Purpose:   	Implements simple wxWidgets application with GUI
 * 				created using wxFormBuilder.
 * Author:      Mike Rossiter

 * Created:
 * Copyright:
 * License:
 *
 * Notes:		Note that all GUI creation code is implemented in
 * 				gui.cpp source file which is generated by wxFormBuilder.
 *********************************************************************/

#include "stdio.h"
#include "wx/wx.h"
#include "wx/dir.h"
#include <wx/wfstream.h>
#include <wx/sstream.h>
#include <wx/protocol/http.h>
#include <wx/treectrl.h>
#include <wx/treebase.h>
#include <wx/hash.h>
#include <wx/utils.h>
#include <wx/log.h>
#include <wx/stdpaths.h>

#include "folder.xpm"

#include "ncdf.h"
#include "ncdf_reader.h"
#include "ncdfdata.h"
#include "ncdf_pi.h"
#include <vector>

using namespace std;

void ncdfLog(const char* format, ...) {
    FILE *logFile = fopen("C:\\ProgramData\\opencpn\\ncdf_debug.log", "a");
    if (logFile) {
        va_list args;
        va_start(args, format);
        vfprintf(logFile, format, args);
        va_end(args);
        fflush(logFile);
        fclose(logFile);
    }
}

static void ncdfLogW(const wchar_t* format, ...) {
    FILE *logFile = fopen("C:\\ProgramData\\opencpn\\ncdf_debug.log", "a");
    if (logFile) {
        va_list args;
        va_start(args, format);
        vfwprintf(logFile, format, args);
        va_end(args);
        fflush(logFile);
        fclose(logFile);
    }
}

MainDialog::MainDialog(wxWindow *parent) : ncdfDialog( parent ), m_isTreeUpdating(false)
{
	ncdfLog("[ncdf] MainDialog constructor: started\n");
	
	this->my_ncdfReader = new ncdfReader(this);
	
	ncdfLog("[ncdf] MainDialog constructor: ncdfReader created\n");
	
	this->m_parent = parent;
	selectionRectangle.bottomLat = selectionRectangle.bottomLon
	= selectionRectangle.topLat = selectionRectangle.topLon = ncdf_NOTDEF;

	log_window_m = NULL;
	m_lastSelectedTimeIndex = -1;
	gridu = NULL;
	gridv = NULL;
	gridSST = NULL;
	hasSeaTemp = false;

	// Hide all data checkboxes by default (shown when data is loaded)
	m_checkBoxDCurrent->Hide();
	m_staticText333->Hide();
	m_textCtrlCurrentDir->Hide();
	m_checkBoxBmpCurrentForce->Hide();
	m_staticText40->Hide();
	m_textCtrlCurrentForce->Hide();
	m_staticText41->Hide();
	m_checkBoxParticles->Hide();
	m_staticTextParticles->Hide();
	m_checkBoxSeaTemp->Hide();
	m_staticTextSeaTemp->Hide();
	m_checkBoxSeaTempIso->Hide();
	m_staticTextSeaTempIso->Hide();

	m_bpPrev->SetBitmap(wxBitmap(prev1));
	m_bpNext->SetBitmap(wxBitmap(next1));
	m_fileButton->SetBitmap(wxBitmap(openfile));

	// Connect prev/next buttons to handlers
	m_bpPrev->Connect( wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler( MainDialog::onPrev ), NULL, this );
	m_bpNext->Connect( wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler( MainDialog::onNext ), NULL, this );

	BuildHelpPage();

	/* Ensure dialog and its contents can be resized */
	this->SetWindowStyleFlag(this->GetWindowStyleFlag() | wxRESIZE_BORDER);
	this->SetSizeHints(280, 460, -1, -1);
	this->Layout();
}

MainDialog::~MainDialog()
{
	ncdfLog("[ncdf] ~MainDialog: started\n");

	// Disconnect prev/next buttons
	m_bpPrev->Disconnect( wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler( MainDialog::onPrev ), NULL, this );
	m_bpNext->Disconnect( wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler( MainDialog::onNext ), NULL, this );

	if(log_window_m)
		delete log_window_m;
	
	ncdfLog("[ncdf] ~MainDialog: log_window_m deleted\n");
	
	if (gridu) {
		for (wxUint32 i = 0; i < myMessage.noPointsMeridian; ++i) {
			delete[] gridu[i];
		}
		delete[] gridu;
	}
	if (gridv) {
		for (wxUint32 i = 0; i < myMessage.noPointsMeridian; ++i) {
			delete[] gridv[i];
		}
		delete[] gridv;
	}
	if (gridSST) {
		for (wxUint32 i = 0; i < myMessage.noPointsMeridian; ++i) {
			delete[] gridSST[i];
		}
		delete[] gridSST;
	}

	delete my_ncdfReader;
	
	ncdfLog("[ncdf] ~MainDialog: my_ncdfReader deleted\n");
	
	pPlugIn->m_choice = m_choiceTime->GetSelection();
	pPlugIn->m_bShowCurrentDir = m_checkBoxDCurrent->GetValue();
	pPlugIn->m_bShowCurrentForce = m_checkBoxBmpCurrentForce->GetValue();
	pPlugIn->m_bShowParticles = m_checkBoxParticles->GetValue();
	
	ncdfLog("[ncdf] ~MainDialog: settings saved\n");
	
	myDataVector.clear();
	
	ncdfLog("[ncdf] ~MainDialog: myDataVector cleared\n");
	
	ncdfLog("[ncdf] ~MainDialog: completed\n");
}

void MainDialog::setPlugIn(ncdf_pi *p)
{
  this->pPlugIn = p;
  this->m_textCtrlDir->SetValue(pPlugIn->m_ncdf_dir);
  m_choiceTime->SetSelection(pPlugIn->m_choice);
  m_checkBoxDCurrent->SetValue(pPlugIn->m_bShowCurrentDir);
  m_checkBoxBmpCurrentForce->SetValue(pPlugIn->m_bShowCurrentForce);
  m_checkBoxParticles->SetValue(pPlugIn->m_bShowParticles);
}

void MainDialog::SetCursorLatLon(double lat, double lon)
{
      m_cursor_lon = lon;
      m_cursor_lat = lat;

      UpdateTrackingControls();
}

void MainDialog::UpdateTrackingControls()
{
   this->m_textCtrlCurrentDir->Clear();
   this->m_textCtrlCurrentForce->Clear();
   if (gridu && gridv) printCurrentData();

   // SST temperature at cursor position — show only when data loaded and checkbox enabled
   m_textCtrlSeaTemp->Clear();
   if (gridSST && hasSeaTemp && pPlugIn->m_bShowSeaTemp) {
       double temp = myMessage.getInterpolatedValue(myMessage, gridSST, m_cursor_lon, m_cursor_lat, true);
       if (temp != ncdf_NOTDEF && !isnan(temp) && isfinite(temp)) {
           wxString t;
           t.Printf(_T("%.1f"), temp);
           m_textCtrlSeaTemp->SetValue(t);
       }
       m_textCtrlSeaTemp->Show(true);
       m_staticTextSeaTempUnit->Show(true);
   } else {
       m_textCtrlSeaTemp->Show(false);
       m_staticTextSeaTempUnit->Show(false);
   }
}

void MainDialog::printCurrentData()
{
	  if (!gridu || !gridv) return;
	  wxString t;
      double cDir;
      double cForce;

      cDir = myMessage.getInterpolatedValue(myMessage, gridu, m_cursor_lon, m_cursor_lat, true);
	  cForce = myMessage.getInterpolatedValue(myMessage, gridv, m_cursor_lon, m_cursor_lat, true);

			if ((cDir != ncdf_NOTDEF) && (cForce != ncdf_NOTDEF))
			{
				double force = sqrt(cDir*cDir + cForce*cForce)*3.6 / 1.852;
				t.Printf(_T("%3.1f"), force);
				this->m_textCtrlCurrentForce->AppendText(t);
				double dir = 90. + (atan2(cForce, -cDir)  * 180. / PI) - 180;
				if (dir < 0) dir = 360 + dir;
				t.Printf(_T("%3.1f"), dir);
				this->m_textCtrlCurrentDir->AppendText(t);
			}
}

CurrentData MainDialog::getCurrentData(double lat, double lon)
{
	CurrentData result = {0, 0};
	if (!gridu || !gridv) return result;
	wxString t;
	double cDir;
	double cForce;

	cDir = myMessage.getInterpolatedValue(myMessage, gridu, lon, lat, true);
	cForce = myMessage.getInterpolatedValue(myMessage, gridv, lon, lat, true);

	if ((cDir != ncdf_NOTDEF) && (cForce != ncdf_NOTDEF))
	{
		result.force = sqrt(cDir*cDir + cForce*cForce)*3.6 / 1.852;
		result.dir = 90. + (atan2(cForce, -cDir)  * 180. / PI) - 180;
		if (result.dir < 0) result.dir = 360 + result.dir;
	}
	
	return result;
}


double** MainDialog::makeGridDataCURRENT(ncdfDataMessage message, wxString current){

	int y = message.noPointsMeridian, x = message.noPointsParallel;
	double** grid = new double*[y];
	grid[0] = new double[y*x];
	for (int i = 1; i < y; ++i)
		grid[i] = grid[i - 1] + x;

	unsigned int count = 0;
	int bit = 7;
	unsigned int index;
	index = 0;

	for (unsigned int lat = 0; lat < message.noPointsMeridian; lat++)
	{
		for (unsigned int lon = 0; lon < message.noPointsParallel; lon++)
		{
			if (current == _T("currentu")){
				grid[lat][lon] = message.ucurr[count++];
			}
			else if (current == _T("currentv")){
				grid[lat][lon] = message.vcurr[count++];
			}

		}
	}
	return grid;
}

void MainDialog::onPrev(wxCommandEvent& event) {

	// show some info about this item
	wxTreeItemId itemId = m_treeCtrl->GetFocusedItem();
	MyTreeItemData *item = (MyTreeItemData *)this->m_treeCtrl->GetItemData(itemId);
	this->m_treeCtrl->SetItemDropHighlight(itemId, false);

	if (item != NULL)
	{
		wxTreeItemId tid;
		tid = this->m_treeCtrl->GetPrevSibling(itemId);
		if (tid.IsOk() == true){
			this->m_treeCtrl->SetItemDropHighlight(tid, true);
			this->m_treeCtrl->SetFocusedItem(tid);
			readData(tid);
		}
		else {
			this->m_treeCtrl->SetItemDropHighlight(itemId, true);
			return;
		}
	}
	else {
		return;
	}

}

void MainDialog::onNext(wxCommandEvent& event) {

	// show some info about this item
	wxTreeItemId itemId = m_treeCtrl->GetFocusedItem();
	MyTreeItemData *item = (MyTreeItemData *)this->m_treeCtrl->GetItemData(itemId);
	this->m_treeCtrl->SetItemDropHighlight(itemId, false);

	if (item != NULL)
	{
		wxTreeItemId tid;
		tid = this->m_treeCtrl->GetNextSibling(itemId);
		if (tid.IsOk() == true){
			this->m_treeCtrl->SetItemDropHighlight(tid, true);
			this->m_treeCtrl->SetFocusedItem(tid);
			readData(tid);
		}
		else {
			this->m_treeCtrl->SetItemDropHighlight(itemId, true);
			return;
		}
	}
	else {

		return;
	}

}

void MainDialog::readData(wxTreeItemId itemId) {
    FILE *logFile = fopen("C:\\ProgramData\\opencpn\\ncdf_debug.log", "a");
    if (logFile) {
        fwprintf(logFile, L"[ncdf] readData: started, itemId=%p\n", itemId.m_pItem);
        fflush(logFile);
    }
    
	MyTreeItemData *data = (MyTreeItemData *) this->m_treeCtrl->GetItemData(itemId);
	
	if (logFile) {
        fwprintf(logFile, L"[ncdf] readData: data=%p\n", data);
        fflush(logFile);
    }
	
	if (data == NULL) {
		if (logFile) {
			fwprintf(logFile, L"[ncdf] readData: data is NULL, returning\n");
			fflush(logFile);
			fclose(logFile);
		}
		return;
	}

	int idx = data->m_index;
	if (logFile) {
        fwprintf(logFile, L"[ncdf] readData: index=%d, m_lastSelectedTimeIndex=%d, vectorSize=%d\n", 
            idx, m_lastSelectedTimeIndex, (int)myDataVector.size());
        fflush(logFile);
    }
	
	if (idx < 0 || idx >= (int)myDataVector.size()) {
		if (logFile) {
            fwprintf(logFile, L"[ncdf] readData: index out of range\n");
            fflush(logFile);
            fclose(logFile);
        }
		return;
	}
	
	if (m_lastSelectedTimeIndex >= 0 && m_lastSelectedTimeIndex < (int)myDataVector.size()) {
		if (logFile) {
            fwprintf(logFile, L"[ncdf] readData: clearing myDataVector[%d]\n", m_lastSelectedTimeIndex);
            fflush(logFile);
        }
		myDataVector[m_lastSelectedTimeIndex].clear();
	}
	
	ncdfLog("[ncdf] readData: HELLO_SST_TEST idx=%d, vectorSize=%d\n", idx, (int)myDataVector.size());

	if (logFile) {
        fwprintf(logFile, L"[ncdf] readData: calling readTimeStepData for index=%d\n", idx);
        fflush(logFile);
    }
	if (!readTimeStepData(myDataVector[idx])) {
		ncdfLog("[ncdf] readData: readTimeStepData returned FALSE\n");
		if (logFile) {
            fwprintf(logFile, L"[ncdf] readData: readTimeStepData failed\n");
            fflush(logFile);
            fclose(logFile);
        }
		return;
	}

	ncdfLog("[ncdf] readData: readTimeStepData returned TRUE, calling readncdfFile\n");
	
	if (logFile) {
        fwprintf(logFile, L"[ncdf] readData: readTimeStepData succeeded\n");
        fflush(logFile);
    }
	
	m_lastSelectedTimeIndex = idx;

	// Sync slider with current time step
	if (m_sTimeline) {
		m_sTimeline->SetValue(idx);
	}

	if (logFile) {
        fwprintf(logFile, L"[ncdf] readData: updated m_lastSelectedTimeIndex=%d\n", m_lastSelectedTimeIndex);
        fflush(logFile);
    }
	
	if (logFile) {
        fwprintf(logFile, L"[ncdf] readData: calling readncdfFile\n");
        fflush(logFile);
    }
	this->my_ncdfReader->readncdfFile(myDataVector[idx]);
	
	if (logFile) {
        fwprintf(logFile, L"[ncdf] readData: readncdfFile returned\n");
        fflush(logFile);
    }
	
	pPlugIn->GetncdfOverlayFactory()->renderSelectionRectangle = false;
	RequestRefresh(m_parent);
	
	if (logFile) {
        fwprintf(logFile, L"[ncdf] readData: completed\n");
        fflush(logFile);
        fclose(logFile);
    }
}

void MainDialog::OnCloseFrame(wxCloseEvent& event) {

}

void MainDialog::onCloseDialog(wxCloseEvent& event)
{
    pPlugIn->OnncdfDialogClose();
}

void MainDialog::OnExitClick(wxCommandEvent& event) {
//	Destroy();
}

void MainDialog::onFileButtonClick(wxCommandEvent& event)
{
    ncdfLog("[ncdf] onFileButtonClick: started\n");
    
    wxDirDialog fd(this,_("Select a directory"),pPlugIn->m_ncdf_dir);
    ncdfLog("[ncdf] onFileButtonClick: dialog created\n");

    if(fd.ShowModal() != wxID_OK) {
        ncdfLog("[ncdf] onFileButtonClick: user canceled\n");
        return; 
    }
    
    ncdfLog("[ncdf] onFileButtonClick: directory selected\n");
    
    ncdfLog("[ncdf] onFileButtonClick: pPlugIn=%p\n", pPlugIn);
    
    pPlugIn->m_ncdf_dir = fd.GetPath();
    
    ncdfLog("[ncdf] onFileButtonClick: pPlugIn->m_ncdf_dir set\n");
    
    ncdfLog("[ncdf] onFileButtonClick: m_textCtrlDir=%p\n", m_textCtrlDir);
    
    this->m_textCtrlDir->SetValue(pPlugIn->m_ncdf_dir);
    
    ncdfLog("[ncdf] onFileButtonClick: m_textCtrlDir->SetValue done\n");
    
    ncdfLog("[ncdf] onFileButtonClick: completed\n");
}

/* Helper: read a text attribute from a variable. Caller must delete[] the result. */
static char* read_var_att_text(int ncid, int varid, const char* attname) {
    size_t attlen;
    if (nc_inq_attlen(ncid, varid, attname, &attlen) != NC_NOERR) return NULL;
    char* text = new char[attlen + 1];
    if (nc_get_att_text(ncid, varid, attname, text) != NC_NOERR) {
        delete[] text;
        return NULL;
    }
    text[attlen] = '\0';
    return text;
}

/* CF-compliant variable finder with three-tier priority:
   P1 (gold standard): exact standard_name match
   P2 (disambiguation): if multiple matches, return first with warning
   P3 (fallback): try long_name, then variable name, with WARNING log */
static int find_var_by_cf(int ncid,
                           const char* target_std_name,
                           const char** alt_std_names,
                           const char** long_name_hints,
                           const char** var_name_hints) {
    int nvars;
    if (nc_inq(ncid, NULL, &nvars, NULL, NULL) != NC_NOERR) return -1;
    
    /* ===== Priority 1: standard_name exact match ===== */
    int best_varid = -1;
    int match_count = 0;
    
    for (int i = 0; i < nvars; i++) {
        char* std_name = read_var_att_text(ncid, i, "standard_name");
        if (!std_name) continue;
        
        if (strcmp(std_name, target_std_name) == 0) {
            if (best_varid == -1) best_varid = i;
            match_count++;
        }
        delete[] std_name;
    }
    
    if (match_count == 1) return best_varid;
    
    /* ===== Priority 2: multiple matches ===== */
    if (match_count > 1) {
        ncdfLog("[ncdf] find_var_by_cf: WARNING - %d vars with standard_name='%s', using first (varid=%d)\n",
                match_count, target_std_name, best_varid);
        return best_varid;
    }
    
    /* ===== Try alternative standard_names ===== */
    if (alt_std_names) {
        for (const char** alt = alt_std_names; *alt; alt++) {
            for (int i = 0; i < nvars; i++) {
                char* std_name = read_var_att_text(ncid, i, "standard_name");
                if (!std_name) continue;
                if (strcmp(std_name, *alt) == 0) {
                    delete[] std_name;
                    ncdfLog("[ncdf] find_var_by_cf: matched alt standard_name='%s' (target was '%s')\n",
                            *alt, target_std_name);
                    return i;
                }
                delete[] std_name;
            }
        }
    }
    
    /* ===== Priority 3a: fallback to long_name ===== */
    if (long_name_hints) {
        for (const char** hint = long_name_hints; *hint; hint++) {
            for (int i = 0; i < nvars; i++) {
                char* long_name = read_var_att_text(ncid, i, "long_name");
                if (long_name && strcmp(long_name, *hint) == 0) {
                    ncdfLog("[ncdf] find_var_by_cf: WARNING - no standard_name, matched long_name='%s' for target='%s'\n",
                            *hint, target_std_name);
                    delete[] long_name;
                    return i;
                }
                if (long_name) delete[] long_name;
            }
        }
    }
    
    /* ===== Priority 3b: fallback to variable name ===== */
    if (var_name_hints) {
        for (const char** hint = var_name_hints; *hint; hint++) {
            int varid;
            if (nc_inq_varid(ncid, *hint, &varid) == NC_NOERR) {
                ncdfLog("[ncdf] find_var_by_cf: WARNING - no standard_name, matched variable name='%s' for target='%s'\n",
                        *hint, target_std_name);
                return varid;
            }
        }
    }
    
    return -1;
}

static int find_dim_by_var(int ncid, int varid, int dim_idx) {
    int ndims;
    nc_inq_varndims(ncid, varid, &ndims);
    if (dim_idx >= ndims) return -1;
    
    int* dimids = new int[ndims];
    nc_inq_var(ncid, varid, NULL, NULL, NULL, dimids, NULL);
    int dimid = dimids[dim_idx];
    delete[] dimids;
    return dimid;
}

/* CF-compliant time unit parser.
   Parses strings like "hours since 1950-01-01 00:00:00" or "days since 1950-01-01".
   Returns seconds_per_unit and the epoch datetime. */
struct CFTimeInfo {
    wxDateTime baseDateTime;
    double secondsPerUnit;
    bool valid;
    CFTimeInfo() : secondsPerUnit(0.0), valid(false) {}
};

static CFTimeInfo ParseCFTimeUnits(const char* unitsStr) {
    CFTimeInfo info;
    wxString units(unitsStr);
    
    int sincePos = units.Find(" since ");
    if (sincePos == wxNOT_FOUND) return info;
    
    wxString unitPart = units.Left(sincePos).Trim().Lower();
    wxString datePart = units.Mid(sincePos + 7).Trim();
    
    if (unitPart.Contains("second") || unitPart == "secs" || unitPart == "sec" || unitPart == "s")
        info.secondsPerUnit = 1.0;
    else if (unitPart.Contains("minute") || unitPart == "mins" || unitPart == "min")
        info.secondsPerUnit = 60.0;
    else if (unitPart.Contains("hour") || unitPart == "hrs" || unitPart == "hr" || unitPart == "h")
        info.secondsPerUnit = 3600.0;
    else if (unitPart.Contains("day") || unitPart == "d")
        info.secondsPerUnit = 86400.0;
    else
        return info;
    
    /* Strip trailing timezone (e.g. " UTC", " +00:00", "Z") and fractional seconds */
    wxString cleanDate;
    for (size_t j = 0; j < datePart.Len(); j++) {
        wxChar c = datePart[j];
        if (c == 'Z' || c == 'z') continue;  // skip Z
        if (c == '+' || c == '-') {
            /* Check if this is a timezone offset like "+00:00" or "-05:00" */
            if (j > 0 && datePart[j-1] == ' ') {
                break;  // timezone after space
            }
            if (j > 0 && datePart[j-1] == 'T') {
                /* This could be a negative timezone like T-05:00 */
                cleanDate += c;
                continue;
            }
        }
        cleanDate += c;
    }
    /* Remove trailing whitespace */
    cleanDate = cleanDate.Trim();
    
    if (info.baseDateTime.ParseFormat(cleanDate, "%Y-%m-%d %H:%M:%S") ||
        info.baseDateTime.ParseFormat(cleanDate, "%Y-%m-%dT%H:%M:%S") ||
        info.baseDateTime.ParseFormat(cleanDate, "%Y-%m-%d") ||
        info.baseDateTime.ParseFormat(cleanDate, "%Y-%m-%dT%H:%M:%SZ") ||
        info.baseDateTime.ParseFormat(cleanDate, "%Y-%m-%dT%H:%M:%S%z") ||
        info.baseDateTime.ParseFormat(cleanDate, "%Y-%m-%d %H:%M:%S %z")) {
        info.valid = true;
    }
    
    return info;
}

int MainDialog::nc_get(wxString filestr){

	ncdfLog("[ncdf] nc_get: started\n");

	ncdfLog("[ncdf] nc_get: clearing myDataVector...\n");
	myDataVector.clear();
	ncdfLog("[ncdf] nc_get: myDataVector cleared\n");

	m_lastSelectedTimeIndex = -1;

	ncdfLog("[ncdf] nc_get: declaring variables...\n");
	int ncid;
	int time_varid, lat_varid, lon_varid;
	int u_varid, v_varid;
	int retval;

	int ndims_in, nvars_in, ngatts_in, unlimdimid_in;

	ncdfLog("[ncdf] nc_get: processing filename...\n");
	wxString filenameStr = filestr;
	ncdfLog("[ncdf] nc_get: filenameStr wxChar length=%d\n", (int)filenameStr.length());
	
	const wxCharBuffer mbBuf = filenameStr.mb_str();
	size_t mbLen = strlen(mbBuf);
	char* filename = new char[mbLen + 1];
	ncdfLog("[ncdf] nc_get: filename allocated, mbLen=%d\n", (int)mbLen);
	
	strcpy(filename, mbBuf);
	ncdfLog("[ncdf] nc_get: filename copied: %s\n", filename);

	/* Try opening without NC_NETCDF4 first (compatible with NetCDF3 classic format).
	   If that fails, retry with NC_NETCDF4 for HDF5-based NetCDF4 files. */
	retval = nc_open(filename, NC_NOWRITE, &ncid);
	if (retval != NC_NOERR) {
		retval = nc_open(filename, NC_NOWRITE | NC_NETCDF4, &ncid);
	}
	if (retval != NC_NOERR) {
		ncdfLog("[ncdf] nc_get: nc_open failed, retval=%d\n", retval);
		delete[] filename;
		return retval;
	}

	if ((retval = nc_inq(ncid, &ndims_in, &nvars_in, &ngatts_in, &unlimdimid_in))) {
		nc_close(ncid);
		delete[] filename;
		return retval;
	}

	if (ndims_in < 3 || ndims_in > 4) {
		ncdfLog("[ncdf] nc_get: unsupported ndims=%d (need 3-4)\n", ndims_in);
		nc_close(ncid);
		delete[] filename;
		return 2;
	}

	ncdfLog("[ncdf] nc_get: searching for variables using CF conventions...\n");

	/* u: eastward_sea_water_velocity */
	{
		const char* alt_std[] = {"surface_eastward_sea_water_velocity", NULL};
		const char* long_hints[] = {"Eastward Current Velocity", "u-velocity component of current", NULL};
		const char* var_hints[] = {"u", "uo", "current_u", "curr_u", "u10", "u100", NULL};
		u_varid = find_var_by_cf(ncid, "eastward_sea_water_velocity", alt_std, long_hints, var_hints);
	}
	
	/* v: northward_sea_water_velocity */
	{
		const char* alt_std[] = {"surface_northward_sea_water_velocity", NULL};
		const char* long_hints[] = {"Northward Current Velocity", "v-velocity component of current", NULL};
		const char* var_hints[] = {"v", "vo", "current_v", "curr_v", "v10", "v100", NULL};
		v_varid = find_var_by_cf(ncid, "northward_sea_water_velocity", alt_std, long_hints, var_hints);
	}
	
	/* lat: latitude */
	{
		const char* alt_std[] = {"projection_y_coordinate", NULL};
		const char* long_hints[] = {"Latitude", "latitude coordinate", NULL};
		const char* var_hints[] = {"lat", "latitude", "nav_lat", NULL};
		lat_varid = find_var_by_cf(ncid, "latitude", alt_std, long_hints, var_hints);
	}
	
	/* lon: longitude */
	{
		const char* alt_std[] = {"projection_x_coordinate", NULL};
		const char* long_hints[] = {"Longitude", "longitude coordinate", NULL};
		const char* var_hints[] = {"lon", "longitude", "nav_lon", NULL};
		lon_varid = find_var_by_cf(ncid, "longitude", alt_std, long_hints, var_hints);
	}
	
	/* time */
	{
		const char* alt_std[] = {NULL};
		const char* long_hints[] = {"Time", "time coordinate", NULL};
		const char* var_hints[] = {"time", "t", "Time", NULL};
		time_varid = find_var_by_cf(ncid, "time", alt_std, long_hints, var_hints);
	}

	/* sea surface temperature (optional, just discover the variable) */
	int sst_varid = -1;
	{
		const char* alt_std[] = {"sea_surface_temperature", "surface_temperature", NULL};
		const char* long_hints[] = {"Sea surface temperature", "sea_water_temperature", "SST", "Temperature", "temperature", NULL};
		const char* var_hints[] = {"thetao", "sst", "temperature", "temp", "SST", "votemper", "to", NULL};
		sst_varid = find_var_by_cf(ncid, "sea_water_temperature", alt_std, long_hints, var_hints);
	}
	ncdfLog("[ncdf] nc_get: sst_varid=%d\n", sst_varid);

	/* depth - commented out */
	/*int depth_varid = -1;
	{
		const char* alt_std[] = {"depth", "z", "depth_below_sea_level", NULL};
		const char* long_hints[] = {"Depth", "depth coordinate", "vertical level", NULL};
		const char* var_hints[] = {"depth", "z", "Depth", "level", NULL};
		depth_varid = find_var_by_cf(ncid, "depth", alt_std, long_hints, var_hints);
	}*/

	ncdfLog("[ncdf] nc_get: result - u_varid=%d, v_varid=%d, lat_varid=%d, lon_varid=%d, time_varid=%d, sst_varid=%d\n",
		u_varid, v_varid, lat_varid, lon_varid, time_varid, sst_varid);

	bool hasCurrent = (u_varid != -1 && v_varid != -1);
	bool hasSST = (sst_varid != -1);

	// Store file-level data availability and cached variable IDs
	m_fileHasCurrent = hasCurrent;
	m_fileHasSeaTemp = hasSST;
	m_cached_u_varid = u_varid;
	m_cached_v_varid = v_varid;
	m_cached_sst_varid = sst_varid;
	ncdfLog("[ncdf] nc_get: m_fileHasCurrent=%d, m_fileHasSeaTemp=%d, cached varids: u=%d v=%d sst=%d\n",
		(int)m_fileHasCurrent, (int)m_fileHasSeaTemp, m_cached_u_varid, m_cached_v_varid, m_cached_sst_varid);

	if (!hasCurrent && !hasSST) {
		ncdfLog("[ncdf] nc_get: no u/v and no SST, but loading file anyway for coordinate display\n");
		// Don't return error - allow the file to load for coordinate/time display
	}

	if (lat_varid == -1) {
		ncdfLog("[ncdf] nc_get: lat variable not found\n");
		nc_close(ncid);
		delete[] filename;
		return 2;
	}

	if (lon_varid == -1) {
		ncdfLog("[ncdf] nc_get: lon variable not found\n");
		nc_close(ncid);
		delete[] filename;
		return 2;
	}

	if (time_varid == -1) {
		ncdfLog("[ncdf] nc_get: time variable not found\n");
		nc_close(ncid);
		delete[] filename;
		return 2;
	}

	int timeid = find_dim_by_var(ncid, time_varid, 0);
	int latid = find_dim_by_var(ncid, lat_varid, 0);
	int lonid = find_dim_by_var(ncid, lon_varid, 0);
	/* depth - commented out */
	/*int depthid = -1;
	if (depth_varid != -1) {
		depthid = find_dim_by_var(ncid, depth_varid, 0);
	}*/

	if (timeid == -1 || latid == -1 || lonid == -1) {
		ncdfLog("[ncdf] nc_get: invalid dimension id (timeid=%d, latid=%d, lonid=%d)\n", timeid, latid, lonid);
		nc_close(ncid);
		delete[] filename;
		return 2;
	}

	size_t timelength = 0, latlength = 0, lonlength = 0/*, depthlength = 0*/;
	int status;

	if ((status = nc_inq_dimlen(ncid, timeid, &timelength)) != NC_NOERR) {
		ncdfLog("[ncdf] nc_get: failed to get time dimension length\n");
		nc_close(ncid);
		delete[] filename;
		return 2;
	}
	if ((status = nc_inq_dimlen(ncid, latid, &latlength)) != NC_NOERR) {
		ncdfLog("[ncdf] nc_get: failed to get lat dimension length\n");
		nc_close(ncid);
		delete[] filename;
		return 2;
	}
	if ((status = nc_inq_dimlen(ncid, lonid, &lonlength)) != NC_NOERR) {
		ncdfLog("[ncdf] nc_get: failed to get lon dimension length\n");
		nc_close(ncid);
		delete[] filename;
		return 2;
	}

	ncdfLog("[ncdf] nc_get: timelength=%d, latlength=%d, lonlength=%d\n", 
		(int)timelength, (int)latlength, (int)lonlength);

	wxDouble* lats = (wxDouble*)calloc(latlength, sizeof(wxDouble));
	wxDouble* lons = (wxDouble*)calloc(lonlength, sizeof(wxDouble));
	double* time_out = (double*)calloc(timelength, sizeof(double));

	if (!lats || !lons || !time_out) {
		if (lats) free(lats);
		if (lons) free(lons);
		if (time_out) free(time_out);
		nc_close(ncid);
		delete[] filename;
		return 1;
	}

	if (nc_get_var_double(ncid, lat_varid, (double*)lats) != NC_NOERR) {
		float* lat_float = (float*)calloc(latlength, sizeof(float));
		if (!lat_float) { free(lats); free(lons); free(time_out); nc_close(ncid); delete[] filename; return 1; }
		if (nc_get_var_float(ncid, lat_varid, lat_float) == NC_NOERR) {
			for (size_t i = 0; i < latlength; i++) {
				lats[i] = lat_float[i];
			}
		}
		free(lat_float);
	}
	
	if (nc_get_var_double(ncid, lon_varid, (double*)lons) != NC_NOERR) {
		float* lon_float = (float*)calloc(lonlength, sizeof(float));
		if (!lon_float) { free(lons); free(lats); free(time_out); nc_close(ncid); delete[] filename; return 1; }
		if (nc_get_var_float(ncid, lon_varid, lon_float) == NC_NOERR) {
			for (size_t i = 0; i < lonlength; i++) {
				lons[i] = lon_float[i];
			}
		}
		free(lon_float);
	}
	
	if (nc_get_var_double(ncid, time_varid, time_out) != NC_NOERR) {
		float* time_float = (float*)calloc(timelength, sizeof(float));
		if (!time_float) { free(time_out); free(lats); free(lons); nc_close(ncid); delete[] filename; return 1; }
		if (nc_get_var_float(ncid, time_varid, time_float) == NC_NOERR) {
			for (size_t i = 0; i < timelength; i++) {
				time_out[i] = time_float[i];
			}
		}
		free(time_float);
	}
	
	ncdfLog("[ncdf] nc_get: first time value = %f\n", timelength > 0 ? time_out[0] : 0.0);
	
	/* depth - commented out */
	/*wxDouble* depths = NULL;
	if (depth_varid != -1 && depthid != -1) {
		if ((status = nc_inq_dimlen(ncid, depthid, &depthlength)) != NC_NOERR) {
			ncdfLog("[ncdf] nc_get: failed to get depth dimension length, assuming surface data\n");
			depthlength = 0;
		} else {
			if (depthlength > 0) {
				depths = (wxDouble*)calloc(depthlength, sizeof(wxDouble));
				if (depths) {
					if (nc_get_var_double(ncid, depth_varid, (double*)depths) != NC_NOERR) {
						float* depth_float = (float*)calloc(depthlength, sizeof(float));
						if (depth_float) {
							if (nc_get_var_float(ncid, depth_varid, depth_float) == NC_NOERR) {
								for (size_t i = 0; i < depthlength; i++) {
									depths[i] = depth_float[i];
								}
							}
							free(depth_float);
						}
					}
					ncdfLog("[ncdf] nc_get: depth length=%d, first depth value=%f\n", 
						(int)depthlength, depths[0]);
				}
			} else {
				ncdfLog("[ncdf] nc_get: depth dimension length is 0, assuming surface data\n");
				depthlength = 0;
			}
		}
	} else {
		depthlength = 0;
	}*/

	float firstGridPointLat;
	float firstGridPointLon;
	float lastGridPointLat;
	float lastGridPointLon;
	float scale_factor = 1.0f;

	// Always use actual coordinate arrays for bounds (GRIB pattern)
	// Global attributes (latitude_min etc.) may not match the data grid exactly
	firstGridPointLat = lats[0];
	firstGridPointLon = lons[0];
	lastGridPointLat = lats[latlength - 1];
	lastGridPointLon = lons[lonlength - 1];
	
	if (nc_get_att_float(ncid, u_varid, "scale_factor", &scale_factor) != NC_NOERR) {
		scale_factor = 1.0f;
	}
	
	/* Read CF time units and parse epoch + unit */
	CFTimeInfo timeInfo;
	{
		char* timeUnits = read_var_att_text(ncid, time_varid, "units");
		if (!timeUnits) {
			timeUnits = read_var_att_text(ncid, NC_GLOBAL, "units");
			if (timeUnits) ncdfLog("[ncdf] nc_get: found time units from NC_GLOBAL: '%s'\n", timeUnits);
		}
		
		if (!timeUnits && timelength > 0) {
			double firstTimeValue = time_out[0];
			double timeStep = timelength > 1 ? time_out[1] - time_out[0] : 1.0;
			
			bool canDetermine = false;
			const int MAX_YEAR = 2050;
			
			if (firstTimeValue >= 0 && firstTimeValue <= 2000000000.0) {
				if (timeStep >= 3600.0 || timeStep >= 86400.0) {
					CFTimeInfo unixInfo = ParseCFTimeUnits("seconds since 1970-01-01");
					if (unixInfo.valid) {
						wxDateTime testDate = unixInfo.baseDateTime;
						testDate.Add(wxTimeSpan::Seconds((long long)(firstTimeValue * unixInfo.secondsPerUnit)));
						if (testDate.GetYear() <= MAX_YEAR) {
							ncdfLog("[ncdf] nc_get: WARNING - no units, guessed Unix timestamp, first date=%s (valid, <=%d)\n", 
								(const char*)testDate.Format("%Y-%m-%d").mb_str(), MAX_YEAR);
							timeInfo = unixInfo;
							canDetermine = true;
						} else {
							ncdfLog("[ncdf] nc_get: WARNING - no units, guessed Unix timestamp but first date=%s (>%d), rejecting\n", 
								(const char*)testDate.Format("%Y-%m-%d").mb_str(), MAX_YEAR);
						}
					}
				}
			}
			
			if (!canDetermine && firstTimeValue >= 0 && firstTimeValue <= 700000.0) {
				if (timeStep >= 1.0 && timeStep <= 24.0) {
					CFTimeInfo cmemsInfo = ParseCFTimeUnits("hours since 1950-01-01");
					if (cmemsInfo.valid) {
						wxDateTime testDate = cmemsInfo.baseDateTime;
						testDate.Add(wxTimeSpan::Seconds((long long)(firstTimeValue * cmemsInfo.secondsPerUnit)));
						if (testDate.GetYear() <= MAX_YEAR) {
							ncdfLog("[ncdf] nc_get: WARNING - no units, guessed CMEMS hours, first date=%s (valid, <=%d)\n", 
								(const char*)testDate.Format("%Y-%m-%d").mb_str(), MAX_YEAR);
							timeInfo = cmemsInfo;
							canDetermine = true;
						} else {
							ncdfLog("[ncdf] nc_get: WARNING - no units, guessed CMEMS hours but first date=%s (>%d), rejecting\n", 
								(const char*)testDate.Format("%Y-%m-%d").mb_str(), MAX_YEAR);
						}
					}
				}
			}
			
			if (!canDetermine) {
				ncdfLog("[ncdf] nc_get: WARNING - no units, time value=%.0f, step=%.0f, cannot reliably determine time unit, using sequential labels\n", firstTimeValue, timeStep);
				timeInfo.valid = false;
			}
		} else if (!timeUnits) {
			ncdfLog("[ncdf] nc_get: WARNING - no units and no time data, using sequential labels\n");
			timeInfo.valid = false;
		} else {
			ncdfLog("[ncdf] nc_get: time units = '%s'\n", timeUnits);
			timeInfo = ParseCFTimeUnits(timeUnits);
			delete[] timeUnits;
		}
		if (timeInfo.valid) {
			wxString fmt = timeInfo.baseDateTime.Format("%Y-%m-%d %H:%M:%S");
			ncdfLog("[ncdf] nc_get: time epoch = %s, secondsPerUnit=%f\n",
				(const char*)fmt.mb_str(), timeInfo.secondsPerUnit);
		} else {
			ncdfLog("[ncdf] nc_get: WARNING - failed to parse time units, using fallback\n");
		}
	}
	
	// 
	wxDouble iDirectionIncr = (lastGridPointLon - firstGridPointLon) / (lonlength > 1 ? lonlength - 1 : 1);
	wxDouble jDirectionIncr = (lastGridPointLat - firstGridPointLat) / (latlength > 1 ? latlength - 1 : 1);
	
	// Create message for each timestep (metadata only)
	for (size_t i = 0; i < timelength; i++) {
		
		myncdfData.clear();
		myncdfData.timeValid = timeInfo.valid;
		
		if (timeInfo.valid) {
			wxTimeSpan span = wxTimeSpan::Seconds((long long)(time_out[i] * timeInfo.secondsPerUnit));
			myncdfData.dataDateTime = timeInfo.baseDateTime;
			myncdfData.dataDateTime.Add(span);
			myncdfData.minutesAfterStart = (int)(time_out[i] * timeInfo.secondsPerUnit / 60.0);
			
			wxString dateStr = myncdfData.dataDateTime.Format("%Y-%m-%d %H:%M:%S");
			ncdfLog("[ncdf] nc_get: timestep=%d, raw_time=%f, calculated_date=%s\n",
				(int)i, time_out[i], (const char*)dateStr.mb_str());
		} else {
			myncdfData.dataDateTime = wxDateTime();
			myncdfData.minutesAfterStart = (int)(i * 60);
			ncdfLog("[ncdf] nc_get: timestep=%d, raw_time=%f, timeValid=false, using sequential label, minutesAfterStart=%d\n",
				(int)i, time_out[i], myncdfData.minutesAfterStart);
		}
		myncdfData.numberOfPoints = (int)(latlength * lonlength);
		myncdfData.noPointsParallel = (wxUint32)lonlength;
		myncdfData.noPointsMeridian = (wxUint32)latlength;
		myncdfData.firstGridPointLat = firstGridPointLat;
		myncdfData.firstGridPointLong = firstGridPointLon;
		myncdfData.lastGridPointLat = lastGridPointLat;
		myncdfData.lastGridPointLong = lastGridPointLon;
		if (i == 0) {
			ncdfLog("[ncdf] nc_get: bounds from file: lat[%.2f,%.2f] lon[%.2f,%.2f] file=%s\n",
				firstGridPointLat, lastGridPointLat, firstGridPointLon, lastGridPointLon, filename);
		}
		myncdfData.iDirectionIncr = iDirectionIncr;
		myncdfData.jDirectionIncr = jDirectionIncr;
		myncdfData.fileName = filename;
		myncdfData.timeIndex = (int)i;
		myncdfData.timeLength = timelength;
		myncdfData.latLength = latlength;
		myncdfData.lonLength = lonlength;
		myncdfData.hasSeaTemp = hasSST;
		/*myncdfData.depthLength = depthlength;*/
		
		myncdfData.latValues = (wxDouble*)calloc(latlength, sizeof(wxDouble));
		myncdfData.lonValues = (wxDouble*)calloc(lonlength, sizeof(wxDouble));
		myncdfData.timeValues = (double*)calloc(timelength, sizeof(double));
		
		/*if (depthlength > 0 && depths) {
			myncdfData.depthValues = (wxDouble*)calloc(depthlength, sizeof(wxDouble));
			memcpy(myncdfData.depthValues, depths, depthlength * sizeof(wxDouble));
		}*/
		
		memcpy(myncdfData.latValues, lats, latlength * sizeof(wxDouble));
		memcpy(myncdfData.lonValues, lons, lonlength * sizeof(wxDouble));
		memcpy(myncdfData.timeValues, time_out, timelength * sizeof(double));
		
		myDataVector.push_back(myncdfData);
	}
	
	nc_close(ncid);
	
	free(time_out);
	free(lats);
	free(lons);
	/*if (depths) {
		free(depths);
	}*/
	
	delete[] filename;

	// Update slider range to match current file's time steps
	int nSteps = (int)myDataVector.size();
	if (nSteps > 0 && m_sTimeline) {
		m_sTimeline->SetRange(0, nSteps - 1);
		m_sTimeline->SetValue(0);
	}

	return 0;
}

bool MainDialog::readTimeStepData(ncdfDataMessage& dataMessage) {
	ncdfLog("[ncdf] readTimeStepData: timeIndex=%d, latLength=%d, lonLength=%d\n", 
		dataMessage.timeIndex, (int)dataMessage.latLength, (int)dataMessage.lonLength);
		
	if (!dataMessage.latValues || !dataMessage.lonValues) {
		ncdfLog("[ncdf] readTimeStepData: latValues or lonValues is NULL\n");
		return false;
	}
	
	// Free existing SST data before reallocating (prevents leak on repeated calls)
	if (dataMessage.sst) {
		free(dataMessage.sst);
		dataMessage.sst = NULL;
	}
	dataMessage.hasSeaTemp = false;

	ncdfLog("[ncdf] readTimeStepData: freeing existing data\n");
	if (dataMessage.ucurr) {
		ncdfLog("[ncdf] readTimeStepData: freeing ucurr=%p\n", dataMessage.ucurr);
		free(dataMessage.ucurr);
		dataMessage.ucurr = NULL;
	}
	if (dataMessage.vcurr) {
		ncdfLog("[ncdf] readTimeStepData: freeing vcurr=%p\n", dataMessage.vcurr);
		free(dataMessage.vcurr);
		dataMessage.vcurr = NULL;
	}
	if (dataMessage.uvlats) {
		ncdfLog("[ncdf] readTimeStepData: freeing uvlats=%p\n", dataMessage.uvlats);
		free(dataMessage.uvlats);
		dataMessage.uvlats = NULL;
	}
	if (dataMessage.uvlons) {
		ncdfLog("[ncdf] readTimeStepData: freeing uvlons=%p\n", dataMessage.uvlons);
		free(dataMessage.uvlons);
		dataMessage.uvlons = NULL;
	}

	int ncid;
	int retval;
	
	wxString filenameStr = dataMessage.fileName;
	const wxCharBuffer mbBuf = filenameStr.mb_str();
	size_t mbLen = strlen(mbBuf);
	char* filename = new char[mbLen + 1];
	strcpy(filename, mbBuf);
	
	retval = nc_open(filename, NC_NOWRITE, &ncid);
	if (retval != NC_NOERR) {
		retval = nc_open(filename, NC_NOWRITE | NC_NETCDF4, &ncid);
	}
	if (retval != NC_NOERR) {
		ncdfLog("[ncdf] readTimeStepData: nc_open failed, retval=%d\n", retval);
		delete[] filename;
		return false;
	}
	
	// Use cached variable IDs from nc_get() (GRIB pattern: discover once, read many)
	// Fallback to CF discovery if cache is invalid (shouldn't happen in normal flow)
	int u_varid = m_cached_u_varid;
	int v_varid = m_cached_v_varid;
	if (u_varid < 0 || v_varid < 0) {
		ncdfLog("[ncdf] readTimeStepData: cache miss, falling back to CF discovery\n");
		{
			const char* alt_std[] = {"surface_eastward_sea_water_velocity", NULL};
			const char* long_hints[] = {"Eastward Current Velocity", "u-velocity component of current", NULL};
			const char* var_hints[] = {"u", "uo", "current_u", "curr_u", "u10", "u100", NULL};
			u_varid = find_var_by_cf(ncid, "eastward_sea_water_velocity", alt_std, long_hints, var_hints);
		}
		{
			const char* alt_std[] = {"surface_northward_sea_water_velocity", NULL};
			const char* long_hints[] = {"Northward Current Velocity", "v-velocity component of current", NULL};
			const char* var_hints[] = {"v", "vo", "current_v", "curr_v", "v10", "v100", NULL};
			v_varid = find_var_by_cf(ncid, "northward_sea_water_velocity", alt_std, long_hints, var_hints);
		}
	}

	bool hasUV = (u_varid != -1 && v_varid != -1);
	ncdfLog("[ncdf] readTimeStepData: hasUV=%d, u_varid=%d, v_varid=%d (cached)\n", (int)hasUV, u_varid, v_varid);

	if (hasUV) {
	ncdfLog("[ncdf] readTimeStepData: variables found, u_varid=%d, v_varid=%d\n", u_varid, v_varid);

	float fill_value_u = -32767.0f;
	float fill_value_v = -32767.0f;
	
	if (nc_get_att_float(ncid, u_varid, "_FillValue", &fill_value_u) != NC_NOERR) {
		double fill_val_double;
		if (nc_get_att_double(ncid, u_varid, "_FillValue", &fill_val_double) == NC_NOERR) {
			fill_value_u = (float)fill_val_double;
		} else {
			fill_value_u = -32767.0f;
		}
	}
	
	if (nc_get_att_float(ncid, v_varid, "_FillValue", &fill_value_v) != NC_NOERR) {
		double fill_val_double;
		if (nc_get_att_double(ncid, v_varid, "_FillValue", &fill_val_double) == NC_NOERR) {
			fill_value_v = (float)fill_val_double;
		} else {
			fill_value_v = -32767.0f;
		}
	}
	
	int ndims;
	if ((retval = nc_inq_varndims(ncid, u_varid, &ndims))) {
		nc_close(ncid);
		delete[] filename;
		return false;
	}
	
	int* dimids = (int*)calloc(ndims, sizeof(int));
	if (!dimids) { nc_close(ncid); delete[] filename; return false; }
	
	if ((retval = nc_inq_var(ncid, u_varid, NULL, NULL, NULL, dimids, NULL))) {
		free(dimids); nc_close(ncid); delete[] filename; return false;
	}
	
	int time_dimid = -1, lat_dimid = -1, lon_dimid = -1, depth_dimid = -1;
	
	nc_inq_dimid(ncid, "time", &time_dimid);
	nc_inq_dimid(ncid, "latitude", &lat_dimid);
	if (lat_dimid == -1) nc_inq_dimid(ncid, "lat", &lat_dimid);
	nc_inq_dimid(ncid, "longitude", &lon_dimid);
	if (lon_dimid == -1) nc_inq_dimid(ncid, "lon", &lon_dimid);
	nc_inq_dimid(ncid, "depth", &depth_dimid);
	if (depth_dimid == -1) nc_inq_dimid(ncid, "z", &depth_dimid);
	
	int time_idx = -1, lat_idx = -1, lon_idx = -1, depth_idx = -1;
	
	for (int i = 0; i < ndims; i++) {
		if (dimids[i] == time_dimid) time_idx = i;
		else if (dimids[i] == lat_dimid) lat_idx = i;
		else if (dimids[i] == lon_dimid) lon_idx = i;
		else if (dimids[i] == depth_dimid) depth_idx = i;
	}
	
	free(dimids);
	
	if (time_idx == -1 || lat_idx == -1 || lon_idx == -1) {
		nc_close(ncid);
		delete[] filename;
		return false;
	}
	
	bool lat_before_lon = (lat_idx < lon_idx);
	
	ncdfLog("[ncdf] readTimeStepData: dims - time_idx=%d, lat_idx=%d, lon_idx=%d, depth_idx=%d, lat_before_lon=%d\n",
		time_idx, lat_idx, lon_idx, depth_idx, (int)lat_before_lon);
	
	size_t start[4] = {0, 0, 0, 0};
	size_t count[4] = {1, 1, 1, 1};
	
	start[time_idx] = dataMessage.timeIndex;
	count[time_idx] = 1;
	
	start[lat_idx] = 0;
	count[lat_idx] = dataMessage.latLength;
	
	start[lon_idx] = 0;
	count[lon_idx] = dataMessage.lonLength;
	
	if (depth_idx != -1) {
		start[depth_idx] = 0;
		count[depth_idx] = 1;
	}
	
	size_t nbr_uv = dataMessage.latLength * dataMessage.lonLength;
	
	float* u_vals = (float*)calloc(nbr_uv, sizeof(float));
	if (!u_vals) { nc_close(ncid); delete[] filename; return false; }
	
	float* v_vals = (float*)calloc(nbr_uv, sizeof(float));
	if (!v_vals) { free(u_vals); nc_close(ncid); delete[] filename; return false; }
	
	nc_type u_type, v_type;
	nc_inq_vartype(ncid, u_varid, &u_type);
	nc_inq_vartype(ncid, v_varid, &v_type);
	
	ncdfLog("[ncdf] readTimeStepData: reading data, u_type=%d, v_type=%d, nbr_uv=%zu\n", 
		(int)u_type, (int)v_type, nbr_uv);
	
	if (u_type == NC_DOUBLE) {
		double* u_vals_double = (double*)calloc(nbr_uv, sizeof(double));
		if (!u_vals_double) { free(u_vals); free(v_vals); nc_close(ncid); delete[] filename; return false; }
		if ((retval = nc_get_vara_double(ncid, u_varid, start, count, u_vals_double))) {
			free(u_vals_double); free(u_vals); free(v_vals); nc_close(ncid); delete[] filename; return false;
		}
		for (size_t i = 0; i < nbr_uv; i++) {
			u_vals[i] = (float)u_vals_double[i];
		}
		free(u_vals_double);
	} else {
		if ((retval = nc_get_vara_float(ncid, u_varid, start, count, u_vals))) {
			free(u_vals);
			free(v_vals);
			nc_close(ncid);
			delete[] filename;
			return false;
		}
	}
	
	if (v_type == NC_DOUBLE) {
		double* v_vals_double = (double*)calloc(nbr_uv, sizeof(double));
		if (!v_vals_double) { free(u_vals); free(v_vals); nc_close(ncid); delete[] filename; return false; }
		if ((retval = nc_get_vara_double(ncid, v_varid, start, count, v_vals_double))) {
			free(v_vals_double); free(u_vals); free(v_vals); nc_close(ncid); delete[] filename; return false;
		}
		for (size_t i = 0; i < nbr_uv; i++) {
			v_vals[i] = (float)v_vals_double[i];
		}
		free(v_vals_double);
	} else {
		if ((retval = nc_get_vara_float(ncid, v_varid, start, count, v_vals))) {
			free(u_vals);
			free(v_vals);
			nc_close(ncid);
			delete[] filename;
			return false;
		}
	}
	
	ncdfLog("[ncdf] readTimeStepData: data read successfully, allocating output arrays\n");

	// ncid and filename are freed at the end of the function (after SST read)

	dataMessage.ucurr = (double*)calloc(nbr_uv, sizeof(double));
	if (!dataMessage.ucurr) {
		free(u_vals);
		free(v_vals);
		nc_close(ncid);
		delete[] filename;
		return false;
	}

	dataMessage.vcurr = (double*)calloc(nbr_uv, sizeof(double));
	if (!dataMessage.vcurr) {
		free(dataMessage.ucurr);
		dataMessage.ucurr = NULL;
		free(u_vals);
		free(v_vals);
		nc_close(ncid);
		delete[] filename;
		return false;
	}
	
	dataMessage.uvlats = (double*)calloc(nbr_uv, sizeof(double));
	if (!dataMessage.uvlats) {
		free(dataMessage.vcurr); dataMessage.vcurr = NULL;
		free(dataMessage.ucurr); dataMessage.ucurr = NULL;
		free(u_vals);
		free(v_vals);
		nc_close(ncid);
		delete[] filename;
		return false;
	}

	dataMessage.uvlons = (double*)calloc(nbr_uv, sizeof(double));
	if (!dataMessage.uvlons) {
		free(dataMessage.uvlats); dataMessage.uvlats = NULL;
		free(dataMessage.vcurr); dataMessage.vcurr = NULL;
		free(dataMessage.ucurr); dataMessage.ucurr = NULL;
		free(u_vals);
		free(v_vals);
		nc_close(ncid);
		delete[] filename;
		return false;
	}
	
	// 
	size_t count_records = 0;
	if (lat_before_lon) {
		for (size_t j = 0; j < dataMessage.latLength; j++) {
			for (size_t k = 0; k < dataMessage.lonLength; k++) {
				if (u_vals[count_records] != fill_value_u && v_vals[count_records] != fill_value_v) {
					dataMessage.uvlats[count_records] = dataMessage.latValues[j];
					dataMessage.uvlons[count_records] = dataMessage.lonValues[k];
					dataMessage.ucurr[count_records] = (double)u_vals[count_records];
					dataMessage.vcurr[count_records] = (double)v_vals[count_records];
				} else {
					dataMessage.uvlats[count_records] = ncdf_NOTDEF;
					dataMessage.uvlons[count_records] = ncdf_NOTDEF;
					dataMessage.ucurr[count_records] = ncdf_NOTDEF;
					dataMessage.vcurr[count_records] = ncdf_NOTDEF;
				}
				count_records++;
			}
		}
	} else {
		for (size_t k = 0; k < dataMessage.lonLength; k++) {
			for (size_t j = 0; j < dataMessage.latLength; j++) {
				if (u_vals[count_records] != fill_value_u && v_vals[count_records] != fill_value_v) {
					dataMessage.uvlats[count_records] = dataMessage.latValues[j];
					dataMessage.uvlons[count_records] = dataMessage.lonValues[k];
					dataMessage.ucurr[count_records] = (double)u_vals[count_records];
					dataMessage.vcurr[count_records] = (double)v_vals[count_records];
				} else {
					dataMessage.uvlats[count_records] = ncdf_NOTDEF;
					dataMessage.uvlons[count_records] = ncdf_NOTDEF;
					dataMessage.ucurr[count_records] = ncdf_NOTDEF;
					dataMessage.vcurr[count_records] = ncdf_NOTDEF;
				}
				count_records++;
			}
		}
	}
	
	free(u_vals);
	free(v_vals);
	} // end if (hasUV)

	// Read sea surface temperature using cached variable ID (GRIB pattern)
	if (ncid >= 0 && m_fileHasSeaTemp) {
		int sst_varid_local = m_cached_sst_varid;
		if (sst_varid_local < 0) {
			// Fallback: discover SST variable if cache miss
			const char* alt_std[] = {"sea_surface_temperature", "surface_temperature", NULL};
			const char* long_hints[] = {"Sea surface temperature", "sea_water_temperature", "SST", "Temperature", "temperature", NULL};
			const char* var_hints[] = {"thetao", "sst", "temperature", "temp", "SST", "votemper", "to", NULL};
			sst_varid_local = find_var_by_cf(ncid, "sea_water_temperature", alt_std, long_hints, var_hints);
		}
		if (sst_varid_local != -1) {
			size_t nbr_uv = dataMessage.latLength * dataMessage.lonLength;
			float* sst_vals = (float*)calloc(nbr_uv, sizeof(float));
			if (sst_vals) {
				// Read SST using hyperslab (current time step only)
				int sst_ndims;
				nc_inq_varndims(ncid, sst_varid_local, &sst_ndims);
				int sst_dimids[NC_MAX_DIMS];
				nc_inq_vardimid(ncid, sst_varid_local, sst_dimids);
				size_t sst_start[NC_MAX_DIMS] = {0};
				size_t sst_count[NC_MAX_DIMS] = {0};
				for (int d = 0; d < sst_ndims; d++) {
					char dimname[NC_MAX_NAME + 1];
					size_t dimlen;
					nc_inq_dim(ncid, sst_dimids[d], dimname, &dimlen);
					if (strstr(dimname, "time") || strstr(dimname, "Time")) {
						sst_start[d] = dataMessage.timeIndex;
						sst_count[d] = 1;
					} else if (strstr(dimname, "lat") || strstr(dimname, "Lat")) {
						sst_count[d] = dataMessage.latLength;
					} else if (strstr(dimname, "lon") || strstr(dimname, "Lon")) {
						sst_count[d] = dataMessage.lonLength;
					} else {
						sst_count[d] = 1;
					}
				}
				nc_get_vara_float(ncid, sst_varid_local, sst_start, sst_count, sst_vals);

				bool isKelvin = false;
				char units_str[64] = {0};
				if (nc_get_att_text(ncid, sst_varid_local, "units", units_str) == NC_NOERR) {
					if (strstr(units_str, "K") || strstr(units_str, "kelvin")) isKelvin = true;
				}

				float sst_fill = -32767.0f;
				nc_get_att_float(ncid, sst_varid_local, "_FillValue", &sst_fill);

				dataMessage.sst = (double*)calloc(nbr_uv, sizeof(double));
				for (size_t k = 0; k < nbr_uv; k++) {
					double val = (double)sst_vals[k];
					if (!isnan(val) && isfinite(val) && val != sst_fill && val > 100.0) {
						dataMessage.sst[k] = isKelvin ? (val - 273.15) : val;
					} else {
						dataMessage.sst[k] = ncdf_NOTDEF;
					}
				}
				free(sst_vals);
				ncdfLog("[ncdf] readTimeStepData: SST read, isKelvin=%d\n", (int)isKelvin);
				dataMessage.hasSeaTemp = true;
			}
		}
	}

	ncdfLog("[ncdf] readTimeStepData: completed successfully\n");

	nc_close(ncid);
	delete[] filename;

	return true;
}

wxDateTime MainDialog::GetDateFromHours(int hours_in){

	wxString baseDateTime = _T("2011-12-31 00:00:00");

	wxDateTime m_dt;
	m_dt.ParseDateTime(baseDateTime);

	wxTimeSpan m_ts = wxTimeSpan::Hours(hours_in);
	m_dt.Add(m_ts);

	return m_dt;
}


void MainDialog::onDirChanged(wxCommandEvent& event)
{
    ncdfLogW(L"[ncdf] onDirChanged: started, value=%ls\n", (const wchar_t*)this->m_textCtrlDir->GetValue().c_str());
	
	wxStandardPathsBase &std_path = wxStandardPathsBase::Get();
	wxString std = std_path.GetDocumentsDir();

	if(this->m_textCtrlDir->GetValue().length() != 0 && pPlugIn->m_ncdf_dir != std_path.GetDocumentsDir()){
	    ncdfLog("[ncdf] onDirChanged: calling fillDirTree\n");
		fillDirTree(this->m_textCtrlDir->GetValue(), true, 0);
	    ncdfLog("[ncdf] onDirChanged: fillDirTree returned\n");
	}
	else{
	    ncdfLog("[ncdf] onDirChanged: deleting all tree items\n");
		this->m_treeCtrl->DeleteAllItems();
	}
}

void MainDialog::onTreeSelectionChanged(wxTreeEvent& event)
{
    ncdfLog("[ncdf] onTreeSelectionChanged: started\n");
	
	if (m_isTreeUpdating) {
		ncdfLog("[ncdf] onTreeSelectionChanged: m_isTreeUpdating=true, returning\n");
		return;
	}
	
	if(this->my_ncdfReader->isReading == true){
	    ncdfLog("[ncdf] onTreeSelectionChanged: isReading=true, returning\n");
		ncdfDialog::onTreeSelectionChanged(event); 
		return; 
	}

 	if(this->m_treeCtrl->GetRootItem() == event.GetItem()){
	    ncdfLog("[ncdf] onTreeSelectionChanged: root item selected, returning\n");
		return;
	}
	
	if (this->m_treeCtrl->HasChildren(event.GetItem())){
	    // File node clicked: load data and auto-select first time step
	    wxString fn = m_treeCtrl->GetItemText(event.GetItem());
	    wxString fileName = m_textCtrlDir->GetValue() + _T("\\") + fn;
	    ncdfLogW(L"[ncdf] file node clicked: fn=%ls, fileName=%ls\n", (const wchar_t*)fn.c_str(), (const wchar_t*)fileName.c_str());

	    // Guard against re-entrant calls: nc_get + SelectItem can trigger
	    // onTreeSelectionChanged again. Block it and process manually.
	    m_isTreeUpdating = true;
	    int ret = nc_get(fileName);
	    ncdfLog("[ncdf] nc_get returned: %d, myDataVector size=%d\n", ret, (int)myDataVector.size());
	    m_isTreeUpdating = false;

	    if (ret != 0 || myDataVector.empty()) {
	        ncdfDialog::onTreeSelectionChanged(event);
	        return;
	    }

	    // Clean up old grids (atomic swap: save old, set NULL, nc_get will rebuild via readncdfFile)
	    wxUint32 oldMeridian = myMessage.noPointsMeridian;
	    double **oldGridu = gridu; gridu = NULL;
	    double **oldGridv = gridv; gridv = NULL;
	    double **oldGridSST = gridSST; gridSST = NULL;
	    hasSeaTemp = false;
	    // Free old grids after setting pointers to NULL (prevents stale access)
	    if (oldGridu) {
	        for (wxUint32 i = 0; i < oldMeridian; ++i) delete[] oldGridu[i];
	        delete[] oldGridu;
	    }
	    if (oldGridv) {
	        for (wxUint32 i = 0; i < oldMeridian; ++i) delete[] oldGridv[i];
	        delete[] oldGridv;
	    }
	    if (oldGridSST) {
	        for (wxUint32 i = 0; i < oldMeridian; ++i) delete[] oldGridSST[i];
	        delete[] oldGridSST;
	    }
	    hasSeaTemp = false;
	    m_lastSelectedTimeIndex = -1;
	    pPlugIn->GetncdfOverlayFactory()->reset();

	    // Set up timeline range (data loaded lazily when user selects a time step)
	    int nSteps = (int)myDataVector.size();
	    if (nSteps > 0 && m_sTimeline) {
	        m_sTimeline->SetRange(0, nSteps - 1);
	        m_sTimeline->SetValue(0);
	    }

		ncdfDialog::onTreeSelectionChanged(event);
		// Show checkboxes based on file-level data availability
		bool showCurrent = m_fileHasCurrent;
		bool showSST = m_fileHasSeaTemp;
		m_checkBoxDCurrent->Show(showCurrent);
		m_staticText333->Show(showCurrent);
		m_textCtrlCurrentDir->Show(showCurrent);
		m_staticText341->Show(showCurrent);
		m_checkBoxBmpCurrentForce->Show(showCurrent);
		m_staticText40->Show(showCurrent);
		m_textCtrlCurrentForce->Show(showCurrent);
		m_staticText41->Show(showCurrent);
		m_checkBoxParticles->Show(showCurrent);
		m_staticTextParticles->Show(showCurrent);
		m_checkBoxSeaTemp->Show(showSST);
		m_staticTextSeaTemp->Show(showSST);
		m_textCtrlSeaTemp->Show(showSST);
		m_staticTextSeaTempUnit->Show(showSST);
		m_staticTextSeaTempIso->Show(showSST);
		Layout();
		if (!showCurrent) {
			pPlugIn->m_bShowCurrentDir = false;
			pPlugIn->m_bShowCurrentForce = false;
			pPlugIn->m_bShowParticles = false;
		} else {
			// Auto-enable current rendering when current data is available (GRIB pattern)
			pPlugIn->m_bShowCurrentDir = m_checkBoxDCurrent->GetValue();
			pPlugIn->m_bShowCurrentForce = m_checkBoxBmpCurrentForce->GetValue();
		}
		if (!showSST) {
			pPlugIn->m_bShowSeaTemp = false;
			pPlugIn->m_bShowSeaTempIso = false;
		}
		return;
    }

	ncdfDialog::onTreeSelectionChanged(event);

	MyTreeItemData* data = (MyTreeItemData*)this->m_treeCtrl->GetItemData(event.GetItem());
	if (data) {
		int idx = data->m_index;

		// Check if we need to load a different file first
		wxTreeItemId parentItem = m_treeCtrl->GetItemParent(event.GetItem());
		if (parentItem.IsOk()) {
			wxString fn = m_treeCtrl->GetItemText(parentItem);
			wxString fileName = m_textCtrlDir->GetValue() + _T("\\") + fn;
			if (fileName != m_currentFilePath) {
				ncdfLogW(L"[ncdf] onTreeSelectionChanged: switching to file %ls\n", (const wchar_t*)fn.c_str());
				myDataVector.clear();
				m_lastSelectedTimeIndex = -1;
				m_choiceTime->Clear();

				// Clean up old grids before loading new file (GRIB pattern: reset on file change)
				if (gridu) {
					for (wxUint32 i = 0; i < myMessage.noPointsMeridian; ++i) delete[] gridu[i];
					delete[] gridu; gridu = NULL;
				}
				if (gridv) {
					for (wxUint32 i = 0; i < myMessage.noPointsMeridian; ++i) delete[] gridv[i];
					delete[] gridv; gridv = NULL;
				}
				if (gridSST) {
					for (wxUint32 i = 0; i < myMessage.noPointsMeridian; ++i) delete[] gridSST[i];
					delete[] gridSST; gridSST = NULL;
				}
				hasSeaTemp = false;
				pPlugIn->GetncdfOverlayFactory()->reset();

				int ret = nc_get(fileName);
				if (ret != 0) {
					ncdfLog("[ncdf] onTreeSelectionChanged: nc_get failed for %s\n", (const char*)fn.mb_str());
					return;
				}
				m_currentFilePath = fileName;
				idx = data->m_index;

				// Auto-enable rendering for available data types (GRIB pattern)
				bool showCur = m_fileHasCurrent;
				bool showSST = m_fileHasSeaTemp;
				m_checkBoxDCurrent->Show(showCur);
				m_staticText333->Show(showCur);
				m_textCtrlCurrentDir->Show(showCur);
				m_staticText341->Show(showCur);
				m_checkBoxBmpCurrentForce->Show(showCur);
				m_staticText40->Show(showCur);
				m_textCtrlCurrentForce->Show(showCur);
				m_staticText41->Show(showCur);
				m_checkBoxParticles->Show(showCur);
				m_staticTextParticles->Show(showCur);
				m_checkBoxSeaTemp->Show(showSST);
				m_staticTextSeaTemp->Show(showSST);
				m_textCtrlSeaTemp->Show(showSST);
		m_staticTextSeaTempUnit->Show(showSST);
				m_checkBoxSeaTempIso->Show(showSST);
				m_staticTextSeaTempIso->Show(showSST);
				Layout();
				if (showSST) {
					pPlugIn->m_bShowSeaTemp = false;
					m_checkBoxSeaTemp->SetValue(false);
				} else {
					pPlugIn->m_bShowSeaTemp = false;
					pPlugIn->m_bShowSeaTempIso = false;
				}
				if (!showCur) {
					pPlugIn->m_bShowCurrentDir = false;
					pPlugIn->m_bShowCurrentForce = false;
					pPlugIn->m_bShowParticles = false;
				}
			}
		}

		ncdfLog("[ncdf] onTreeSelectionChanged: got MyTreeItemData=%p, index=%d, vectorSize=%d\n",
			data, idx, (int)myDataVector.size());
		
		if (idx < 0 || idx >= (int)myDataVector.size()) {
			ncdfLog("[ncdf] onTreeSelectionChanged: index out of range\n");
			ncdfLog("[ncdf] onTreeSelectionChanged: completed\n");
			return;
		}
		
		// Only clear previous time step's data if switching to a different one
		if (m_lastSelectedTimeIndex >= 0 && m_lastSelectedTimeIndex != idx &&
		    m_lastSelectedTimeIndex < (int)myDataVector.size()) {
			myDataVector[m_lastSelectedTimeIndex].clear();
		}

		myData = myDataVector[idx];
		m_lastSelectedTimeIndex = idx;

		// Sync slider with tree selection (guard against OnTimeline re-entrancy)
		m_isTreeUpdating = true;
		m_sTimeline->SetValue(idx);
		m_isTreeUpdating = false;
		
		wxString timeText;
		if (myData.timeValid) {
			timeText = myData.dataDateTime.Format(_T("%Y-%m-%d %H:00"));
		} else {
			timeText = wxString::Format(_("时间%d"), idx + 1);
		}
		m_staticTextDateTime->SetLabel(timeText);

		if (readTimeStepData(myData)) {
			ncdfLog("[ncdf] onTreeSelectionChanged: readTimeStepData OK, hasSeaTemp=%d sst=%p\n",
				(int)myData.hasSeaTemp, (void*)myData.sst);
			ncdfLog("[ncdf] onTreeSelectionChanged: calling readncdfFile...\n");
			this->my_ncdfReader->readncdfFile(myData);
			ncdfLog("[ncdf] onTreeSelectionChanged: readncdfFile returned\n");
			pPlugIn->GetncdfOverlayFactory()->renderSelectionRectangle = false;
			ncdfLog("[ncdf] onTreeSelectionChanged: requesting refresh\n");
			RequestRefresh(m_parent);
			ncdfLog("[ncdf] onTreeSelectionChanged: refresh requested\n");
		} else {
			ncdfLog("[ncdf] onTreeSelectionChanged: readTimeStepData failed\n");
		}
	} else {
		ncdfLog("[ncdf] onTreeSelectionChanged: GetItemData returned NULL\n");
	}

	// Show/hide checkboxes based on file-level data availability (like GRIB plugin)
	bool showCurrent = m_fileHasCurrent;
	bool showSST = m_fileHasSeaTemp;
	ncdfLog("[ncdf] onTreeSelectionChanged: showCurrent=%d showSST=%d (file-level)\n",
		(int)showCurrent, (int)showSST);
	// Current checkboxes: show if file has current data
	m_checkBoxDCurrent->Show(showCurrent);
	m_staticText333->Show(showCurrent);
	m_textCtrlCurrentDir->Show(showCurrent);
		m_staticText341->Show(showCurrent);
	m_checkBoxBmpCurrentForce->Show(showCurrent);
	m_staticText40->Show(showCurrent);
	m_textCtrlCurrentForce->Show(showCurrent);
	m_staticText41->Show(showCurrent);
	m_checkBoxParticles->Show(showCurrent);
	m_staticTextParticles->Show(showCurrent);
	// SST checkboxes: show if file has SST data
	m_checkBoxSeaTemp->Show(showSST);
	m_staticTextSeaTemp->Show(showSST);
	m_textCtrlSeaTemp->Show(showSST);
	m_staticTextSeaTempUnit->Show(showSST);
	m_checkBoxSeaTempIso->Show(showSST);
	m_staticTextSeaTempIso->Show(showSST);
	// Force layout update
	Layout();
	// Disable plugin state for unavailable data types
	if (!showCurrent) {
		pPlugIn->m_bShowCurrentDir = false;
		pPlugIn->m_bShowCurrentForce = false;
		pPlugIn->m_bShowParticles = false;
	}
	if (!showSST) {
		pPlugIn->m_bShowSeaTemp = false;
		pPlugIn->m_bShowSeaTempIso = false;
	}

	ncdfLog("[ncdf] onTreeSelectionChanged: completed\n");
}

void MainDialog::onTimeChange(wxCommandEvent& event){
    int selectedIndex = m_choiceTime->GetSelection();

    if (selectedIndex >= 0 && selectedIndex < (int)myDataVector.size()) {
        myData = myDataVector[selectedIndex];
        m_lastSelectedTimeIndex = selectedIndex;

        wxString timeText;
        if (myData.timeValid) {
            timeText = myData.dataDateTime.Format(_T("%Y-%m-%d %H:00"));
        } else {
            timeText = wxString::Format(_("时间%d"), selectedIndex + 1);
        }
        m_staticTextDateTime->SetLabel(timeText);

        // Sync slider (guard against OnTimeline re-entrancy)
        m_isTreeUpdating = true;
        m_sTimeline->SetValue(selectedIndex);
        m_isTreeUpdating = false;

        readTimeStepData(myData);
        my_ncdfReader->readncdfFile(myData);
        RequestRefresh(m_parent);
    }
}

void MainDialog::OnTimeline(wxScrollEvent& event)
{
    int selectedIndex = m_sTimeline->GetValue();

    // Only switch time steps within the current file (don't load new files)
    if (selectedIndex >= 0 && selectedIndex < (int)myDataVector.size()) {
        if (m_lastSelectedTimeIndex >= 0 && m_lastSelectedTimeIndex < (int)myDataVector.size()) {
            myDataVector[m_lastSelectedTimeIndex].clear();
        }

        myData = myDataVector[selectedIndex];
        m_lastSelectedTimeIndex = selectedIndex;

        // Sync choice control
        m_choiceTime->SetSelection(selectedIndex);

        wxString timeText;
        if (myData.timeValid) {
            timeText = myData.dataDateTime.Format(_T("%Y-%m-%d %H:00"));
        } else {
            timeText = wxString::Format(_("时间%d"), selectedIndex + 1);
        }
        m_staticTextDateTime->SetLabel(timeText);

        // Sync tree control selection (use m_isTreeUpdating to prevent event recursion)
        m_isTreeUpdating = true;
        wxTreeItemId currentItem = m_treeCtrl->GetFocusedItem();
        if (currentItem.IsOk()) {
            wxTreeItemId fileNode = m_treeCtrl->GetItemParent(currentItem);
            if (!fileNode.IsOk() || fileNode == m_treeCtrl->GetRootItem()) {
                fileNode = currentItem;
            }
            if (m_treeCtrl->HasChildren(fileNode)) {
                // Clear any previous drop highlights
                wxTreeItemIdValue clearCookie;
                wxTreeItemId clearChild = m_treeCtrl->GetFirstChild(fileNode, clearCookie);
                while (clearChild.IsOk()) {
                    m_treeCtrl->SetItemDropHighlight(clearChild, false);
                    clearChild = m_treeCtrl->GetNextSibling(clearChild);
                }

                wxTreeItemIdValue childCookie;
                wxTreeItemId childItem = m_treeCtrl->GetFirstChild(fileNode, childCookie);
                int treeIdx = 0;
                while (childItem.IsOk()) {
                    if (treeIdx == selectedIndex) {
                        m_treeCtrl->SelectItem(childItem);
                        m_treeCtrl->SetFocusedItem(childItem);
                        m_treeCtrl->EnsureVisible(childItem);
                        break;
                    }
                    childItem = m_treeCtrl->GetNextSibling(childItem);
                    treeIdx++;
                }
            }
        }
        m_isTreeUpdating = false;

        readTimeStepData(myData);
        my_ncdfReader->readncdfFile(myData);
        RequestRefresh(m_parent);
    }
}

void MainDialog::onTreeItemRightClick(wxTreeEvent& event)
{
    if(this->m_treeCtrl->GetRootItem() == event.GetItem())
		return;

    wxTreeItemId id =  this->m_treeCtrl->GetSelection();
    MyTreeItemData *data = (MyTreeItemData *) this->m_treeCtrl->GetItemData(id);
}

void MainDialog::onDCurrentClick( wxCommandEvent& event )
{
	pPlugIn->m_bShowCurrentDir = m_checkBoxDCurrent->GetValue();
	RequestRefresh(m_parent);
}
void MainDialog::onBmpCurrentForceClick(wxCommandEvent& event)
{
	pPlugIn->m_bShowCurrentForce = m_checkBoxBmpCurrentForce->GetValue();
	RequestRefresh(m_parent);
}

void MainDialog::onParticlesClick(wxCommandEvent& event)
{
	pPlugIn->m_bShowParticles = !pPlugIn->m_bShowParticles;
	RequestRefresh(m_parent);
}

void MainDialog::onSeaTempClick(wxCommandEvent& event)
{
	pPlugIn->m_bShowSeaTemp = m_checkBoxSeaTemp->GetValue();
	RequestRefresh(m_parent);
}

void MainDialog::onSeaTempIsoClick(wxCommandEvent& event)
{
	pPlugIn->m_bShowSeaTempIso = m_checkBoxSeaTempIso->GetValue();
	RequestRefresh(m_parent);
}

void MainDialog::fillDirTree(wxString path, bool start, wxTreeItemId id)
{
    ncdfLogW(L"[ncdf] fillDirTree: started, path=%ls, start=%d\n", (const wchar_t*)path.c_str(), (int)start);

	if(start == true)
	{
		ncdfLog("[ncdf] fillDirTree: deleting all tree items\n");
		
		m_isTreeUpdating = true;
		m_treeCtrl->Freeze();
		this->m_treeCtrl->DeleteAllItems();
		
		id = this->m_treeCtrl->AddRoot(_T(""));
		this->m_treeCtrl->SetItemText(id,_("ncdf-Files"));
		this->m_treeCtrl->SelectItem(id);
		m_isTreeUpdating = false;
		m_treeCtrl->Thaw();
		
		ncdfLog("[ncdf] fillDirTree: root item created\n");
	}

	wxDir dir(path);
	if(dir.IsOpened() && dir.HasFiles())
	{
		ncdfLog("[ncdf] fillDirTree: directory opened successfully\n");
		wxString s;
		if (dir.GetFirst(&s, wxEmptyString, wxDIR_FILES)) {
			do {
				wxString ext = s.Mid(s.find_last_of('.') + 1).Lower();
				if (ext == "nc" || ext == "nc4") {
					ncdfLogW(L"[ncdf] fillDirTree: adding file: %ls\n", (const wchar_t*)s.c_str());
					
					wxTreeItemId iid = this->m_treeCtrl->AppendItem(id, s);
					
					ncdfLogW(L"[ncdf] fillDirTree: calling addChildren for %ls\n", (const wchar_t*)s.c_str());
					addChildren(iid, s);
					
					ncdfLog("[ncdf] fillDirTree: addChildren returned\n");
				}
			} while (dir.GetNext(&s));
		}
	}
	
	ncdfLog("[ncdf] fillDirTree: completed\n");
}

void MainDialog::addChildren(wxTreeItemId id, wxString fn)
{
    ncdfLogW(L"[ncdf] addChildren: started, fn=%ls\n", (const wchar_t*)fn.c_str());

	wxDateTime dt;
	wxString fileName;

	fileName = this->m_textCtrlDir->GetValue()+_("\\")+fn;
	
	ncdfLogW(L"[ncdf] addChildren: fileName=%ls\n", (const wchar_t*)fileName.c_str());

	/* Save existing data in case nc_get fails */
	std::vector<ncdfDataMessage> savedVector = myDataVector;
	int savedIndex = m_lastSelectedTimeIndex;

	myDataVector.clear();
	m_lastSelectedTimeIndex = -1;
	m_choiceTime->Clear();
	m_currentFilePath = fileName;

	ncdfLog("[ncdf] addChildren: calling nc_get\n");
	int ret = nc_get(fileName);

	if (ret != 0) {
		/* Restore previous data on failure */
		myDataVector = savedVector;
		m_lastSelectedTimeIndex = savedIndex;
		ncdfLog("[ncdf] addChildren: nc_get failed with return code=%d, restored existing data (size=%d)\n",
			ret, (int)myDataVector.size());
		return;
	}
	ncdfLog("[ncdf] addChildren: nc_get returned, myDataVector size=%d\n", (int)myDataVector.size());

	int timeIndex = 0;
	for (vector<ncdfDataMessage>::iterator it = myDataVector.begin(); it != myDataVector.end(); it++){

		dt = (*it).dataDateTime;

		wxTreeItemId itemId = this->m_treeCtrl->AppendItem(id, _T(""));
		wxString timeText;
		
		if ((*it).timeValid) {
			timeText = dt.Format(_T("%Y-%m-%d %H:00"));
		} else {
			timeText = wxString::Format(_("时间%d"), timeIndex + 1);
		}
		
		/* depth - commented out */
		/*wxString itemText;
		if ((*it).depthValues && (*it).depthLength > 0) {
			wxString depthText = wxString::Format(_("%.1f m"), (*it).depthValues[(*it).depthIndex]);
			itemText = wxString::Format(_("%s (%s)"), timeText.c_str(), depthText.c_str());
		} else {
			itemText = timeText;
		}*/
		wxString itemText = timeText;
		
		this->m_treeCtrl->SetItemText(itemId, itemText);
		
		MyTreeItemData* treeItemData = new MyTreeItemData(timeIndex);
		this->m_treeCtrl->SetItemData(itemId, treeItemData);
		
		m_choiceTime->Append(itemText);

		timeIndex++;
	}

	// Update slider range to match number of time steps
	int nSteps = (int)myDataVector.size();
	if (nSteps > 0) {
		m_sTimeline->SetRange(0, nSteps - 1);
		m_sTimeline->SetValue(0);
	}

	ncdfLog("[ncdf] addChildren: completed\n");

}

void MainDialog::OnContextMenu(double m_lat, double m_lon){

	// show some info about this item
	wxTreeItemId itemId = m_treeCtrl->GetFocusedItem();
	MyTreeItemData *item = (MyTreeItemData *)this->m_treeCtrl->GetItemData(itemId);

	if (item == NULL)
	{
		return;
	}

	int response;
	wxMessageDialog *dial = new wxMessageDialog(NULL, _T("Show tidal current at the cursor position?"), wxT("Proceed?"), wxOK | wxCANCEL);

	response = dial->ShowModal();

	if (response == wxID_OK) {
		pPlugIn->b_showODAS = true;
		Arrow *m_Arrow = new Arrow;
		m_Arrow->m_lat = m_lat;
		m_Arrow->m_lon = m_lon;
		m_ArrowList.push_back(m_Arrow);
	}
	else{
		pPlugIn->b_showODAS = false;
		m_ArrowList.clear();

		return;
	}
}

void MainDialog::BuildHelpPage(){

	wxString myHelp;
	myHelp = _("This page is intended to help users download \nthe areas to use with the ncdf plugin.\n\nThe display Areas for ncdf Tidal Currents\n are as follows:\n\nFormat: \nLat(Min), Lat(Max), Lon(Min), Lon(Max)\n\nEnglish Channel:           48, 51, -7, -2\nIrish Sea:                         50, 56, -9, -2\nSouthern Brittany:         46.5, 48.5, -5.5, -0.5\nNorth Sea:                      51, 56, -2.5, 5\nBiscay South:                 43, 47, -9.5, -0.5\nWestern Ireland:            50, 56, -12, -8               ");
	m_staticText6->SetLabel(myHelp);
}

